"""
FY3 Zaytoven Collection — Bass Presets
=======================================
100 bass presets (FY3_BAS_001 → FY3_BAS_100)
Covers all Zaytoven eras with authentic 808s, organ bass, synth bass, and sub-bass.

Bass types: 808_sub, 808_dist, organ_bass, synth_bass, pluck_bass, deep_sub
Era split: 33 Early (2005-2010) / 34 Peak (2010-2016) / 33 Modern (2016+)
"""

BASS_PRESETS = [
    # ═══════════════════════════════════════════════════════════════════════════
    #  EARLY ERA (2005-2010) — FY3_BAS_001 → FY3_BAS_033
    #  Clean 808 subs, organ bass from church roots, Zone 6 fundamentals
    # ═══════════════════════════════════════════════════════════════════════════

    {
        "id": "FY3_BAS_001",
        "name": "Trap House Sub",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'Trap House' (2005) — the OG clean 808 sub that started it all",
        "instrument_breakdown": "Pure sine 808, 2-semitone pitch drop, long 2.5s decay, minimal filtering",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.0,
            "decay_time": 2.5,
            "filter_cutoff": 400,
            "distortion": 0.0,
            "attack": 0.003,
            "sustain": 0.7,
            "release": 0.3,
            "eq_low": 2,
            "eq_mid": -2,
        },
    },
    {
        "id": "FY3_BAS_002",
        "name": "Zone 6 Church Bass",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Zaytoven's church organ bass lines from early Gucci sessions",
        "instrument_breakdown": "Organ bass with sub-octave, slight tube overdrive, warm low-mids",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "organ_bass",
            "pitch_drop": 0.0,
            "decay_time": 2.0,
            "filter_cutoff": 1200,
            "distortion": 0.15,
            "attack": 0.008,
            "sustain": 0.85,
            "release": 0.4,
            "eq_low": 3,
            "eq_mid": 1,
        },
    },
    {
        "id": "FY3_BAS_003",
        "name": "Jeezy Snowman Sub",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Young Jeezy 'Trap or Die' (2005) — booming clean sub that shakes trunks",
        "instrument_breakdown": "808 sub with extended 3s decay, deep pitch drop, heavy low EQ boost",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 3.0,
            "decay_time": 3.0,
            "filter_cutoff": 350,
            "distortion": 0.0,
            "attack": 0.002,
            "sustain": 0.65,
            "release": 0.4,
            "eq_low": 4,
            "eq_mid": -3,
        },
    },
    {
        "id": "FY3_BAS_004",
        "name": "So Icy Deep Sub",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'So Icy' (2005) — clean, deep sub for minimal trap beats",
        "instrument_breakdown": "Deep sub sine, very clean with minimal harmonics, smooth envelope",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "deep_sub",
            "pitch_drop": 1.0,
            "decay_time": 2.0,
            "filter_cutoff": 300,
            "distortion": 0.0,
            "attack": 0.01,
            "sustain": 0.9,
            "release": 0.5,
            "eq_low": 3,
            "eq_mid": -1,
        },
    },
    {
        "id": "FY3_BAS_005",
        "name": "Hard In Da Paint 808",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Waka Flocka Flame 'Hard in da Paint' (2010) — aggressive short 808 hits",
        "instrument_breakdown": "808 sub with fast decay, punchy attack, slight saturation for presence",
        "note": 40,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 1.5,
            "decay_time": 1.2,
            "filter_cutoff": 500,
            "distortion": 0.05,
            "attack": 0.002,
            "sustain": 0.5,
            "release": 0.2,
            "eq_low": 2,
            "eq_mid": 0,
        },
    },
    {
        "id": "FY3_BAS_006",
        "name": "Chicken Talk Organ Bass",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'Chicken Talk' (2006) — gospel organ bass lines under trap drums",
        "instrument_breakdown": "Organ bass with strong sub-octave, tube overdrive, key click",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "organ_bass",
            "pitch_drop": 0.0,
            "decay_time": 1.8,
            "filter_cutoff": 1400,
            "distortion": 0.2,
            "attack": 0.006,
            "sustain": 0.88,
            "release": 0.35,
            "eq_low": 3,
            "eq_mid": 2,
        },
    },
    {
        "id": "FY3_BAS_007",
        "name": "Burrprint 808",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'Burrprint 3D' (2009) — warm 808 sub with moderate decay",
        "instrument_breakdown": "808 sub, 2-semitone drop, warm filtering, clean and round",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.0,
            "decay_time": 2.0,
            "filter_cutoff": 450,
            "distortion": 0.02,
            "attack": 0.003,
            "sustain": 0.72,
            "release": 0.3,
            "eq_low": 2,
            "eq_mid": -1,
        },
    },
    {
        "id": "FY3_BAS_008",
        "name": "State Vs Radric 808",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'The State vs. Radric Davis' (2009) — polished album 808",
        "instrument_breakdown": "808 sub with controlled decay, slight compression, radio-ready sub",
        "note": 41,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 1.5,
            "decay_time": 1.8,
            "filter_cutoff": 420,
            "distortion": 0.03,
            "attack": 0.003,
            "sustain": 0.68,
            "release": 0.35,
            "eq_low": 3,
            "eq_mid": -2,
        },
    },
    {
        "id": "FY3_BAS_009",
        "name": "First Day Out Deep",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'First Day Out' — deep resonant sub-bass, minimal processing",
        "instrument_breakdown": "Deep sub with extended sustain, very low cutoff, pure sine character",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "deep_sub",
            "pitch_drop": 0.5,
            "decay_time": 2.5,
            "filter_cutoff": 280,
            "distortion": 0.0,
            "attack": 0.008,
            "sustain": 0.92,
            "release": 0.6,
            "eq_low": 4,
            "eq_mid": -2,
        },
    },
    {
        "id": "FY3_BAS_010",
        "name": "Trap Back Jumpin Sub",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'Trap Back' series — bouncy 808 with quick pitch drop",
        "instrument_breakdown": "808 sub with fast 1-semitone drop, medium decay, trunk-rattling low end",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 1.0,
            "decay_time": 1.6,
            "filter_cutoff": 380,
            "distortion": 0.01,
            "attack": 0.002,
            "sustain": 0.6,
            "release": 0.25,
            "eq_low": 3,
            "eq_mid": -1,
        },
    },
    {
        "id": "FY3_BAS_011",
        "name": "Murder Was the Case Bass",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Early Zaytoven dark beats — menacing low organ bass with grit",
        "instrument_breakdown": "Organ bass with heavier overdrive, dark filtering, sustained growl",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "organ_bass",
            "pitch_drop": 0.0,
            "decay_time": 2.2,
            "filter_cutoff": 1000,
            "distortion": 0.28,
            "attack": 0.008,
            "sustain": 0.82,
            "release": 0.4,
            "eq_low": 4,
            "eq_mid": 0,
        },
    },
    {
        "id": "FY3_BAS_012",
        "name": "Lemonade 808",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'Lemonade' (2009) — bouncy melodic 808 pattern",
        "instrument_breakdown": "808 sub with moderate pitch drop, controlled decay for fast patterns",
        "note": 40,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.5,
            "decay_time": 1.4,
            "filter_cutoff": 400,
            "distortion": 0.02,
            "attack": 0.002,
            "sustain": 0.55,
            "release": 0.2,
            "eq_low": 2,
            "eq_mid": -1,
        },
    },
    {
        "id": "FY3_BAS_013",
        "name": "Freaky Gurl Sub",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'Freaky Gurl' (2007) — smooth radio-ready sub",
        "instrument_breakdown": "Clean 808 sub with gentle decay, smooth filtering, subtle warmth",
        "note": 41,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 1.0,
            "decay_time": 2.0,
            "filter_cutoff": 380,
            "distortion": 0.01,
            "attack": 0.003,
            "sustain": 0.7,
            "release": 0.35,
            "eq_low": 2,
            "eq_mid": 0,
        },
    },
    {
        "id": "FY3_BAS_014",
        "name": "OJ da Juiceman Pluck",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "OJ da Juiceman 'Make tha Trap Say Aye' — snappy pluck bass for bouncy beats",
        "instrument_breakdown": "Pluck bass with fast decay, filter envelope, percussive character",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "pluck_bass",
            "pitch_drop": 0.5,
            "decay_time": 0.8,
            "filter_cutoff": 1200,
            "distortion": 0.0,
            "attack": 0.002,
            "sustain": 0.3,
            "release": 0.15,
            "eq_low": 2,
            "eq_mid": 1,
        },
    },
    {
        "id": "FY3_BAS_015",
        "name": "Photoshoot Synth Bass",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'Photoshoot' — filtered synth bass for melodic beats",
        "instrument_breakdown": "Filtered sawtooth synth bass, resonant filter, punchy envelope",
        "note": 40,
        "duration": 8.0,
        "params": {
            "bass_type": "synth_bass",
            "pitch_drop": 0.0,
            "decay_time": 1.5,
            "filter_cutoff": 1000,
            "distortion": 0.1,
            "attack": 0.003,
            "sustain": 0.65,
            "release": 0.25,
            "eq_low": 2,
            "eq_mid": 1,
        },
    },
    {
        "id": "FY3_BAS_016",
        "name": "Wasted Long Sub",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'Wasted' (2009) — extended sustain 808 for party records",
        "instrument_breakdown": "808 sub with extra-long 3.5s decay, clean and boomy",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.0,
            "decay_time": 3.5,
            "filter_cutoff": 350,
            "distortion": 0.0,
            "attack": 0.003,
            "sustain": 0.75,
            "release": 0.5,
            "eq_low": 4,
            "eq_mid": -3,
        },
    },
    {
        "id": "FY3_BAS_017",
        "name": "745 Deep Sub",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane '745' — floor-shaking deep sub bass",
        "instrument_breakdown": "Deep sub, ultra-clean sine, very low filter, smooth envelope",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "deep_sub",
            "pitch_drop": 0.0,
            "decay_time": 2.8,
            "filter_cutoff": 250,
            "distortion": 0.0,
            "attack": 0.012,
            "sustain": 0.93,
            "release": 0.6,
            "eq_low": 5,
            "eq_mid": -3,
        },
    },
    {
        "id": "FY3_BAS_018",
        "name": "I Think I Love Her 808",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'I Think I Love Her' — smooth melodic 808",
        "instrument_breakdown": "808 sub with musical pitch drop, warm decay, balanced mix",
        "note": 43,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 1.5,
            "decay_time": 2.0,
            "filter_cutoff": 420,
            "distortion": 0.01,
            "attack": 0.003,
            "sustain": 0.7,
            "release": 0.3,
            "eq_low": 2,
            "eq_mid": 0,
        },
    },
    {
        "id": "FY3_BAS_019",
        "name": "Go Head Organ Low",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Early Zaytoven organ bass patterns — gospel-influenced walking bass",
        "instrument_breakdown": "Organ bass with warm sub-octave, slight click, moderate overdrive",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "organ_bass",
            "pitch_drop": 0.0,
            "decay_time": 1.6,
            "filter_cutoff": 1300,
            "distortion": 0.18,
            "attack": 0.006,
            "sustain": 0.86,
            "release": 0.3,
            "eq_low": 3,
            "eq_mid": 1,
        },
    },
    {
        "id": "FY3_BAS_020",
        "name": "Pillz Punchy Sub",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'Pillz' — tight punchy sub for uptempo trap",
        "instrument_breakdown": "808 sub with short decay, fast attack, controlled low end",
        "note": 40,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 1.0,
            "decay_time": 1.0,
            "filter_cutoff": 450,
            "distortion": 0.02,
            "attack": 0.002,
            "sustain": 0.5,
            "release": 0.15,
            "eq_low": 2,
            "eq_mid": 0,
        },
    },
    {
        "id": "FY3_BAS_021",
        "name": "Classical Trap Sub",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane early classical-sampled beats — foundational sub",
        "instrument_breakdown": "Deep sub with smooth attack, sustained body, pure low end",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "deep_sub",
            "pitch_drop": 0.5,
            "decay_time": 2.2,
            "filter_cutoff": 320,
            "distortion": 0.0,
            "attack": 0.015,
            "sustain": 0.88,
            "release": 0.5,
            "eq_low": 3,
            "eq_mid": -2,
        },
    },
    {
        "id": "FY3_BAS_022",
        "name": "Yellow Diamonds 808",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'Yellow Diamonds' — bright 808 with presence",
        "instrument_breakdown": "808 sub with slightly higher cutoff for presence, moderate decay",
        "note": 41,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.0,
            "decay_time": 1.8,
            "filter_cutoff": 480,
            "distortion": 0.03,
            "attack": 0.003,
            "sustain": 0.65,
            "release": 0.25,
            "eq_low": 2,
            "eq_mid": 0,
        },
    },
    {
        "id": "FY3_BAS_023",
        "name": "Gingerbread Man Bass",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane dark early cuts — heavy organ bass for menacing beats",
        "instrument_breakdown": "Organ bass with heavy sub, aggressive overdrive, dark character",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "organ_bass",
            "pitch_drop": 0.0,
            "decay_time": 2.0,
            "filter_cutoff": 900,
            "distortion": 0.3,
            "attack": 0.008,
            "sustain": 0.8,
            "release": 0.35,
            "eq_low": 4,
            "eq_mid": -1,
        },
    },
    {
        "id": "FY3_BAS_024",
        "name": "Trap Star Sub",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'Trap Star' — classic Zone 6 trunk-rattling 808",
        "instrument_breakdown": "808 sub with big pitch drop, long sustain, maximum low end",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 3.5,
            "decay_time": 2.8,
            "filter_cutoff": 360,
            "distortion": 0.01,
            "attack": 0.002,
            "sustain": 0.72,
            "release": 0.4,
            "eq_low": 5,
            "eq_mid": -3,
        },
    },
    {
        "id": "FY3_BAS_025",
        "name": "Dope Boys Pluck",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Young Jeezy/Gucci crossover era — percussive pluck bass for hard beats",
        "instrument_breakdown": "Pluck bass with sharp transient, fast filter sweep, snappy",
        "note": 40,
        "duration": 8.0,
        "params": {
            "bass_type": "pluck_bass",
            "pitch_drop": 0.0,
            "decay_time": 0.6,
            "filter_cutoff": 1400,
            "distortion": 0.05,
            "attack": 0.001,
            "sustain": 0.25,
            "release": 0.1,
            "eq_low": 2,
            "eq_mid": 2,
        },
    },
    {
        "id": "FY3_BAS_026",
        "name": "Swing My Door Sub",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'Swing My Door' — heavy sliding 808 sub",
        "instrument_breakdown": "808 sub with extra pitch slide, deep and resonant",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 4.0,
            "decay_time": 2.5,
            "filter_cutoff": 380,
            "distortion": 0.01,
            "attack": 0.002,
            "sustain": 0.68,
            "release": 0.35,
            "eq_low": 4,
            "eq_mid": -2,
        },
    },
    {
        "id": "FY3_BAS_027",
        "name": "Street Credibility Bass",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Zaytoven-produced street records — synth bass with attitude",
        "instrument_breakdown": "Synth bass with resonant filter, punchy attack, slight dirt",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "synth_bass",
            "pitch_drop": 0.0,
            "decay_time": 1.4,
            "filter_cutoff": 1100,
            "distortion": 0.15,
            "attack": 0.003,
            "sustain": 0.6,
            "release": 0.2,
            "eq_low": 3,
            "eq_mid": 1,
        },
    },
    {
        "id": "FY3_BAS_028",
        "name": "Mouth Full of Gold Sub",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Early Gucci gold era — heavy 808 with shimmer from upper harmonics",
        "instrument_breakdown": "808 sub with slight saturation for harmonic presence, extended decay",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.0,
            "decay_time": 2.6,
            "filter_cutoff": 500,
            "distortion": 0.06,
            "attack": 0.003,
            "sustain": 0.7,
            "release": 0.35,
            "eq_low": 3,
            "eq_mid": -1,
        },
    },
    {
        "id": "FY3_BAS_029",
        "name": "Definition of a G Sub",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'Definition of a G' — standard Zone 6 808 sub",
        "instrument_breakdown": "Clean 808 sub, standard parameters, reliable and deep",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.0,
            "decay_time": 2.0,
            "filter_cutoff": 400,
            "distortion": 0.0,
            "attack": 0.003,
            "sustain": 0.7,
            "release": 0.3,
            "eq_low": 2,
            "eq_mid": -1,
        },
    },
    {
        "id": "FY3_BAS_030",
        "name": "Hood Classics Deep",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Zaytoven hood classics compilation — versatile deep sub",
        "instrument_breakdown": "Deep sub with warm character, smooth transitions, clean bottom end",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "deep_sub",
            "pitch_drop": 1.0,
            "decay_time": 2.0,
            "filter_cutoff": 300,
            "distortion": 0.0,
            "attack": 0.01,
            "sustain": 0.9,
            "release": 0.4,
            "eq_low": 3,
            "eq_mid": -1,
        },
    },
    {
        "id": "FY3_BAS_031",
        "name": "Worst Enemy Organ Sub",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'Worst Enemy' — organ bass with gospel weight",
        "instrument_breakdown": "Organ bass with heavy sub-octave emphasis, warm overdrive",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "organ_bass",
            "pitch_drop": 0.0,
            "decay_time": 2.0,
            "filter_cutoff": 1100,
            "distortion": 0.22,
            "attack": 0.006,
            "sustain": 0.84,
            "release": 0.35,
            "eq_low": 4,
            "eq_mid": 1,
        },
    },
    {
        "id": "FY3_BAS_032",
        "name": "Stash House 808",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'Stash House' mixtape — tight controlled 808",
        "instrument_breakdown": "808 sub with medium decay, clean mix, slight warmth",
        "note": 40,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 1.5,
            "decay_time": 1.5,
            "filter_cutoff": 420,
            "distortion": 0.02,
            "attack": 0.002,
            "sustain": 0.6,
            "release": 0.2,
            "eq_low": 2,
            "eq_mid": 0,
        },
    },
    {
        "id": "FY3_BAS_033",
        "name": "Brick Factory Foundation",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'Brick Factory' series — foundational 808 for brick talk",
        "instrument_breakdown": "808 sub with solid low end, moderate settings, rock-solid foundation",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.0,
            "decay_time": 2.2,
            "filter_cutoff": 400,
            "distortion": 0.01,
            "attack": 0.003,
            "sustain": 0.7,
            "release": 0.3,
            "eq_low": 3,
            "eq_mid": -2,
        },
    },

    # ═══════════════════════════════════════════════════════════════════════════
    #  PEAK ERA (2010-2016) — FY3_BAS_034 → FY3_BAS_067
    #  Distorted 808s emerge, heavier processing, Migos/Future influence
    # ═══════════════════════════════════════════════════════════════════════════

    {
        "id": "FY3_BAS_034",
        "name": "Versace 808 Boom",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos 'Versace' (2013) — the 808 that launched a thousand ad-libs",
        "instrument_breakdown": "808 sub with aggressive pitch drop, medium-long decay, trunk presence",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 3.0,
            "decay_time": 2.2,
            "filter_cutoff": 420,
            "distortion": 0.04,
            "attack": 0.002,
            "sustain": 0.68,
            "release": 0.3,
            "eq_low": 3,
            "eq_mid": -1,
        },
    },
    {
        "id": "FY3_BAS_035",
        "name": "Hannah Montana Dist",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos 'Hannah Montana' (2013) — distorted 808 with attitude",
        "instrument_breakdown": "808 distorted with dual-stage saturation, heavy harmonics, compressed",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "808_dist",
            "pitch_drop": 2.0,
            "decay_time": 2.0,
            "filter_cutoff": 1800,
            "distortion": 0.5,
            "attack": 0.002,
            "sustain": 0.6,
            "release": 0.25,
            "eq_low": 2,
            "eq_mid": 1,
        },
    },
    {
        "id": "FY3_BAS_036",
        "name": "Fight Night 808",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos 'Fight Night' (2014) — hard-hitting 808 with punch",
        "instrument_breakdown": "808 sub with fast attack, aggressive pitch drop, punchy character",
        "note": 40,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 3.5,
            "decay_time": 1.8,
            "filter_cutoff": 450,
            "distortion": 0.05,
            "attack": 0.002,
            "sustain": 0.6,
            "release": 0.2,
            "eq_low": 3,
            "eq_mid": 0,
        },
    },
    {
        "id": "FY3_BAS_037",
        "name": "YRN Dirty 808",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos 'Young Rich N*ggas' mixtape (2013) — gritty distorted 808",
        "instrument_breakdown": "808 distorted with medium drive, warm tube saturation",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_dist",
            "pitch_drop": 2.5,
            "decay_time": 2.0,
            "filter_cutoff": 2000,
            "distortion": 0.55,
            "attack": 0.002,
            "sustain": 0.62,
            "release": 0.25,
            "eq_low": 2,
            "eq_mid": 2,
        },
    },
    {
        "id": "FY3_BAS_038",
        "name": "Trap Queen 808",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Peak era radio trap — clean 808 with mainstream polish",
        "instrument_breakdown": "808 sub with balanced parameters, radio-ready mix",
        "note": 41,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 1.5,
            "decay_time": 2.0,
            "filter_cutoff": 400,
            "distortion": 0.02,
            "attack": 0.003,
            "sustain": 0.7,
            "release": 0.3,
            "eq_low": 2,
            "eq_mid": -1,
        },
    },
    {
        "id": "FY3_BAS_039",
        "name": "Papers Organ Low",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Usher 'Papers' (2010) — polished organ bass for R&B-trap crossover",
        "instrument_breakdown": "Organ bass with refined character, moderate overdrive, smooth sustain",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "organ_bass",
            "pitch_drop": 0.0,
            "decay_time": 1.8,
            "filter_cutoff": 1500,
            "distortion": 0.12,
            "attack": 0.008,
            "sustain": 0.88,
            "release": 0.4,
            "eq_low": 2,
            "eq_mid": 2,
        },
    },
    {
        "id": "FY3_BAS_040",
        "name": "Future Dirty Sprite 808",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Future 'Dirty Sprite 2' (2015) — dark distorted 808 with weight",
        "instrument_breakdown": "808 distorted with heavy drive, dark filtering, compressed punch",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_dist",
            "pitch_drop": 2.0,
            "decay_time": 2.5,
            "filter_cutoff": 1500,
            "distortion": 0.65,
            "attack": 0.002,
            "sustain": 0.65,
            "release": 0.3,
            "eq_low": 3,
            "eq_mid": 0,
        },
    },
    {
        "id": "FY3_BAS_041",
        "name": "March Madness Sub",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Future 'March Madness' (2015) — heavy sub for anthemic trap",
        "instrument_breakdown": "808 sub with maximum low end, long decay, minimal harmonics",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.5,
            "decay_time": 3.0,
            "filter_cutoff": 350,
            "distortion": 0.01,
            "attack": 0.002,
            "sustain": 0.72,
            "release": 0.4,
            "eq_low": 5,
            "eq_mid": -3,
        },
    },
    {
        "id": "FY3_BAS_042",
        "name": "Everybody Looking Dist",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Gucci Mane 'Everybody Looking' (2016) — refined distorted 808",
        "instrument_breakdown": "808 distorted with controlled saturation, polished mix, punchy attack",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "808_dist",
            "pitch_drop": 2.0,
            "decay_time": 1.8,
            "filter_cutoff": 2200,
            "distortion": 0.45,
            "attack": 0.002,
            "sustain": 0.6,
            "release": 0.25,
            "eq_low": 2,
            "eq_mid": 1,
        },
    },
    {
        "id": "FY3_BAS_043",
        "name": "1st Day Out Tha Feds Sub",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Gucci Mane '1st Day Out Tha Feds' (2016) — triumphant return 808",
        "instrument_breakdown": "Clean 808 sub with powerful low end, moderate pitch drop",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.0,
            "decay_time": 2.5,
            "filter_cutoff": 400,
            "distortion": 0.02,
            "attack": 0.002,
            "sustain": 0.7,
            "release": 0.35,
            "eq_low": 4,
            "eq_mid": -2,
        },
    },
    {
        "id": "FY3_BAS_044",
        "name": "Handsome & Wealthy Sub",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos 'Handsome and Wealthy' (2014) — smooth 808 for melodic flows",
        "instrument_breakdown": "808 sub with musical character, smooth decay, warm filtering",
        "note": 43,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 1.5,
            "decay_time": 2.0,
            "filter_cutoff": 380,
            "distortion": 0.01,
            "attack": 0.003,
            "sustain": 0.7,
            "release": 0.3,
            "eq_low": 2,
            "eq_mid": 0,
        },
    },
    {
        "id": "FY3_BAS_045",
        "name": "Pipe It Up Dist",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos 'Pipe It Up' (2015) — aggressive distorted 808 for hype tracks",
        "instrument_breakdown": "808 distorted with heavy saturation, bright harmonics, fast decay",
        "note": 40,
        "duration": 8.0,
        "params": {
            "bass_type": "808_dist",
            "pitch_drop": 1.5,
            "decay_time": 1.5,
            "filter_cutoff": 2500,
            "distortion": 0.6,
            "attack": 0.002,
            "sustain": 0.5,
            "release": 0.2,
            "eq_low": 1,
            "eq_mid": 2,
        },
    },
    {
        "id": "FY3_BAS_046",
        "name": "Look At My Dab Sub",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos 'Look At My Dab' (2015) — bouncy 808 for dance tracks",
        "instrument_breakdown": "808 sub with tight decay for fast patterns, bouncy character",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.0,
            "decay_time": 1.2,
            "filter_cutoff": 420,
            "distortion": 0.03,
            "attack": 0.002,
            "sustain": 0.55,
            "release": 0.15,
            "eq_low": 2,
            "eq_mid": 0,
        },
    },
    {
        "id": "FY3_BAS_047",
        "name": "One Time Pluck Bass",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos 'One Time' — percussive pluck bass for uptempo flows",
        "instrument_breakdown": "Pluck bass with tight envelope, filter sweep, percussive snap",
        "note": 40,
        "duration": 8.0,
        "params": {
            "bass_type": "pluck_bass",
            "pitch_drop": 0.5,
            "decay_time": 0.7,
            "filter_cutoff": 1500,
            "distortion": 0.05,
            "attack": 0.001,
            "sustain": 0.2,
            "release": 0.1,
            "eq_low": 2,
            "eq_mid": 2,
        },
    },
    {
        "id": "FY3_BAS_048",
        "name": "Cross The Country 808",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos 'Cross the Country' — highway-cruising 808 with weight",
        "instrument_breakdown": "808 sub with extended decay, deep pitch, car-system tuned",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 3.0,
            "decay_time": 2.8,
            "filter_cutoff": 380,
            "distortion": 0.02,
            "attack": 0.002,
            "sustain": 0.7,
            "release": 0.35,
            "eq_low": 4,
            "eq_mid": -2,
        },
    },
    {
        "id": "FY3_BAS_049",
        "name": "Gucci Comeback Organ Bass",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Gucci Mane post-prison era — evolved organ bass with polish",
        "instrument_breakdown": "Organ bass with refined overdrive, balanced harmonics, clean sub",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "organ_bass",
            "pitch_drop": 0.0,
            "decay_time": 1.8,
            "filter_cutoff": 1400,
            "distortion": 0.16,
            "attack": 0.006,
            "sustain": 0.86,
            "release": 0.35,
            "eq_low": 3,
            "eq_mid": 2,
        },
    },
    {
        "id": "FY3_BAS_050",
        "name": "Wop Heavy Dist",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Gucci Mane 'Woptober' (2016) — heavy distorted 808 with maximum grit",
        "instrument_breakdown": "808 distorted with high drive, aggressive tube saturation, dark",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_dist",
            "pitch_drop": 2.5,
            "decay_time": 2.2,
            "filter_cutoff": 1600,
            "distortion": 0.7,
            "attack": 0.002,
            "sustain": 0.6,
            "release": 0.3,
            "eq_low": 3,
            "eq_mid": 1,
        },
    },
    {
        "id": "FY3_BAS_051",
        "name": "Trap God Sub",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Gucci Mane 'Trap God' mixtape (2012) — godly 808 sub bass",
        "instrument_breakdown": "808 sub with perfect parameters, deep and controlled",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.5,
            "decay_time": 2.5,
            "filter_cutoff": 400,
            "distortion": 0.01,
            "attack": 0.002,
            "sustain": 0.7,
            "release": 0.3,
            "eq_low": 4,
            "eq_mid": -2,
        },
    },
    {
        "id": "FY3_BAS_052",
        "name": "Migos Synth Bass",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos experimental tracks — filtered synth bass for variety",
        "instrument_breakdown": "Synth bass with resonant filter, tight envelope, bright character",
        "note": 40,
        "duration": 8.0,
        "params": {
            "bass_type": "synth_bass",
            "pitch_drop": 0.0,
            "decay_time": 1.2,
            "filter_cutoff": 1200,
            "distortion": 0.15,
            "attack": 0.003,
            "sustain": 0.6,
            "release": 0.2,
            "eq_low": 2,
            "eq_mid": 2,
        },
    },
    {
        "id": "FY3_BAS_053",
        "name": "Freak No More 808",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos 'Freak No More' (2015) — bouncy 808 with character",
        "instrument_breakdown": "808 sub with musical pitch drop, tight decay for melodic patterns",
        "note": 41,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.0,
            "decay_time": 1.6,
            "filter_cutoff": 420,
            "distortion": 0.02,
            "attack": 0.002,
            "sustain": 0.6,
            "release": 0.2,
            "eq_low": 2,
            "eq_mid": -1,
        },
    },
    {
        "id": "FY3_BAS_054",
        "name": "Chirpin Deep Sub",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Gucci Mane 'Chirpin' — ultra-deep sub for slow trap",
        "instrument_breakdown": "Deep sub with maximum low-end, extended sustain, floor-shaking",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "deep_sub",
            "pitch_drop": 0.5,
            "decay_time": 3.0,
            "filter_cutoff": 250,
            "distortion": 0.0,
            "attack": 0.01,
            "sustain": 0.95,
            "release": 0.6,
            "eq_low": 5,
            "eq_mid": -3,
        },
    },
    {
        "id": "FY3_BAS_055",
        "name": "No Label 808",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos 'No Label 2' mixtape (2014) — independent hustle 808",
        "instrument_breakdown": "808 sub with solid fundamentals, reliable and hard-hitting",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.0,
            "decay_time": 2.0,
            "filter_cutoff": 400,
            "distortion": 0.03,
            "attack": 0.002,
            "sustain": 0.68,
            "release": 0.25,
            "eq_low": 3,
            "eq_mid": -1,
        },
    },
    {
        "id": "FY3_BAS_056",
        "name": "Clientele Dist 808",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Gucci Mane 'Trap House IV' (2014) — refined distorted 808",
        "instrument_breakdown": "808 distorted with moderate drive, controlled harmonics",
        "note": 40,
        "duration": 8.0,
        "params": {
            "bass_type": "808_dist",
            "pitch_drop": 2.0,
            "decay_time": 1.8,
            "filter_cutoff": 1800,
            "distortion": 0.5,
            "attack": 0.002,
            "sustain": 0.6,
            "release": 0.25,
            "eq_low": 2,
            "eq_mid": 1,
        },
    },
    {
        "id": "FY3_BAS_057",
        "name": "Migos Walk It Sub",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos ad-lib era — walking 808 bass lines with groove",
        "instrument_breakdown": "808 sub with shorter decay for rhythmic patterns, tight and punchy",
        "note": 40,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 1.5,
            "decay_time": 1.2,
            "filter_cutoff": 450,
            "distortion": 0.02,
            "attack": 0.002,
            "sustain": 0.55,
            "release": 0.15,
            "eq_low": 2,
            "eq_mid": 0,
        },
    },
    {
        "id": "FY3_BAS_058",
        "name": "Jungle Organ Bass",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos 'Jungle' — organ bass with aggressive character",
        "instrument_breakdown": "Organ bass with heavier overdrive, punchy attack, aggressive",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "organ_bass",
            "pitch_drop": 0.0,
            "decay_time": 1.6,
            "filter_cutoff": 1100,
            "distortion": 0.25,
            "attack": 0.005,
            "sustain": 0.82,
            "release": 0.3,
            "eq_low": 4,
            "eq_mid": 1,
        },
    },
    {
        "id": "FY3_BAS_059",
        "name": "Get Right Witcha Sub",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos 'Get Right Witcha' — clean bouncy sub for head-nodding",
        "instrument_breakdown": "808 sub with musical bounce, controlled decay, clean mix",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.0,
            "decay_time": 1.8,
            "filter_cutoff": 400,
            "distortion": 0.01,
            "attack": 0.003,
            "sustain": 0.65,
            "release": 0.25,
            "eq_low": 3,
            "eq_mid": -1,
        },
    },
    {
        "id": "FY3_BAS_060",
        "name": "Ice Tray Heavy Dist",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Peak era flex tracks — maximum distortion 808 for hard beats",
        "instrument_breakdown": "808 distorted with maximum drive, crushed harmonics, aggressive",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_dist",
            "pitch_drop": 3.0,
            "decay_time": 2.0,
            "filter_cutoff": 2000,
            "distortion": 0.8,
            "attack": 0.002,
            "sustain": 0.55,
            "release": 0.25,
            "eq_low": 1,
            "eq_mid": 3,
        },
    },
    {
        "id": "FY3_BAS_061",
        "name": "Peak Era Synth Bass",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Zaytoven peak era — synth bass experiments with trap drums",
        "instrument_breakdown": "Synth bass with heavy resonance, warm filtering, fat sawtooth",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "synth_bass",
            "pitch_drop": 0.0,
            "decay_time": 1.5,
            "filter_cutoff": 900,
            "distortion": 0.2,
            "attack": 0.003,
            "sustain": 0.65,
            "release": 0.25,
            "eq_low": 3,
            "eq_mid": 1,
        },
    },
    {
        "id": "FY3_BAS_062",
        "name": "Bando Sub Long",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos 'Bando' (2013) — sustained 808 for the trap house anthem",
        "instrument_breakdown": "808 sub with extra-long 3s decay, deep and sustained",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.5,
            "decay_time": 3.0,
            "filter_cutoff": 360,
            "distortion": 0.01,
            "attack": 0.002,
            "sustain": 0.72,
            "release": 0.4,
            "eq_low": 4,
            "eq_mid": -2,
        },
    },
    {
        "id": "FY3_BAS_063",
        "name": "Roller Coaster Pluck",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Peak era experimental — snappy pluck bass for rapid-fire patterns",
        "instrument_breakdown": "Pluck bass with extra-fast decay, bright transient, percussive",
        "note": 41,
        "duration": 8.0,
        "params": {
            "bass_type": "pluck_bass",
            "pitch_drop": 0.0,
            "decay_time": 0.5,
            "filter_cutoff": 1600,
            "distortion": 0.08,
            "attack": 0.001,
            "sustain": 0.15,
            "release": 0.08,
            "eq_low": 2,
            "eq_mid": 3,
        },
    },
    {
        "id": "FY3_BAS_064",
        "name": "Commando 808",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos 'Commando' (2014) — military precision 808 hits",
        "instrument_breakdown": "808 sub with tight attack, controlled decay, disciplined low end",
        "note": 40,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 1.5,
            "decay_time": 1.4,
            "filter_cutoff": 420,
            "distortion": 0.03,
            "attack": 0.002,
            "sustain": 0.58,
            "release": 0.2,
            "eq_low": 2,
            "eq_mid": 0,
        },
    },
    {
        "id": "FY3_BAS_065",
        "name": "Real Atlanta Deep",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Gucci Mane 'Real Atlanta' — authentic deep sub for street records",
        "instrument_breakdown": "Deep sub with extended sustain, pure sine, maximum depth",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "deep_sub",
            "pitch_drop": 0.0,
            "decay_time": 2.5,
            "filter_cutoff": 280,
            "distortion": 0.0,
            "attack": 0.012,
            "sustain": 0.92,
            "release": 0.5,
            "eq_low": 4,
            "eq_mid": -2,
        },
    },
    {
        "id": "FY3_BAS_066",
        "name": "Offset Melody 808",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Offset solo cuts — melodic 808 with musical pitch slides",
        "instrument_breakdown": "808 sub with wide pitch drop for melodic bass lines",
        "note": 43,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 4.0,
            "decay_time": 2.2,
            "filter_cutoff": 400,
            "distortion": 0.02,
            "attack": 0.002,
            "sustain": 0.68,
            "release": 0.3,
            "eq_low": 3,
            "eq_mid": -1,
        },
    },
    {
        "id": "FY3_BAS_067",
        "name": "Slippery When Wet Dist",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos 'Slippery' era — wet distorted 808 with character",
        "instrument_breakdown": "808 distorted with medium-heavy drive, warm saturation, full body",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "808_dist",
            "pitch_drop": 2.0,
            "decay_time": 2.0,
            "filter_cutoff": 1800,
            "distortion": 0.55,
            "attack": 0.002,
            "sustain": 0.62,
            "release": 0.25,
            "eq_low": 2,
            "eq_mid": 2,
        },
    },

    # ═══════════════════════════════════════════════════════════════════════════
    #  MODERN ERA (2016+) — FY3_BAS_068 → FY3_BAS_100
    #  Evolved 808 processing, GloRilla/21 Savage influence, modern trap bass
    # ═══════════════════════════════════════════════════════════════════════════

    {
        "id": "FY3_BAS_068",
        "name": "Culture 808",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Migos 'Culture' (2017) — the album that defined modern trap 808s",
        "instrument_breakdown": "808 sub with refined parameters, modern mix-ready, deep and punchy",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.5,
            "decay_time": 2.2,
            "filter_cutoff": 420,
            "distortion": 0.03,
            "attack": 0.002,
            "sustain": 0.68,
            "release": 0.3,
            "eq_low": 3,
            "eq_mid": -1,
        },
    },
    {
        "id": "FY3_BAS_069",
        "name": "Bad and Boujee 808",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Migos 'Bad and Boujee' (2017) — the #1 hit 808 with maximum impact",
        "instrument_breakdown": "808 sub with big pitch drop, precise decay, chart-topping low end",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 3.0,
            "decay_time": 2.0,
            "filter_cutoff": 400,
            "distortion": 0.04,
            "attack": 0.002,
            "sustain": 0.65,
            "release": 0.25,
            "eq_low": 3,
            "eq_mid": 0,
        },
    },
    {
        "id": "FY3_BAS_070",
        "name": "Trap Holizay Modern Dist",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Zaytoven 'Trap Holizay' (2018) — modern evolved distorted 808",
        "instrument_breakdown": "808 distorted with modern processing, balanced harmonics, clear distortion",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_dist",
            "pitch_drop": 2.0,
            "decay_time": 2.2,
            "filter_cutoff": 2000,
            "distortion": 0.55,
            "attack": 0.002,
            "sustain": 0.62,
            "release": 0.28,
            "eq_low": 2,
            "eq_mid": 2,
        },
    },
    {
        "id": "FY3_BAS_071",
        "name": "GloRilla Stomp 808",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "GloRilla Memphis-meets-ATL trap — stomping 808 with impact",
        "instrument_breakdown": "808 sub with aggressive attack, heavy low end, club-rattling",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 3.5,
            "decay_time": 1.8,
            "filter_cutoff": 450,
            "distortion": 0.05,
            "attack": 0.001,
            "sustain": 0.6,
            "release": 0.2,
            "eq_low": 4,
            "eq_mid": -1,
        },
    },
    {
        "id": "FY3_BAS_072",
        "name": "21 Savage Dark Sub",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "21 Savage x Zaytoven — dark menacing sub for savage beats",
        "instrument_breakdown": "Deep sub with dark character, slow attack, ominous presence",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "deep_sub",
            "pitch_drop": 1.0,
            "decay_time": 2.5,
            "filter_cutoff": 260,
            "distortion": 0.0,
            "attack": 0.015,
            "sustain": 0.9,
            "release": 0.5,
            "eq_low": 4,
            "eq_mid": -3,
        },
    },
    {
        "id": "FY3_BAS_073",
        "name": "Young Dolph Heavy 808",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Young Dolph Memphis trap influence — heavy 808 with maximum weight",
        "instrument_breakdown": "808 sub with massive low end, extended decay, weight and presence",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 3.0,
            "decay_time": 3.0,
            "filter_cutoff": 380,
            "distortion": 0.02,
            "attack": 0.002,
            "sustain": 0.72,
            "release": 0.4,
            "eq_low": 5,
            "eq_mid": -3,
        },
    },
    {
        "id": "FY3_BAS_074",
        "name": "Lil Uzi Bass Bounce",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Lil Uzi Vert Zaytoven collabs — bouncy 808 for energetic flows",
        "instrument_breakdown": "808 sub with fast attack, bouncy decay, energetic character",
        "note": 40,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.0,
            "decay_time": 1.4,
            "filter_cutoff": 450,
            "distortion": 0.04,
            "attack": 0.002,
            "sustain": 0.58,
            "release": 0.2,
            "eq_low": 2,
            "eq_mid": 0,
        },
    },
    {
        "id": "FY3_BAS_075",
        "name": "Quavo Huncho Dist",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Quavo 'Quavo Huncho' (2018) — distorted 808 for solo work",
        "instrument_breakdown": "808 distorted with modern saturation, clear attack, balanced mix",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "808_dist",
            "pitch_drop": 2.0,
            "decay_time": 1.8,
            "filter_cutoff": 2200,
            "distortion": 0.5,
            "attack": 0.002,
            "sustain": 0.6,
            "release": 0.25,
            "eq_low": 2,
            "eq_mid": 2,
        },
    },
    {
        "id": "FY3_BAS_076",
        "name": "Takeoff Spaceship Sub",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Takeoff 'The Last Rocket' (2018) — spacey sub with depth",
        "instrument_breakdown": "808 sub with extra-wide pitch drop, spacious character",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 4.5,
            "decay_time": 2.5,
            "filter_cutoff": 380,
            "distortion": 0.01,
            "attack": 0.002,
            "sustain": 0.7,
            "release": 0.35,
            "eq_low": 4,
            "eq_mid": -2,
        },
    },
    {
        "id": "FY3_BAS_077",
        "name": "Modern Organ Bass",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Zaytoven modern church organ bass — evolved from gospel roots",
        "instrument_breakdown": "Organ bass with polished character, controlled overdrive, modern mix",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "organ_bass",
            "pitch_drop": 0.0,
            "decay_time": 1.8,
            "filter_cutoff": 1500,
            "distortion": 0.14,
            "attack": 0.006,
            "sustain": 0.87,
            "release": 0.35,
            "eq_low": 3,
            "eq_mid": 2,
        },
    },
    {
        "id": "FY3_BAS_078",
        "name": "Drip Too Hard 808",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Modern drip era trap — crisp 808 with millennial sheen",
        "instrument_breakdown": "808 sub with tight controlled decay, clean and modern",
        "note": 41,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.0,
            "decay_time": 1.8,
            "filter_cutoff": 400,
            "distortion": 0.02,
            "attack": 0.002,
            "sustain": 0.65,
            "release": 0.25,
            "eq_low": 3,
            "eq_mid": -1,
        },
    },
    {
        "id": "FY3_BAS_079",
        "name": "Stir Fry Dist Bass",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Migos 'Stir Fry' (2018) — Pharrell-influenced distorted 808",
        "instrument_breakdown": "808 distorted with funk-influenced character, unique saturation",
        "note": 40,
        "duration": 8.0,
        "params": {
            "bass_type": "808_dist",
            "pitch_drop": 1.5,
            "decay_time": 1.5,
            "filter_cutoff": 2500,
            "distortion": 0.45,
            "attack": 0.002,
            "sustain": 0.55,
            "release": 0.2,
            "eq_low": 1,
            "eq_mid": 3,
        },
    },
    {
        "id": "FY3_BAS_080",
        "name": "Narcos Deep Sub",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Migos 'Narcos' — cinematic deep sub bass for dramatic beats",
        "instrument_breakdown": "Deep sub with dramatic character, very low filter, cinematic weight",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "deep_sub",
            "pitch_drop": 0.5,
            "decay_time": 3.0,
            "filter_cutoff": 240,
            "distortion": 0.0,
            "attack": 0.012,
            "sustain": 0.93,
            "release": 0.6,
            "eq_low": 5,
            "eq_mid": -3,
        },
    },
    {
        "id": "FY3_BAS_081",
        "name": "Walk It Talk It Sub",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Migos 'Walk It Talk It' (2018) — bouncy 808 for the drake feature",
        "instrument_breakdown": "808 sub with tight decay, bouncy character for melodic flows",
        "note": 40,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.0,
            "decay_time": 1.4,
            "filter_cutoff": 420,
            "distortion": 0.03,
            "attack": 0.002,
            "sustain": 0.6,
            "release": 0.2,
            "eq_low": 2,
            "eq_mid": 0,
        },
    },
    {
        "id": "FY3_BAS_082",
        "name": "Savage Mode Sub",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "21 Savage dark mode — ominous 808 sub for menacing records",
        "instrument_breakdown": "808 sub with dark character, slow attack, evil low end",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 1.5,
            "decay_time": 2.8,
            "filter_cutoff": 350,
            "distortion": 0.01,
            "attack": 0.004,
            "sustain": 0.72,
            "release": 0.4,
            "eq_low": 4,
            "eq_mid": -3,
        },
    },
    {
        "id": "FY3_BAS_083",
        "name": "Modern Synth Bass Fat",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Modern Zaytoven — fat synth bass with modern processing",
        "instrument_breakdown": "Synth bass with heavy filtering, warm saturation, fat character",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "synth_bass",
            "pitch_drop": 0.0,
            "decay_time": 1.5,
            "filter_cutoff": 800,
            "distortion": 0.25,
            "attack": 0.003,
            "sustain": 0.65,
            "release": 0.3,
            "eq_low": 3,
            "eq_mid": 1,
        },
    },
    {
        "id": "FY3_BAS_084",
        "name": "MotorSport Heavy Dist",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Migos 'MotorSport' (2017) — revving engine distorted 808",
        "instrument_breakdown": "808 distorted with maximum harmonics, aggressive drive, crushed",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_dist",
            "pitch_drop": 3.0,
            "decay_time": 2.0,
            "filter_cutoff": 2200,
            "distortion": 0.75,
            "attack": 0.002,
            "sustain": 0.58,
            "release": 0.25,
            "eq_low": 1,
            "eq_mid": 3,
        },
    },
    {
        "id": "FY3_BAS_085",
        "name": "East Atlanta Day Sub",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Gucci Mane modern Atlanta anthems — polished 808 sub",
        "instrument_breakdown": "808 sub with polished mix, controlled parameters, modern Atlanta",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.0,
            "decay_time": 2.0,
            "filter_cutoff": 400,
            "distortion": 0.02,
            "attack": 0.002,
            "sustain": 0.68,
            "release": 0.3,
            "eq_low": 3,
            "eq_mid": -1,
        },
    },
    {
        "id": "FY3_BAS_086",
        "name": "Black Wrist 808",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Gucci Mane 'Black Wrist' — heavy 808 with jewelry-rattling low end",
        "instrument_breakdown": "808 sub with maximum low end, heavy pitch drop, impactful",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 3.5,
            "decay_time": 2.5,
            "filter_cutoff": 360,
            "distortion": 0.03,
            "attack": 0.002,
            "sustain": 0.7,
            "release": 0.35,
            "eq_low": 5,
            "eq_mid": -2,
        },
    },
    {
        "id": "FY3_BAS_087",
        "name": "Taco Tuesday Pluck",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Modern party trap — fun pluck bass for uptempo club records",
        "instrument_breakdown": "Pluck bass with snappy character, bright transient, modern processing",
        "note": 41,
        "duration": 8.0,
        "params": {
            "bass_type": "pluck_bass",
            "pitch_drop": 0.5,
            "decay_time": 0.6,
            "filter_cutoff": 1800,
            "distortion": 0.08,
            "attack": 0.001,
            "sustain": 0.2,
            "release": 0.1,
            "eq_low": 2,
            "eq_mid": 2,
        },
    },
    {
        "id": "FY3_BAS_088",
        "name": "Notice Me Organ Low",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Migos modern R&B-trap — smooth organ bass for melodic records",
        "instrument_breakdown": "Organ bass with smooth character, refined overdrive, modern warmth",
        "note": 40,
        "duration": 8.0,
        "params": {
            "bass_type": "organ_bass",
            "pitch_drop": 0.0,
            "decay_time": 1.6,
            "filter_cutoff": 1400,
            "distortion": 0.12,
            "attack": 0.008,
            "sustain": 0.88,
            "release": 0.4,
            "eq_low": 2,
            "eq_mid": 2,
        },
    },
    {
        "id": "FY3_BAS_089",
        "name": "Straightenin 808",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Migos 'Straightenin' (2021) — comeback 808 with precision",
        "instrument_breakdown": "808 sub with precise parameters, clean and hard-hitting",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.5,
            "decay_time": 2.0,
            "filter_cutoff": 400,
            "distortion": 0.03,
            "attack": 0.002,
            "sustain": 0.65,
            "release": 0.25,
            "eq_low": 3,
            "eq_mid": -1,
        },
    },
    {
        "id": "FY3_BAS_090",
        "name": "Avalanche Dist Heavy",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Migos 'Culture III' — overwhelming distorted 808 wall",
        "instrument_breakdown": "808 distorted with massive drive, sustained distortion, wall of bass",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_dist",
            "pitch_drop": 2.5,
            "decay_time": 2.5,
            "filter_cutoff": 1800,
            "distortion": 0.7,
            "attack": 0.002,
            "sustain": 0.65,
            "release": 0.3,
            "eq_low": 2,
            "eq_mid": 2,
        },
    },
    {
        "id": "FY3_BAS_091",
        "name": "Pac Man Bounce Sub",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Gucci Mane modern bounce — playful bouncy 808 for radio hits",
        "instrument_breakdown": "808 sub with tight bouncy character, fast decay for patterns",
        "note": 41,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.0,
            "decay_time": 1.2,
            "filter_cutoff": 420,
            "distortion": 0.02,
            "attack": 0.002,
            "sustain": 0.55,
            "release": 0.15,
            "eq_low": 2,
            "eq_mid": 0,
        },
    },
    {
        "id": "FY3_BAS_092",
        "name": "Type Shit Deep",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Modern type beat culture — versatile deep sub for producers",
        "instrument_breakdown": "Deep sub with all-purpose character, flexible parameters",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "deep_sub",
            "pitch_drop": 1.0,
            "decay_time": 2.2,
            "filter_cutoff": 300,
            "distortion": 0.0,
            "attack": 0.01,
            "sustain": 0.9,
            "release": 0.45,
            "eq_low": 3,
            "eq_mid": -2,
        },
    },
    {
        "id": "FY3_BAS_093",
        "name": "AI Youngboy Dist",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "NBA Youngboy x Zaytoven collabs — raw distorted 808 with energy",
        "instrument_breakdown": "808 distorted with raw character, aggressive saturation, energetic",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "808_dist",
            "pitch_drop": 2.0,
            "decay_time": 1.8,
            "filter_cutoff": 2000,
            "distortion": 0.6,
            "attack": 0.002,
            "sustain": 0.58,
            "release": 0.22,
            "eq_low": 2,
            "eq_mid": 2,
        },
    },
    {
        "id": "FY3_BAS_094",
        "name": "Long Live Takeoff Sub",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Tribute to Takeoff — soulful 808 sub with depth and emotion",
        "instrument_breakdown": "808 sub with extra-long sustain, soulful character, deep resonance",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.0,
            "decay_time": 3.5,
            "filter_cutoff": 380,
            "distortion": 0.01,
            "attack": 0.003,
            "sustain": 0.75,
            "release": 0.5,
            "eq_low": 4,
            "eq_mid": -2,
        },
    },
    {
        "id": "FY3_BAS_095",
        "name": "TikTok Trap Pluck",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Modern viral trap — snappy pluck bass for short-form content",
        "instrument_breakdown": "Pluck bass with ultra-fast attack, bright character, viral energy",
        "note": 40,
        "duration": 8.0,
        "params": {
            "bass_type": "pluck_bass",
            "pitch_drop": 0.0,
            "decay_time": 0.5,
            "filter_cutoff": 2000,
            "distortion": 0.1,
            "attack": 0.001,
            "sustain": 0.15,
            "release": 0.08,
            "eq_low": 1,
            "eq_mid": 3,
        },
    },
    {
        "id": "FY3_BAS_096",
        "name": "Modern Gospel Organ Bass",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Zaytoven's evolved church roots — modern gospel organ bass with polish",
        "instrument_breakdown": "Organ bass with maximum sub-octave, clean overdrive, gospel warmth",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "organ_bass",
            "pitch_drop": 0.0,
            "decay_time": 2.0,
            "filter_cutoff": 1300,
            "distortion": 0.18,
            "attack": 0.006,
            "sustain": 0.86,
            "release": 0.4,
            "eq_low": 4,
            "eq_mid": 1,
        },
    },
    {
        "id": "FY3_BAS_097",
        "name": "Metro Collab Dist",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Zaytoven x Metro Boomin crossover — aggressive modern dist 808",
        "instrument_breakdown": "808 distorted with modern aggressive drive, clear and punchy",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "808_dist",
            "pitch_drop": 2.5,
            "decay_time": 2.0,
            "filter_cutoff": 2200,
            "distortion": 0.65,
            "attack": 0.002,
            "sustain": 0.6,
            "release": 0.25,
            "eq_low": 2,
            "eq_mid": 2,
        },
    },
    {
        "id": "FY3_BAS_098",
        "name": "Gucci Classic Remastered",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Gucci Mane remastered classics — the original 808 updated for modern DAWs",
        "instrument_breakdown": "808 sub with classic parameters, modern mastering-ready",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.0,
            "decay_time": 2.5,
            "filter_cutoff": 400,
            "distortion": 0.02,
            "attack": 0.003,
            "sustain": 0.7,
            "release": 0.3,
            "eq_low": 3,
            "eq_mid": -1,
        },
    },
    {
        "id": "FY3_BAS_099",
        "name": "FY3 Signature Sub",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "FY3 house sound — our signature sub bass tuned for maximum impact",
        "instrument_breakdown": "808 sub with FY3-optimized parameters, perfect balance of weight and clarity",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.5,
            "decay_time": 2.5,
            "filter_cutoff": 420,
            "distortion": 0.03,
            "attack": 0.002,
            "sustain": 0.7,
            "release": 0.3,
            "eq_low": 4,
            "eq_mid": -2,
        },
    },
    {
        "id": "FY3_BAS_100",
        "name": "FY3 Ultimate 808",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "FY3 Collection finale — the ultimate 808 combining all eras into one",
        "instrument_breakdown": "808 distorted with balanced drive, all-era character, versatile and powerful",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_dist",
            "pitch_drop": 2.5,
            "decay_time": 2.2,
            "filter_cutoff": 1800,
            "distortion": 0.5,
            "attack": 0.002,
            "sustain": 0.65,
            "release": 0.28,
            "eq_low": 3,
            "eq_mid": 1,
        },
    },
    # ══════════════════════════════════════════════════════════════════════
    # UNDERREPRESENTED ARTIST EXPANSION — Presets 101-128
    # ══════════════════════════════════════════════════════════════════════
    {
        "id": "FY3_BAS_101",
        "name": "Usher R&B Sub",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Usher - Raymond vs. Raymond (2010) — smooth deep sub for R&B grooves",
        "instrument_breakdown": "Clean deep sub with extended sustain, warm low-end, minimal distortion",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "deep_sub",
            "pitch_drop": 1.0,
            "decay_time": 2.8,
            "filter_cutoff": 350,
            "distortion": 0.0,
            "attack": 0.01,
            "sustain": 0.9,
            "release": 0.5,
            "eq_low": 3,
            "eq_mid": -1,
        },
    },
    {
        "id": "FY3_BAS_102",
        "name": "Usher Synth Bass Smooth",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Usher - Climax (2012) — smooth synth bass for atmospheric R&B",
        "instrument_breakdown": "Warm synth bass with gentle filter sweep and extended sustain",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "synth_bass",
            "pitch_drop": 0.5,
            "decay_time": 2.5,
            "filter_cutoff": 800,
            "distortion": 0.05,
            "attack": 0.015,
            "sustain": 0.85,
            "release": 0.4,
            "eq_low": 2,
            "eq_mid": 1,
        },
    },
    {
        "id": "FY3_BAS_103",
        "name": "Usher Organ Bass Warm",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Usher - Papers (2010) — warm organ bass for soulful R&B",
        "instrument_breakdown": "Warm organ bass with church character, gentle sustain, clean tone",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "organ_bass",
            "pitch_drop": 0.0,
            "decay_time": 2.2,
            "filter_cutoff": 1000,
            "distortion": 0.08,
            "attack": 0.01,
            "sustain": 0.88,
            "release": 0.4,
            "eq_low": 2,
            "eq_mid": 2,
        },
    },
    {
        "id": "FY3_BAS_104",
        "name": "Waka Distorted 808",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Waka Flocka Flame - Hard in da Paint (2010) — distorted 808 for hard trap",
        "instrument_breakdown": "Heavy distorted 808 with aggressive harmonics and fast attack",
        "note": 34,
        "duration": 7.0,
        "params": {
            "bass_type": "808_dist",
            "pitch_drop": 3.0,
            "decay_time": 2.0,
            "filter_cutoff": 2000,
            "distortion": 0.6,
            "attack": 0.002,
            "sustain": 0.6,
            "release": 0.2,
            "eq_low": 4,
            "eq_mid": 2,
        },
    },
    {
        "id": "FY3_BAS_105",
        "name": "Waka Flockaveli Sub",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Waka Flocka Flame - Flockaveli (2010) — heavy sub for aggressive trap",
        "instrument_breakdown": "Deep 808 sub with heavy pitch drop and extended decay",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 4.0,
            "decay_time": 2.8,
            "filter_cutoff": 300,
            "distortion": 0.0,
            "attack": 0.002,
            "sustain": 0.7,
            "release": 0.3,
            "eq_low": 5,
            "eq_mid": -2,
        },
    },
    {
        "id": "FY3_BAS_106",
        "name": "Waka No Hands Pluck",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Waka Flocka Flame - No Hands (2010) — plucky bass for club bangers",
        "instrument_breakdown": "Punchy pluck bass with fast attack and club-ready bounce",
        "note": 38,
        "duration": 7.0,
        "params": {
            "bass_type": "pluck_bass",
            "pitch_drop": 1.0,
            "decay_time": 1.2,
            "filter_cutoff": 1500,
            "distortion": 0.1,
            "attack": 0.003,
            "sustain": 0.5,
            "release": 0.2,
            "eq_low": 2,
            "eq_mid": 2,
        },
    },
    {
        "id": "FY3_BAS_107",
        "name": "Quavo Melodic 808",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Quavo - Quavo Huncho (2018) — melodic 808 for auto-tune hooks",
        "instrument_breakdown": "Clean melodic 808 sub with moderate pitch drop and bright resonance",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.0,
            "decay_time": 2.5,
            "filter_cutoff": 450,
            "distortion": 0.0,
            "attack": 0.003,
            "sustain": 0.75,
            "release": 0.35,
            "eq_low": 3,
            "eq_mid": 0,
        },
    },
    {
        "id": "FY3_BAS_108",
        "name": "Quavo Synth Bass Bright",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Quavo - Rocket Power (2024) — bright synth bass for modern melodic trap",
        "instrument_breakdown": "Bright synth bass with crystalline harmonics and clean sustain",
        "note": 38,
        "duration": 8.0,
        "params": {
            "bass_type": "synth_bass",
            "pitch_drop": 1.0,
            "decay_time": 2.2,
            "filter_cutoff": 1200,
            "distortion": 0.08,
            "attack": 0.005,
            "sustain": 0.8,
            "release": 0.35,
            "eq_low": 2,
            "eq_mid": 1,
        },
    },
    {
        "id": "FY3_BAS_109",
        "name": "Quavo Deep Sub Clean",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Quavo - Workin Me (2018) — clean deep sub for catchy hooks",
        "instrument_breakdown": "Ultra-clean deep sub with minimal harmonics and smooth envelope",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "deep_sub",
            "pitch_drop": 1.5,
            "decay_time": 2.5,
            "filter_cutoff": 280,
            "distortion": 0.0,
            "attack": 0.008,
            "sustain": 0.88,
            "release": 0.45,
            "eq_low": 3,
            "eq_mid": -1,
        },
    },
    {
        "id": "FY3_BAS_110",
        "name": "Offset Punchy 808",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Offset - Father of 4 (2019) — punchy 808 for hard modern trap",
        "instrument_breakdown": "Punchy distorted 808 with aggressive attack and heavy sustain",
        "note": 34,
        "duration": 7.0,
        "params": {
            "bass_type": "808_dist",
            "pitch_drop": 2.5,
            "decay_time": 2.2,
            "filter_cutoff": 1600,
            "distortion": 0.45,
            "attack": 0.002,
            "sustain": 0.65,
            "release": 0.25,
            "eq_low": 4,
            "eq_mid": 1,
        },
    },
    {
        "id": "FY3_BAS_111",
        "name": "Offset Dark Sub",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Offset - Ric Flair Drip (2017) — dark sub for luxury street trap",
        "instrument_breakdown": "Dark 808 sub with heavy pitch drop and ominous sustain",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 3.0,
            "decay_time": 2.8,
            "filter_cutoff": 320,
            "distortion": 0.0,
            "attack": 0.002,
            "sustain": 0.7,
            "release": 0.3,
            "eq_low": 4,
            "eq_mid": -2,
        },
    },
    {
        "id": "FY3_BAS_112",
        "name": "Offset Clout Synth Bass",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Offset - Clout (2019) — aggressive synth bass for hard flex records",
        "instrument_breakdown": "Aggressive synth bass with driven harmonics and punchy attack",
        "note": 38,
        "duration": 7.0,
        "params": {
            "bass_type": "synth_bass",
            "pitch_drop": 1.5,
            "decay_time": 1.8,
            "filter_cutoff": 1400,
            "distortion": 0.25,
            "attack": 0.003,
            "sustain": 0.65,
            "release": 0.25,
            "eq_low": 3,
            "eq_mid": 2,
        },
    },
    {
        "id": "FY3_BAS_113",
        "name": "Takeoff Quick 808",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Takeoff - The Last Rocket (2018) — fast 808 patterns for technical trap",
        "instrument_breakdown": "Quick-decay 808 for rapid bass patterns and technical production",
        "note": 36,
        "duration": 6.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.0,
            "decay_time": 1.5,
            "filter_cutoff": 400,
            "distortion": 0.0,
            "attack": 0.002,
            "sustain": 0.6,
            "release": 0.2,
            "eq_low": 3,
            "eq_mid": 0,
        },
    },
    {
        "id": "FY3_BAS_114",
        "name": "Takeoff Precise Pluck",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Takeoff - Last Memory (2018) — precise pluck bass for technical patterns",
        "instrument_breakdown": "Precise pluck bass with clean attack and defined note separation",
        "note": 38,
        "duration": 6.0,
        "params": {
            "bass_type": "pluck_bass",
            "pitch_drop": 1.0,
            "decay_time": 1.0,
            "filter_cutoff": 1800,
            "distortion": 0.05,
            "attack": 0.003,
            "sustain": 0.45,
            "release": 0.15,
            "eq_low": 2,
            "eq_mid": 1,
        },
    },
    {
        "id": "FY3_BAS_115",
        "name": "Takeoff Tight Dist 808",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Takeoff - Infatuation (2018) — tight distorted 808 for fast flows",
        "instrument_breakdown": "Tight distorted 808 with controlled harmonics and fast decay",
        "note": 34,
        "duration": 6.0,
        "params": {
            "bass_type": "808_dist",
            "pitch_drop": 2.0,
            "decay_time": 1.5,
            "filter_cutoff": 1500,
            "distortion": 0.35,
            "attack": 0.002,
            "sustain": 0.55,
            "release": 0.18,
            "eq_low": 3,
            "eq_mid": 1,
        },
    },
    {
        "id": "FY3_BAS_116",
        "name": "YB Heavy Emotional 808",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "NBA YoungBoy - AI YoungBoy 2 (2019) — heavy emotional 808 for pain music",
        "instrument_breakdown": "Heavy 808 sub with deep pitch drop and emotional sustain",
        "note": 34,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 4.0,
            "decay_time": 3.0,
            "filter_cutoff": 300,
            "distortion": 0.0,
            "attack": 0.002,
            "sustain": 0.72,
            "release": 0.35,
            "eq_low": 5,
            "eq_mid": -2,
        },
    },
    {
        "id": "FY3_BAS_117",
        "name": "YB Aggressive Dist 808",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "NBA YoungBoy - Sincerely Kentrell (2021) — aggressive distorted 808",
        "instrument_breakdown": "Aggressive distorted 808 with heavy harmonics for emotional bangers",
        "note": 36,
        "duration": 7.0,
        "params": {
            "bass_type": "808_dist",
            "pitch_drop": 3.0,
            "decay_time": 2.5,
            "filter_cutoff": 1800,
            "distortion": 0.55,
            "attack": 0.002,
            "sustain": 0.62,
            "release": 0.25,
            "eq_low": 4,
            "eq_mid": 2,
        },
    },
    {
        "id": "FY3_BAS_118",
        "name": "YB Deep Emotional Sub",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "NBA YoungBoy - Colors (2020) — deep emotional sub for moody tracks",
        "instrument_breakdown": "Deep sub with extended sustain and sorrowful pitch movement",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "deep_sub",
            "pitch_drop": 2.0,
            "decay_time": 2.8,
            "filter_cutoff": 280,
            "distortion": 0.0,
            "attack": 0.008,
            "sustain": 0.85,
            "release": 0.5,
            "eq_low": 4,
            "eq_mid": -1,
        },
    },
    {
        "id": "FY3_BAS_119",
        "name": "OJ Classic 808",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "OJ Da Juiceman - The Otha Side of the Trap (2009) — classic clean 808",
        "instrument_breakdown": "Classic clean 808 sub from vintage Zaytoven-OJ sessions",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.0,
            "decay_time": 2.5,
            "filter_cutoff": 380,
            "distortion": 0.0,
            "attack": 0.003,
            "sustain": 0.7,
            "release": 0.3,
            "eq_low": 3,
            "eq_mid": -1,
        },
    },
    {
        "id": "FY3_BAS_120",
        "name": "OJ Organ Bass Classic",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "OJ Da Juiceman - Make tha Trap Say Aye (2008) — vintage organ bass",
        "instrument_breakdown": "Classic organ bass with vintage warmth and church character",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "organ_bass",
            "pitch_drop": 0.0,
            "decay_time": 2.0,
            "filter_cutoff": 1100,
            "distortion": 0.12,
            "attack": 0.008,
            "sustain": 0.82,
            "release": 0.4,
            "eq_low": 3,
            "eq_mid": 1,
        },
    },
    {
        "id": "FY3_BAS_121",
        "name": "Dolph Memphis 808 Heavy",
        "category": "Bass",
        "era": "Peak (2010-2016)",
        "inspiration": "Young Dolph - King of Memphis (2016) — heavy Memphis 808",
        "instrument_breakdown": "Heavy 808 with Memphis grit and extended low-end sustain",
        "note": 34,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 3.5,
            "decay_time": 3.0,
            "filter_cutoff": 320,
            "distortion": 0.0,
            "attack": 0.002,
            "sustain": 0.7,
            "release": 0.3,
            "eq_low": 5,
            "eq_mid": -2,
        },
    },
    {
        "id": "FY3_BAS_122",
        "name": "Dolph 100 Shots Dist",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Young Dolph - 100 Shots (2017) — aggressive distorted Memphis 808",
        "instrument_breakdown": "Gritty distorted 808 with Memphis aggression and punchy attack",
        "note": 36,
        "duration": 7.0,
        "params": {
            "bass_type": "808_dist",
            "pitch_drop": 2.5,
            "decay_time": 2.2,
            "filter_cutoff": 1600,
            "distortion": 0.5,
            "attack": 0.002,
            "sustain": 0.62,
            "release": 0.22,
            "eq_low": 4,
            "eq_mid": 2,
        },
    },
    {
        "id": "FY3_BAS_123",
        "name": "GloRilla Punchy 808",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "GloRilla - Tomorrow 2 (2022) — punchy 808 for crunk-trap",
        "instrument_breakdown": "Punchy modern 808 with tight attack and energetic bounce",
        "note": 36,
        "duration": 7.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 2.0,
            "decay_time": 2.0,
            "filter_cutoff": 420,
            "distortion": 0.0,
            "attack": 0.002,
            "sustain": 0.65,
            "release": 0.25,
            "eq_low": 3,
            "eq_mid": 0,
        },
    },
    {
        "id": "FY3_BAS_124",
        "name": "GloRilla Party Dist",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "GloRilla - FNF (2022) — distorted party 808 for female trap",
        "instrument_breakdown": "Bright distorted 808 with party energy and club-ready punch",
        "note": 36,
        "duration": 7.0,
        "params": {
            "bass_type": "808_dist",
            "pitch_drop": 2.0,
            "decay_time": 1.8,
            "filter_cutoff": 1500,
            "distortion": 0.35,
            "attack": 0.002,
            "sustain": 0.6,
            "release": 0.22,
            "eq_low": 3,
            "eq_mid": 2,
        },
    },
    {
        "id": "FY3_BAS_125",
        "name": "Jeezy Snowman 808",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Young Jeezy - Soul Survivor (2005) — booming anthemic 808",
        "instrument_breakdown": "Massive booming 808 with extended decay for trunk-shaking anthems",
        "note": 34,
        "duration": 8.0,
        "params": {
            "bass_type": "808_sub",
            "pitch_drop": 3.5,
            "decay_time": 3.2,
            "filter_cutoff": 330,
            "distortion": 0.0,
            "attack": 0.002,
            "sustain": 0.68,
            "release": 0.4,
            "eq_low": 5,
            "eq_mid": -3,
        },
    },
    {
        "id": "FY3_BAS_126",
        "name": "Jeezy Organ Bass Soulful",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "Young Jeezy - Go Crazy (2005) — soulful organ bass for anthems",
        "instrument_breakdown": "Soulful organ bass with gospel warmth and anthemic sustain",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "organ_bass",
            "pitch_drop": 0.0,
            "decay_time": 2.2,
            "filter_cutoff": 1200,
            "distortion": 0.12,
            "attack": 0.008,
            "sustain": 0.85,
            "release": 0.45,
            "eq_low": 3,
            "eq_mid": 1,
        },
    },
    {
        "id": "FY3_BAS_127",
        "name": "Dolph Pluck Bass Memphis",
        "category": "Bass",
        "era": "Modern (2016+)",
        "inspiration": "Young Dolph - Rich Slave (2020) — Memphis pluck bass",
        "instrument_breakdown": "Gritty Memphis pluck bass with street character and defined attack",
        "note": 38,
        "duration": 7.0,
        "params": {
            "bass_type": "pluck_bass",
            "pitch_drop": 1.0,
            "decay_time": 1.2,
            "filter_cutoff": 1400,
            "distortion": 0.15,
            "attack": 0.003,
            "sustain": 0.5,
            "release": 0.2,
            "eq_low": 2,
            "eq_mid": 2,
        },
    },
    {
        "id": "FY3_BAS_128",
        "name": "OJ Deep Sub Vintage",
        "category": "Bass",
        "era": "Early (2005-2010)",
        "inspiration": "OJ Da Juiceman - I'm Gettin Money (2008) — vintage deep sub",
        "instrument_breakdown": "Vintage deep sub with classic character and smooth envelope",
        "note": 36,
        "duration": 8.0,
        "params": {
            "bass_type": "deep_sub",
            "pitch_drop": 1.5,
            "decay_time": 2.2,
            "filter_cutoff": 300,
            "distortion": 0.0,
            "attack": 0.01,
            "sustain": 0.85,
            "release": 0.45,
            "eq_low": 3,
            "eq_mid": -1,
        },
    },
]
