"""FY3 Zaytoven Collection — FX & Texture Presets (30)."""

FX_PRESETS = [
    # =========================================================================
    # RISERS (FY3_SFX_001 – FY3_SFX_010)
    # =========================================================================
    {
        "id": "FY3_SFX_001",
        "name": "Trap Riser",
        "category": "FX",
        "era": "All Eras",
        "inspiration": "Zaytoven Production Style",
        "instrument_breakdown": (
            "White noise riser with 4-second sweep from 200Hz to 12kHz, building "
            "tension. Classic trap buildup effect for beat transitions."
        ),
        "note": 60,
        "duration": 7.0,
        "params": {
            "fx_type": "riser",
            "brightness": 0.7,
            "sweep_time": 4.0,
            "sweep_range": [200, 12000],
            "noise_color": "white",
            "layer_count": 3,
            "decay_time": 0.5,
            "attack_time": 0.1,
            "reverb_wet": 0.45,
            "reverb_size": 0.6,
            "delay_mix": 0.2,
            "delay_ms": 250,
            "distortion": 0.1,
            "eq_low": -3,
            "eq_mid": 0,
            "eq_high": 4,
            "stereo_width": 0.8,
        },
    },
    {
        "id": "FY3_SFX_002",
        "name": "Zone 6 Siren Rise",
        "category": "FX",
        "era": "2010s",
        "inspiration": "Zaytoven x Gucci Mane Transitions",
        "instrument_breakdown": (
            "Pink noise siren sweep with a tight 2-second rise from 400Hz to 8kHz. "
            "Quick tension builder with slight distortion grit, ideal for 8-bar buildups."
        ),
        "note": 60,
        "duration": 2.0,
        "params": {
            "fx_type": "riser",
            "brightness": 0.55,
            "sweep_time": 2.0,
            "sweep_range": [400, 8000],
            "noise_color": "pink",
            "layer_count": 2,
            "decay_time": 0.3,
            "attack_time": 0.05,
            "reverb_wet": 0.3,
            "reverb_size": 0.4,
            "delay_mix": 0.15,
            "delay_ms": 180,
            "distortion": 0.25,
            "eq_low": -2,
            "eq_mid": 2,
            "eq_high": 3,
            "stereo_width": 0.65,
        },
    },
    {
        "id": "FY3_SFX_003",
        "name": "Dark Cathedral Rise",
        "category": "FX",
        "era": "All Eras",
        "inspiration": "Zaytoven Production Style",
        "instrument_breakdown": (
            "Brown noise riser with a long 6-second sweep from 80Hz to 6kHz, heavy "
            "reverb tail creating a cavernous buildup. Deep sub-rumble foundation "
            "for dramatic drops."
        ),
        "note": 60,
        "duration": 6.0,
        "params": {
            "fx_type": "riser",
            "brightness": 0.3,
            "sweep_time": 6.0,
            "sweep_range": [80, 6000],
            "noise_color": "brown",
            "layer_count": 4,
            "decay_time": 1.0,
            "attack_time": 0.3,
            "reverb_wet": 0.7,
            "reverb_size": 0.9,
            "delay_mix": 0.1,
            "delay_ms": 400,
            "distortion": 0.05,
            "eq_low": 3,
            "eq_mid": -2,
            "eq_high": -1,
            "stereo_width": 0.95,
        },
    },
    {
        "id": "FY3_SFX_004",
        "name": "Brick Squad Riser",
        "category": "FX",
        "era": "2010s",
        "inspiration": "Zaytoven x Waka Flocka Era",
        "instrument_breakdown": (
            "Aggressive white noise riser with distortion-driven edge, sweeping "
            "from 300Hz to 15kHz over 3 seconds. High-energy buildup with layered "
            "harmonics for hard-hitting trap drops."
        ),
        "note": 60,
        "duration": 6.0,
        "params": {
            "fx_type": "riser",
            "brightness": 0.85,
            "sweep_time": 3.0,
            "sweep_range": [300, 15000],
            "noise_color": "white",
            "layer_count": 5,
            "decay_time": 0.4,
            "attack_time": 0.05,
            "reverb_wet": 0.25,
            "reverb_size": 0.35,
            "delay_mix": 0.3,
            "delay_ms": 150,
            "distortion": 0.45,
            "eq_low": -4,
            "eq_mid": 3,
            "eq_high": 5,
            "stereo_width": 0.7,
        },
    },
    {
        "id": "FY3_SFX_005",
        "name": "Velvet Sweep",
        "category": "FX",
        "era": "All Eras",
        "inspiration": "Zaytoven Production Style",
        "instrument_breakdown": (
            "Smooth pink noise riser with gentle 5-second ascent from 150Hz to "
            "10kHz. Warm, silky character with minimal distortion, perfect for "
            "melodic sections and R&B-influenced trap transitions."
        ),
        "note": 60,
        "duration": 8.0,
        "params": {
            "fx_type": "riser",
            "brightness": 0.5,
            "sweep_time": 5.0,
            "sweep_range": [150, 10000],
            "noise_color": "pink",
            "layer_count": 3,
            "decay_time": 0.8,
            "attack_time": 0.2,
            "reverb_wet": 0.55,
            "reverb_size": 0.7,
            "delay_mix": 0.25,
            "delay_ms": 330,
            "distortion": 0.0,
            "eq_low": 1,
            "eq_mid": 2,
            "eq_high": 1,
            "stereo_width": 0.9,
        },
    },
    {
        "id": "FY3_SFX_006",
        "name": "808 Sub Riser",
        "category": "FX",
        "era": "2020s",
        "inspiration": "Zaytoven Production Style",
        "instrument_breakdown": (
            "Ultra-low brown noise riser focusing on sub frequencies, sweeping from "
            "40Hz to 3kHz over 4 seconds. Felt more than heard in the low end, "
            "creating physical tension before 808 drops."
        ),
        "note": 60,
        "duration": 7.0,
        "params": {
            "fx_type": "riser",
            "brightness": 0.2,
            "sweep_time": 4.0,
            "sweep_range": [40, 3000],
            "noise_color": "brown",
            "layer_count": 2,
            "decay_time": 0.6,
            "attack_time": 0.15,
            "reverb_wet": 0.35,
            "reverb_size": 0.5,
            "delay_mix": 0.05,
            "delay_ms": 200,
            "distortion": 0.15,
            "eq_low": 6,
            "eq_mid": -4,
            "eq_high": -6,
            "stereo_width": 0.4,
        },
    },
    {
        "id": "FY3_SFX_007",
        "name": "Glass Shimmer Rise",
        "category": "FX",
        "era": "All Eras",
        "inspiration": "Zaytoven Production Style",
        "instrument_breakdown": (
            "Crystalline white noise riser focused in the upper register, sweeping "
            "from 2kHz to 18kHz over 3 seconds. Bright, airy shimmer with wide "
            "stereo spread for ethereal buildups."
        ),
        "note": 60,
        "duration": 6.0,
        "params": {
            "fx_type": "riser",
            "brightness": 0.95,
            "sweep_time": 3.0,
            "sweep_range": [2000, 18000],
            "noise_color": "white",
            "layer_count": 4,
            "decay_time": 0.7,
            "attack_time": 0.1,
            "reverb_wet": 0.65,
            "reverb_size": 0.8,
            "delay_mix": 0.35,
            "delay_ms": 280,
            "distortion": 0.0,
            "eq_low": -6,
            "eq_mid": -1,
            "eq_high": 6,
            "stereo_width": 1.0,
        },
    },
    {
        "id": "FY3_SFX_008",
        "name": "Gutter Grind Rise",
        "category": "FX",
        "era": "2000s",
        "inspiration": "Zaytoven x Jeezy Era",
        "instrument_breakdown": (
            "Dirty pink noise riser with heavy distortion and mid-range focus, "
            "sweeping from 250Hz to 7kHz over 2.5 seconds. Raw, gritty character "
            "like a vintage tape machine being pushed to the limit."
        ),
        "note": 60,
        "duration": 2.5,
        "params": {
            "fx_type": "riser",
            "brightness": 0.4,
            "sweep_time": 2.5,
            "sweep_range": [250, 7000],
            "noise_color": "pink",
            "layer_count": 3,
            "decay_time": 0.35,
            "attack_time": 0.08,
            "reverb_wet": 0.2,
            "reverb_size": 0.3,
            "delay_mix": 0.1,
            "delay_ms": 160,
            "distortion": 0.6,
            "eq_low": -1,
            "eq_mid": 5,
            "eq_high": -2,
            "stereo_width": 0.55,
        },
    },
    {
        "id": "FY3_SFX_009",
        "name": "Phantom Ascend",
        "category": "FX",
        "era": "All Eras",
        "inspiration": "Zaytoven Production Style",
        "instrument_breakdown": (
            "Ethereal brown noise riser with massive reverb wash, sweeping from "
            "100Hz to 9kHz over 5.5 seconds. Ghost-like atmosphere with long decay "
            "tails blending into the reverb for cinematic tension."
        ),
        "note": 60,
        "duration": 5.5,
        "params": {
            "fx_type": "riser",
            "brightness": 0.35,
            "sweep_time": 5.5,
            "sweep_range": [100, 9000],
            "noise_color": "brown",
            "layer_count": 4,
            "decay_time": 1.2,
            "attack_time": 0.4,
            "reverb_wet": 0.8,
            "reverb_size": 0.95,
            "delay_mix": 0.2,
            "delay_ms": 500,
            "distortion": 0.0,
            "eq_low": 2,
            "eq_mid": 0,
            "eq_high": -3,
            "stereo_width": 1.0,
        },
    },
    {
        "id": "FY3_SFX_010",
        "name": "Icy Blade Rise",
        "category": "FX",
        "era": "2020s",
        "inspiration": "Zaytoven Production Style",
        "instrument_breakdown": (
            "Sharp white noise riser with a rapid 2-second sweep from 500Hz to "
            "16kHz, layered with 5 elements for dense stacking. Cutting, metallic "
            "edge with tight stereo imaging for modern trap energy."
        ),
        "note": 60,
        "duration": 2.0,
        "params": {
            "fx_type": "riser",
            "brightness": 0.9,
            "sweep_time": 2.0,
            "sweep_range": [500, 16000],
            "noise_color": "white",
            "layer_count": 5,
            "decay_time": 0.25,
            "attack_time": 0.02,
            "reverb_wet": 0.15,
            "reverb_size": 0.25,
            "delay_mix": 0.4,
            "delay_ms": 120,
            "distortion": 0.35,
            "eq_low": -5,
            "eq_mid": 1,
            "eq_high": 6,
            "stereo_width": 0.6,
        },
    },
    # =========================================================================
    # IMPACTS (FY3_SFX_011 – FY3_SFX_020)
    # =========================================================================
    {
        "id": "FY3_SFX_011",
        "name": "Trap Door Slam",
        "category": "FX",
        "era": "All Eras",
        "inspiration": "Zaytoven Production Style",
        "instrument_breakdown": (
            "Massive low-end impact hit with 4 layered transient elements. Deep "
            "sub boom with fast attack and 1.5-second decay, designed to punctuate "
            "beat drops and section changes."
        ),
        "note": 60,
        "duration": 1.5,
        "params": {
            "fx_type": "impact",
            "brightness": 0.3,
            "sweep_time": 0.0,
            "sweep_range": [40, 800],
            "noise_color": "brown",
            "layer_count": 4,
            "decay_time": 1.5,
            "attack_time": 0.005,
            "reverb_wet": 0.4,
            "reverb_size": 0.5,
            "delay_mix": 0.1,
            "delay_ms": 200,
            "distortion": 0.2,
            "eq_low": 5,
            "eq_mid": -2,
            "eq_high": -4,
            "stereo_width": 0.5,
        },
    },
    {
        "id": "FY3_SFX_012",
        "name": "Gucci Clap Hit",
        "category": "FX",
        "era": "2010s",
        "inspiration": "Zaytoven x Gucci Mane Era",
        "instrument_breakdown": (
            "Snappy mid-range impact with layered clap-like transients and a short "
            "0.8-second decay. Bright attack with white noise burst, perfect for "
            "accenting snare patterns and transition markers."
        ),
        "note": 60,
        "duration": 1.0,
        "params": {
            "fx_type": "impact",
            "brightness": 0.75,
            "sweep_time": 0.0,
            "sweep_range": [500, 6000],
            "noise_color": "white",
            "layer_count": 3,
            "decay_time": 0.8,
            "attack_time": 0.002,
            "reverb_wet": 0.3,
            "reverb_size": 0.35,
            "delay_mix": 0.15,
            "delay_ms": 130,
            "distortion": 0.15,
            "eq_low": -3,
            "eq_mid": 4,
            "eq_high": 2,
            "stereo_width": 0.7,
        },
    },
    {
        "id": "FY3_SFX_013",
        "name": "Cannon Boom",
        "category": "FX",
        "era": "All Eras",
        "inspiration": "Zaytoven Production Style",
        "instrument_breakdown": (
            "Cinematic cannon-fire impact with 5 layered elements for maximum "
            "density. Extended 2.5-second decay with heavy reverb tail, creating "
            "an explosion-like effect for dramatic beat intros."
        ),
        "note": 60,
        "duration": 2.5,
        "params": {
            "fx_type": "impact",
            "brightness": 0.4,
            "sweep_time": 0.0,
            "sweep_range": [30, 2000],
            "noise_color": "brown",
            "layer_count": 5,
            "decay_time": 2.5,
            "attack_time": 0.003,
            "reverb_wet": 0.6,
            "reverb_size": 0.85,
            "delay_mix": 0.2,
            "delay_ms": 350,
            "distortion": 0.3,
            "eq_low": 6,
            "eq_mid": 0,
            "eq_high": -3,
            "stereo_width": 0.85,
        },
    },
    {
        "id": "FY3_SFX_014",
        "name": "Knife Edge Snap",
        "category": "FX",
        "era": "2020s",
        "inspiration": "Zaytoven Production Style",
        "instrument_breakdown": (
            "Ultra-tight transient snap with razor-sharp attack and minimal 0.5-"
            "second decay. Dry, cutting impact with high-frequency emphasis for "
            "modern hi-hat accent patterns and percussive stabs."
        ),
        "note": 60,
        "duration": 1.0,
        "params": {
            "fx_type": "impact",
            "brightness": 0.9,
            "sweep_time": 0.0,
            "sweep_range": [1000, 14000],
            "noise_color": "white",
            "layer_count": 2,
            "decay_time": 0.5,
            "attack_time": 0.001,
            "reverb_wet": 0.1,
            "reverb_size": 0.15,
            "delay_mix": 0.05,
            "delay_ms": 80,
            "distortion": 0.1,
            "eq_low": -6,
            "eq_mid": 0,
            "eq_high": 6,
            "stereo_width": 0.45,
        },
    },
    {
        "id": "FY3_SFX_015",
        "name": "Street Thunder",
        "category": "FX",
        "era": "2000s",
        "inspiration": "Zaytoven x Jeezy Era",
        "instrument_breakdown": (
            "Rolling thunder impact with distorted brown noise burst and 3-second "
            "decay. Multiple transient layers create a cascading rumble effect, "
            "like distant thunder over Zone 6 streets."
        ),
        "note": 60,
        "duration": 6.0,
        "params": {
            "fx_type": "impact",
            "brightness": 0.25,
            "sweep_time": 0.0,
            "sweep_range": [50, 1500],
            "noise_color": "brown",
            "layer_count": 4,
            "decay_time": 3.0,
            "attack_time": 0.01,
            "reverb_wet": 0.55,
            "reverb_size": 0.75,
            "delay_mix": 0.25,
            "delay_ms": 300,
            "distortion": 0.4,
            "eq_low": 4,
            "eq_mid": 1,
            "eq_high": -5,
            "stereo_width": 0.9,
        },
    },
    {
        "id": "FY3_SFX_016",
        "name": "Glass Shatter Hit",
        "category": "FX",
        "era": "All Eras",
        "inspiration": "Zaytoven Production Style",
        "instrument_breakdown": (
            "High-frequency impact simulating shattering glass with white noise "
            "burst and bright EQ profile. 1.2-second decay with wide stereo spread, "
            "adding dramatic flair to beat drops and transitions."
        ),
        "note": 60,
        "duration": 1.5,
        "params": {
            "fx_type": "impact",
            "brightness": 0.95,
            "sweep_time": 0.0,
            "sweep_range": [2000, 18000],
            "noise_color": "white",
            "layer_count": 5,
            "decay_time": 1.2,
            "attack_time": 0.001,
            "reverb_wet": 0.45,
            "reverb_size": 0.55,
            "delay_mix": 0.3,
            "delay_ms": 100,
            "distortion": 0.05,
            "eq_low": -6,
            "eq_mid": 2,
            "eq_high": 5,
            "stereo_width": 1.0,
        },
    },
    {
        "id": "FY3_SFX_017",
        "name": "Muted Thud",
        "category": "FX",
        "era": "All Eras",
        "inspiration": "Zaytoven Production Style",
        "instrument_breakdown": (
            "Soft, padded impact with pink noise character and warm mid-range focus. "
            "Gentle 1-second decay with low brightness, useful as a subtle section "
            "marker that sits behind the mix without dominating."
        ),
        "note": 60,
        "duration": 1.0,
        "params": {
            "fx_type": "impact",
            "brightness": 0.2,
            "sweep_time": 0.0,
            "sweep_range": [100, 2000],
            "noise_color": "pink",
            "layer_count": 2,
            "decay_time": 1.0,
            "attack_time": 0.01,
            "reverb_wet": 0.5,
            "reverb_size": 0.45,
            "delay_mix": 0.0,
            "delay_ms": 0,
            "distortion": 0.0,
            "eq_low": 2,
            "eq_mid": 3,
            "eq_high": -4,
            "stereo_width": 0.35,
        },
    },
    {
        "id": "FY3_SFX_018",
        "name": "Pistol Crack",
        "category": "FX",
        "era": "2010s",
        "inspiration": "Zaytoven Production Style",
        "instrument_breakdown": (
            "Sharp, percussive gunshot-style impact with white noise transient and "
            "very fast 0.6-second decay. Dry and punchy with aggressive distortion, "
            "used for hard accents and ad-lib punctuation effects."
        ),
        "note": 60,
        "duration": 1.0,
        "params": {
            "fx_type": "impact",
            "brightness": 0.8,
            "sweep_time": 0.0,
            "sweep_range": [800, 12000],
            "noise_color": "white",
            "layer_count": 3,
            "decay_time": 0.6,
            "attack_time": 0.001,
            "reverb_wet": 0.15,
            "reverb_size": 0.2,
            "delay_mix": 0.1,
            "delay_ms": 90,
            "distortion": 0.55,
            "eq_low": -4,
            "eq_mid": 2,
            "eq_high": 4,
            "stereo_width": 0.5,
        },
    },
    {
        "id": "FY3_SFX_019",
        "name": "Earthquake Drop",
        "category": "FX",
        "era": "All Eras",
        "inspiration": "Zaytoven Production Style",
        "instrument_breakdown": (
            "Massive sub-frequency impact with maximum low-end boost and 2-second "
            "rumbling decay. Brown noise foundation with heavy distortion creates "
            "a seismic effect that shakes the speakers on the drop."
        ),
        "note": 60,
        "duration": 2.0,
        "params": {
            "fx_type": "impact",
            "brightness": 0.15,
            "sweep_time": 0.0,
            "sweep_range": [20, 500],
            "noise_color": "brown",
            "layer_count": 4,
            "decay_time": 2.0,
            "attack_time": 0.005,
            "reverb_wet": 0.35,
            "reverb_size": 0.6,
            "delay_mix": 0.05,
            "delay_ms": 250,
            "distortion": 0.5,
            "eq_low": 6,
            "eq_mid": -3,
            "eq_high": -6,
            "stereo_width": 0.3,
        },
    },
    {
        "id": "FY3_SFX_020",
        "name": "Reverse Cymbal Splash",
        "category": "FX",
        "era": "All Eras",
        "inspiration": "Zaytoven Production Style",
        "instrument_breakdown": (
            "Reverse cymbal-style impact with pink noise character and a slow "
            "0.05-second attack building into a bright transient peak. Wide stereo "
            "image with shimmering delay, bridging sections with metallic energy."
        ),
        "note": 60,
        "duration": 1.5,
        "params": {
            "fx_type": "impact",
            "brightness": 0.7,
            "sweep_time": 0.0,
            "sweep_range": [600, 16000],
            "noise_color": "pink",
            "layer_count": 3,
            "decay_time": 1.0,
            "attack_time": 0.05,
            "reverb_wet": 0.5,
            "reverb_size": 0.65,
            "delay_mix": 0.35,
            "delay_ms": 220,
            "distortion": 0.05,
            "eq_low": -3,
            "eq_mid": 1,
            "eq_high": 5,
            "stereo_width": 0.95,
        },
    },
    # =========================================================================
    # TEXTURES (FY3_SFX_021 – FY3_SFX_030)
    # =========================================================================
    {
        "id": "FY3_SFX_021",
        "name": "Vinyl Crackle Bed",
        "category": "FX",
        "era": "All Eras",
        "inspiration": "Zaytoven Production Style",
        "instrument_breakdown": (
            "Warm vinyl crackle texture using pink noise with low brightness and "
            "mid-range focus. Continuous 8-second ambient bed that adds analog "
            "warmth and nostalgic lo-fi character to any beat."
        ),
        "note": 60,
        "duration": 8.0,
        "params": {
            "fx_type": "texture",
            "brightness": 0.3,
            "sweep_time": 0.0,
            "sweep_range": [200, 4000],
            "noise_color": "pink",
            "layer_count": 2,
            "decay_time": 0.0,
            "attack_time": 1.5,
            "reverb_wet": 0.25,
            "reverb_size": 0.3,
            "delay_mix": 0.1,
            "delay_ms": 300,
            "distortion": 0.15,
            "eq_low": 1,
            "eq_mid": 3,
            "eq_high": -3,
            "stereo_width": 0.6,
        },
    },
    {
        "id": "FY3_SFX_022",
        "name": "Midnight Fog",
        "category": "FX",
        "era": "All Eras",
        "inspiration": "Zaytoven Production Style",
        "instrument_breakdown": (
            "Dark ambient drone texture built from brown noise with heavy reverb "
            "wash and wide stereo field. 10-second evolving bed with slow attack, "
            "creating a haunting atmospheric backdrop for dark trap beats."
        ),
        "note": 60,
        "duration": 10.0,
        "params": {
            "fx_type": "texture",
            "brightness": 0.15,
            "sweep_time": 0.0,
            "sweep_range": [40, 2000],
            "noise_color": "brown",
            "layer_count": 3,
            "decay_time": 0.0,
            "attack_time": 3.0,
            "reverb_wet": 0.8,
            "reverb_size": 0.95,
            "delay_mix": 0.15,
            "delay_ms": 500,
            "distortion": 0.0,
            "eq_low": 4,
            "eq_mid": -2,
            "eq_high": -5,
            "stereo_width": 1.0,
        },
    },
    {
        "id": "FY3_SFX_023",
        "name": "Trap House Hiss",
        "category": "FX",
        "era": "2010s",
        "inspiration": "Zaytoven x Migos Era",
        "instrument_breakdown": (
            "Constant white noise hiss texture at low volume with bright EQ "
            "character. 7-second ambient layer that simulates tape machine hiss, "
            "filling the high-frequency space and adding gritty realism."
        ),
        "note": 60,
        "duration": 7.0,
        "params": {
            "fx_type": "texture",
            "brightness": 0.65,
            "sweep_time": 0.0,
            "sweep_range": [3000, 16000],
            "noise_color": "white",
            "layer_count": 1,
            "decay_time": 0.0,
            "attack_time": 0.5,
            "reverb_wet": 0.15,
            "reverb_size": 0.2,
            "delay_mix": 0.0,
            "delay_ms": 0,
            "distortion": 0.2,
            "eq_low": -6,
            "eq_mid": -2,
            "eq_high": 4,
            "stereo_width": 0.75,
        },
    },
    {
        "id": "FY3_SFX_024",
        "name": "Cathedral Air",
        "category": "FX",
        "era": "All Eras",
        "inspiration": "Zaytoven Production Style",
        "instrument_breakdown": (
            "Spacious ambient texture with pink noise fed through maximum reverb "
            "and long delay trails. 9-second evolving pad-like bed that creates "
            "the sense of a vast empty space, ideal under sparse piano melodies."
        ),
        "note": 60,
        "duration": 9.0,
        "params": {
            "fx_type": "texture",
            "brightness": 0.4,
            "sweep_time": 0.0,
            "sweep_range": [100, 8000],
            "noise_color": "pink",
            "layer_count": 4,
            "decay_time": 0.0,
            "attack_time": 2.5,
            "reverb_wet": 0.9,
            "reverb_size": 1.0,
            "delay_mix": 0.3,
            "delay_ms": 450,
            "distortion": 0.0,
            "eq_low": 0,
            "eq_mid": 1,
            "eq_high": -1,
            "stereo_width": 1.0,
        },
    },
    {
        "id": "FY3_SFX_025",
        "name": "Dirty South Rumble",
        "category": "FX",
        "era": "2000s",
        "inspiration": "Zaytoven x Jeezy Era",
        "instrument_breakdown": (
            "Low-frequency rumble texture using brown noise with distortion and "
            "sub-heavy EQ. 8-second continuous drone that adds menacing undertone "
            "energy, sitting beneath the 808 to thicken the low end."
        ),
        "note": 60,
        "duration": 8.0,
        "params": {
            "fx_type": "texture",
            "brightness": 0.1,
            "sweep_time": 0.0,
            "sweep_range": [20, 500],
            "noise_color": "brown",
            "layer_count": 2,
            "decay_time": 0.0,
            "attack_time": 2.0,
            "reverb_wet": 0.3,
            "reverb_size": 0.4,
            "delay_mix": 0.05,
            "delay_ms": 200,
            "distortion": 0.4,
            "eq_low": 6,
            "eq_mid": -4,
            "eq_high": -6,
            "stereo_width": 0.3,
        },
    },
    {
        "id": "FY3_SFX_026",
        "name": "Ice Crystal Shimmer",
        "category": "FX",
        "era": "2020s",
        "inspiration": "Zaytoven Production Style",
        "instrument_breakdown": (
            "Bright, sparkling texture using white noise filtered to upper "
            "harmonics with rhythmic delay creating a shimmering pulse. 7-second "
            "ambient layer that adds frozen, crystalline atmosphere to melodic trap."
        ),
        "note": 60,
        "duration": 7.0,
        "params": {
            "fx_type": "texture",
            "brightness": 0.85,
            "sweep_time": 0.0,
            "sweep_range": [4000, 18000],
            "noise_color": "white",
            "layer_count": 3,
            "decay_time": 0.0,
            "attack_time": 1.0,
            "reverb_wet": 0.6,
            "reverb_size": 0.7,
            "delay_mix": 0.4,
            "delay_ms": 375,
            "distortion": 0.0,
            "eq_low": -5,
            "eq_mid": 0,
            "eq_high": 6,
            "stereo_width": 0.95,
        },
    },
    {
        "id": "FY3_SFX_027",
        "name": "Smoke Room Haze",
        "category": "FX",
        "era": "All Eras",
        "inspiration": "Zaytoven Production Style",
        "instrument_breakdown": (
            "Warm, thick ambient texture using pink noise with moderate distortion "
            "and mid-forward EQ. 10-second slowly evolving bed that creates a "
            "smoky, hazy vibe like recording in a dim studio at 3 AM."
        ),
        "note": 60,
        "duration": 10.0,
        "params": {
            "fx_type": "texture",
            "brightness": 0.35,
            "sweep_time": 0.0,
            "sweep_range": [150, 5000],
            "noise_color": "pink",
            "layer_count": 3,
            "decay_time": 0.0,
            "attack_time": 3.5,
            "reverb_wet": 0.5,
            "reverb_size": 0.6,
            "delay_mix": 0.2,
            "delay_ms": 280,
            "distortion": 0.25,
            "eq_low": 2,
            "eq_mid": 4,
            "eq_high": -2,
            "stereo_width": 0.7,
        },
    },
    {
        "id": "FY3_SFX_028",
        "name": "Digital Rain",
        "category": "FX",
        "era": "2020s",
        "inspiration": "Zaytoven Production Style",
        "instrument_breakdown": (
            "Glitchy digital texture using white noise with rapid delay feedback "
            "and moderate distortion. 6-second ambient layer with tight stereo "
            "imaging, evoking the sound of digital artifacts and data streams."
        ),
        "note": 60,
        "duration": 6.0,
        "params": {
            "fx_type": "texture",
            "brightness": 0.6,
            "sweep_time": 0.0,
            "sweep_range": [500, 12000],
            "noise_color": "white",
            "layer_count": 4,
            "decay_time": 0.0,
            "attack_time": 0.8,
            "reverb_wet": 0.35,
            "reverb_size": 0.4,
            "delay_mix": 0.55,
            "delay_ms": 60,
            "distortion": 0.3,
            "eq_low": -3,
            "eq_mid": 2,
            "eq_high": 3,
            "stereo_width": 0.5,
        },
    },
    {
        "id": "FY3_SFX_029",
        "name": "Ocean Floor Drone",
        "category": "FX",
        "era": "All Eras",
        "inspiration": "Zaytoven Production Style",
        "instrument_breakdown": (
            "Deep, submerged ambient texture using brown noise with massive reverb "
            "and minimal brightness. 10-second drone that creates an underwater "
            "pressure effect, perfect for dark intros and cinematic beat openings."
        ),
        "note": 60,
        "duration": 10.0,
        "params": {
            "fx_type": "texture",
            "brightness": 0.1,
            "sweep_time": 0.0,
            "sweep_range": [30, 1000],
            "noise_color": "brown",
            "layer_count": 3,
            "decay_time": 0.0,
            "attack_time": 4.0,
            "reverb_wet": 0.75,
            "reverb_size": 0.9,
            "delay_mix": 0.1,
            "delay_ms": 600,
            "distortion": 0.05,
            "eq_low": 5,
            "eq_mid": -3,
            "eq_high": -6,
            "stereo_width": 0.85,
        },
    },
    {
        "id": "FY3_SFX_030",
        "name": "Phantom Whisper Bed",
        "category": "FX",
        "era": "All Eras",
        "inspiration": "Zaytoven Production Style",
        "instrument_breakdown": (
            "Ghostly, breathy ambient texture using pink noise with high reverb "
            "and gentle delay wash. 9-second ethereal bed with wide stereo spread, "
            "creating the illusion of distant whispered voices in a dark space."
        ),
        "note": 60,
        "duration": 9.0,
        "params": {
            "fx_type": "texture",
            "brightness": 0.45,
            "sweep_time": 0.0,
            "sweep_range": [200, 7000],
            "noise_color": "pink",
            "layer_count": 4,
            "decay_time": 0.0,
            "attack_time": 2.0,
            "reverb_wet": 0.7,
            "reverb_size": 0.85,
            "delay_mix": 0.25,
            "delay_ms": 400,
            "distortion": 0.0,
            "eq_low": -1,
            "eq_mid": 2,
            "eq_high": 1,
            "stereo_width": 1.0,
        },
    },
    # =========================================================================
    # UNDERREPRESENTED ARTISTS — Presets 031-052
    # =========================================================================
    {
        "id": "FY3_SFX_031",
        "name": "Usher Climax Riser",
        "category": "FX",
        "era": "Peak (2010-2016)",
        "inspiration": "Usher 'Climax' (2012)",
        "instrument_breakdown": (
            "Smooth pink noise riser with 5-second sweep from 300Hz to 10kHz. "
            "Silky R&B buildup with wide stereo, long reverb tail, no distortion. "
            "Designed for sensual beat transitions and chorus buildups."
        ),
        "note": 64,
        "duration": 7.0,
        "params": {
            "fx_type": "riser",
            "brightness": 0.55,
            "sweep_time": 5.0,
            "sweep_range": [300, 10000],
            "noise_color": "pink",
            "layer_count": 3,
            "decay_time": 0.8,
            "attack_time": 0.2,
            "reverb_wet": 0.6,
            "reverb_size": 0.8,
            "delay_mix": 0.2,
            "delay_ms": 350,
            "distortion": 0.0,
            "eq_low": 0,
            "eq_mid": 1,
            "eq_high": 2,
            "stereo_width": 0.85,
        },
    },
    {
        "id": "FY3_SFX_032",
        "name": "Usher R&B Shimmer Texture",
        "category": "FX",
        "era": "Peak (2010-2016)",
        "inspiration": "Usher 'Scream' (2012)",
        "instrument_breakdown": (
            "Sparkling pink noise texture bed with high shimmer. 5-layer ambient "
            "wash, gentle attack, wide stereo spread. Creates the glassy R&B "
            "atmosphere behind polished vocal production."
        ),
        "note": 67,
        "duration": 8.0,
        "params": {
            "fx_type": "texture",
            "brightness": 0.65,
            "sweep_time": 0.0,
            "sweep_range": [400, 9000],
            "noise_color": "pink",
            "layer_count": 5,
            "decay_time": 0.0,
            "attack_time": 1.5,
            "reverb_wet": 0.7,
            "reverb_size": 0.85,
            "delay_mix": 0.15,
            "delay_ms": 400,
            "distortion": 0.0,
            "eq_low": -2,
            "eq_mid": 1,
            "eq_high": 3,
            "stereo_width": 0.9,
        },
    },
    {
        "id": "FY3_SFX_033",
        "name": "Flocka Brick Squad Impact",
        "category": "FX",
        "era": "Early (2005-2010)",
        "inspiration": "Waka Flocka 'Hard In Da Paint' (2010)",
        "instrument_breakdown": (
            "Crushing white noise impact hit with heavy distortion. Short attack, "
            "fast decay, 2-layer punch. Aggressive stab for drop accents and "
            "transition markers in hard trap production."
        ),
        "note": 48,
        "duration": 6.0,
        "params": {
            "fx_type": "impact",
            "brightness": 0.8,
            "sweep_time": 0.0,
            "sweep_range": [100, 5000],
            "noise_color": "white",
            "layer_count": 2,
            "decay_time": 0.4,
            "attack_time": 0.01,
            "reverb_wet": 0.2,
            "reverb_size": 0.3,
            "delay_mix": 0.05,
            "delay_ms": 100,
            "distortion": 0.4,
            "eq_low": 4,
            "eq_mid": 2,
            "eq_high": -1,
            "stereo_width": 0.4,
        },
    },
    {
        "id": "FY3_SFX_034",
        "name": "Flocka No Hands Riser",
        "category": "FX",
        "era": "Early (2005-2010)",
        "inspiration": "Waka Flocka 'No Hands' (2010)",
        "instrument_breakdown": (
            "Aggressive white noise riser with 3-second sweep from 200Hz to 8kHz. "
            "Raw, distorted edge with tight stereo. Builds explosive energy for "
            "chorus drops in hard-hitting trap beats."
        ),
        "note": 52,
        "duration": 6.0,
        "params": {
            "fx_type": "riser",
            "brightness": 0.75,
            "sweep_time": 3.0,
            "sweep_range": [200, 8000],
            "noise_color": "white",
            "layer_count": 2,
            "decay_time": 0.3,
            "attack_time": 0.05,
            "reverb_wet": 0.2,
            "reverb_size": 0.35,
            "delay_mix": 0.1,
            "delay_ms": 150,
            "distortion": 0.3,
            "eq_low": 2,
            "eq_mid": 3,
            "eq_high": 1,
            "stereo_width": 0.5,
        },
    },
    {
        "id": "FY3_SFX_035",
        "name": "Quavo Culture Riser",
        "category": "FX",
        "era": "Modern (2016+)",
        "inspiration": "Migos 'Bad and Boujee' (2016)",
        "instrument_breakdown": (
            "Bright pink noise riser with 4-second sweep from 300Hz to 14kHz. "
            "Clean, sparkling climb with wide stereo spread and shimmer. "
            "Polished modern trap transition effect."
        ),
        "note": 66,
        "duration": 7.0,
        "params": {
            "fx_type": "riser",
            "brightness": 0.7,
            "sweep_time": 4.0,
            "sweep_range": [300, 14000],
            "noise_color": "pink",
            "layer_count": 3,
            "decay_time": 0.5,
            "attack_time": 0.1,
            "reverb_wet": 0.45,
            "reverb_size": 0.65,
            "delay_mix": 0.2,
            "delay_ms": 250,
            "distortion": 0.0,
            "eq_low": -2,
            "eq_mid": 0,
            "eq_high": 4,
            "stereo_width": 0.8,
        },
    },
    {
        "id": "FY3_SFX_036",
        "name": "Quavo Narcos Texture",
        "category": "FX",
        "era": "Modern (2016+)",
        "inspiration": "Migos 'Narcos' (2018)",
        "instrument_breakdown": (
            "Dark atmospheric texture bed with brown noise base. 4-layer ambient "
            "wash, slow attack, deep reverb. Creates the ominous cinematic backdrop "
            "behind melodic trap production."
        ),
        "note": 55,
        "duration": 8.0,
        "params": {
            "fx_type": "texture",
            "brightness": 0.4,
            "sweep_time": 0.0,
            "sweep_range": [150, 6000],
            "noise_color": "brown",
            "layer_count": 4,
            "decay_time": 0.0,
            "attack_time": 2.0,
            "reverb_wet": 0.65,
            "reverb_size": 0.85,
            "delay_mix": 0.1,
            "delay_ms": 450,
            "distortion": 0.0,
            "eq_low": 2,
            "eq_mid": 0,
            "eq_high": -1,
            "stereo_width": 0.75,
        },
    },
    {
        "id": "FY3_SFX_037",
        "name": "Offset Set It Off Impact",
        "category": "FX",
        "era": "Modern (2016+)",
        "inspiration": "Offset 'Clout' (2019)",
        "instrument_breakdown": (
            "Heavy impact hit with dark character. White noise burst, tight decay, "
            "moderate distortion, low-end weight. Punchy accent for drop markers "
            "in aggressive modern trap beats."
        ),
        "note": 50,
        "duration": 6.0,
        "params": {
            "fx_type": "impact",
            "brightness": 0.5,
            "sweep_time": 0.0,
            "sweep_range": [80, 4000],
            "noise_color": "white",
            "layer_count": 2,
            "decay_time": 0.5,
            "attack_time": 0.01,
            "reverb_wet": 0.3,
            "reverb_size": 0.45,
            "delay_mix": 0.08,
            "delay_ms": 125,
            "distortion": 0.2,
            "eq_low": 3,
            "eq_mid": 1,
            "eq_high": -2,
            "stereo_width": 0.5,
        },
    },
    {
        "id": "FY3_SFX_038",
        "name": "Offset Dark Riser",
        "category": "FX",
        "era": "Modern (2016+)",
        "inspiration": "Offset 'Ric Flair Drip' (2017)",
        "instrument_breakdown": (
            "Brown noise riser with 3.5-second sweep from 150Hz to 7kHz. Dark "
            "character with moderate distortion, building menacing tension for "
            "verse-to-chorus transitions."
        ),
        "note": 53,
        "duration": 6.5,
        "params": {
            "fx_type": "riser",
            "brightness": 0.45,
            "sweep_time": 3.5,
            "sweep_range": [150, 7000],
            "noise_color": "brown",
            "layer_count": 2,
            "decay_time": 0.4,
            "attack_time": 0.08,
            "reverb_wet": 0.35,
            "reverb_size": 0.5,
            "delay_mix": 0.1,
            "delay_ms": 200,
            "distortion": 0.15,
            "eq_low": 2,
            "eq_mid": 1,
            "eq_high": -1,
            "stereo_width": 0.55,
        },
    },
    {
        "id": "FY3_SFX_039",
        "name": "Takeoff Martian Riser",
        "category": "FX",
        "era": "Modern (2016+)",
        "inspiration": "Takeoff 'Last Memory' (2018)",
        "instrument_breakdown": (
            "Fast white noise riser with 2.5-second sweep from 250Hz to 12kHz. "
            "Clean, precise climb with tight stereo. Technical buildup effect "
            "matching fast-paced triplet flow energy."
        ),
        "note": 62,
        "duration": 6.0,
        "params": {
            "fx_type": "riser",
            "brightness": 0.65,
            "sweep_time": 2.5,
            "sweep_range": [250, 12000],
            "noise_color": "white",
            "layer_count": 3,
            "decay_time": 0.3,
            "attack_time": 0.05,
            "reverb_wet": 0.35,
            "reverb_size": 0.5,
            "delay_mix": 0.15,
            "delay_ms": 175,
            "distortion": 0.0,
            "eq_low": -1,
            "eq_mid": 1,
            "eq_high": 3,
            "stereo_width": 0.65,
        },
    },
    {
        "id": "FY3_SFX_040",
        "name": "Takeoff Casper Impact",
        "category": "FX",
        "era": "Modern (2016+)",
        "inspiration": "Takeoff 'Casper' (2018)",
        "instrument_breakdown": (
            "Sharp impact hit with bright edge. Pink noise burst, instant attack, "
            "quick decay, clean tone. Precise accent marker for beat transitions "
            "and rhythmic punctuation."
        ),
        "note": 65,
        "duration": 6.0,
        "params": {
            "fx_type": "impact",
            "brightness": 0.7,
            "sweep_time": 0.0,
            "sweep_range": [200, 8000],
            "noise_color": "pink",
            "layer_count": 2,
            "decay_time": 0.3,
            "attack_time": 0.01,
            "reverb_wet": 0.25,
            "reverb_size": 0.4,
            "delay_mix": 0.1,
            "delay_ms": 150,
            "distortion": 0.05,
            "eq_low": 0,
            "eq_mid": 2,
            "eq_high": 2,
            "stereo_width": 0.55,
        },
    },
    {
        "id": "FY3_SFX_041",
        "name": "Youngboy Rage Riser",
        "category": "FX",
        "era": "Modern (2016+)",
        "inspiration": "NBA Youngboy 'No Smoke' (2017)",
        "instrument_breakdown": (
            "Aggressive white noise riser with 3-second sweep from 200Hz to 10kHz. "
            "Heavy distortion, raw energy, tight stereo. Builds explosive tension "
            "before emotional verses drop."
        ),
        "note": 54,
        "duration": 6.5,
        "params": {
            "fx_type": "riser",
            "brightness": 0.7,
            "sweep_time": 3.0,
            "sweep_range": [200, 10000],
            "noise_color": "white",
            "layer_count": 2,
            "decay_time": 0.3,
            "attack_time": 0.05,
            "reverb_wet": 0.25,
            "reverb_size": 0.35,
            "delay_mix": 0.08,
            "delay_ms": 125,
            "distortion": 0.35,
            "eq_low": 2,
            "eq_mid": 3,
            "eq_high": 0,
            "stereo_width": 0.45,
        },
    },
    {
        "id": "FY3_SFX_042",
        "name": "Youngboy Dark Texture",
        "category": "FX",
        "era": "Modern (2016+)",
        "inspiration": "NBA Youngboy 'Lonely Child' (2019)",
        "instrument_breakdown": (
            "Haunting brown noise texture with slow attack. 4-layer ambient bed, "
            "deep reverb, melancholic darkness. Creates the emotional atmospheric "
            "backdrop behind vulnerable vocal delivery."
        ),
        "note": 51,
        "duration": 8.0,
        "params": {
            "fx_type": "texture",
            "brightness": 0.35,
            "sweep_time": 0.0,
            "sweep_range": [100, 5000],
            "noise_color": "brown",
            "layer_count": 4,
            "decay_time": 0.0,
            "attack_time": 2.5,
            "reverb_wet": 0.7,
            "reverb_size": 0.9,
            "delay_mix": 0.15,
            "delay_ms": 500,
            "distortion": 0.0,
            "eq_low": 2,
            "eq_mid": -1,
            "eq_high": -2,
            "stereo_width": 0.8,
        },
    },
    {
        "id": "FY3_SFX_043",
        "name": "Youngboy Emotional Impact",
        "category": "FX",
        "era": "Modern (2016+)",
        "inspiration": "NBA Youngboy 'Valuable Pain' (2018)",
        "instrument_breakdown": (
            "Deep impact hit with emotional weight. Brown noise burst, heavy low-end, "
            "moderate distortion, wide reverb tail. Punctuates transitions in "
            "pain-driven melodic trap production."
        ),
        "note": 49,
        "duration": 6.0,
        "params": {
            "fx_type": "impact",
            "brightness": 0.4,
            "sweep_time": 0.0,
            "sweep_range": [60, 3500],
            "noise_color": "brown",
            "layer_count": 3,
            "decay_time": 0.6,
            "attack_time": 0.01,
            "reverb_wet": 0.4,
            "reverb_size": 0.6,
            "delay_mix": 0.1,
            "delay_ms": 300,
            "distortion": 0.2,
            "eq_low": 4,
            "eq_mid": 0,
            "eq_high": -3,
            "stereo_width": 0.6,
        },
    },
    {
        "id": "FY3_SFX_044",
        "name": "OJ Juiceman Trap Riser",
        "category": "FX",
        "era": "Early (2005-2010)",
        "inspiration": "OJ Da Juiceman 'Make Da Trap Say Aye' (2009)",
        "instrument_breakdown": (
            "Classic white noise riser with 4-second sweep from 250Hz to 9kHz. "
            "Vintage analog warmth, moderate saturation, old-school trap buildup "
            "energy for Zone 6 production."
        ),
        "note": 58,
        "duration": 7.0,
        "params": {
            "fx_type": "riser",
            "brightness": 0.6,
            "sweep_time": 4.0,
            "sweep_range": [250, 9000],
            "noise_color": "white",
            "layer_count": 2,
            "decay_time": 0.5,
            "attack_time": 0.1,
            "reverb_wet": 0.35,
            "reverb_size": 0.5,
            "delay_mix": 0.15,
            "delay_ms": 200,
            "distortion": 0.15,
            "eq_low": 1,
            "eq_mid": 2,
            "eq_high": 1,
            "stereo_width": 0.6,
        },
    },
    {
        "id": "FY3_SFX_045",
        "name": "OJ Juice Impact",
        "category": "FX",
        "era": "Early (2005-2010)",
        "inspiration": "OJ Da Juiceman 'I'm Getting Money' (2008)",
        "instrument_breakdown": (
            "Punchy vintage impact hit with analog character. White noise burst, "
            "fast attack, moderate decay, warm saturation. Classic trap accent "
            "stab for early era production."
        ),
        "note": 56,
        "duration": 6.0,
        "params": {
            "fx_type": "impact",
            "brightness": 0.55,
            "sweep_time": 0.0,
            "sweep_range": [120, 5000],
            "noise_color": "white",
            "layer_count": 2,
            "decay_time": 0.4,
            "attack_time": 0.01,
            "reverb_wet": 0.25,
            "reverb_size": 0.35,
            "delay_mix": 0.1,
            "delay_ms": 150,
            "distortion": 0.18,
            "eq_low": 2,
            "eq_mid": 2,
            "eq_high": 0,
            "stereo_width": 0.5,
        },
    },
    {
        "id": "FY3_SFX_046",
        "name": "Dolph Memphis Riser",
        "category": "FX",
        "era": "Modern (2016+)",
        "inspiration": "Young Dolph 'Preach' (2016)",
        "instrument_breakdown": (
            "Dark brown noise riser with 3.5-second sweep from 150Hz to 7kHz. "
            "Memphis grit, heavy distortion, tight stereo. Builds raw threatening "
            "energy for street anthem transitions."
        ),
        "note": 50,
        "duration": 6.5,
        "params": {
            "fx_type": "riser",
            "brightness": 0.45,
            "sweep_time": 3.5,
            "sweep_range": [150, 7000],
            "noise_color": "brown",
            "layer_count": 2,
            "decay_time": 0.35,
            "attack_time": 0.05,
            "reverb_wet": 0.3,
            "reverb_size": 0.45,
            "delay_mix": 0.08,
            "delay_ms": 175,
            "distortion": 0.25,
            "eq_low": 3,
            "eq_mid": 1,
            "eq_high": -2,
            "stereo_width": 0.5,
        },
    },
    {
        "id": "FY3_SFX_047",
        "name": "Dolph 100 Shots Impact",
        "category": "FX",
        "era": "Modern (2016+)",
        "inspiration": "Young Dolph '100 Shots' (2017)",
        "instrument_breakdown": (
            "Massive low-end impact with Memphis weight. Brown noise hit, instant "
            "attack, heavy bass, gritty distortion. Defiant stab accent for "
            "hard Memphis trap drops."
        ),
        "note": 48,
        "duration": 6.0,
        "params": {
            "fx_type": "impact",
            "brightness": 0.4,
            "sweep_time": 0.0,
            "sweep_range": [60, 3000],
            "noise_color": "brown",
            "layer_count": 2,
            "decay_time": 0.5,
            "attack_time": 0.01,
            "reverb_wet": 0.25,
            "reverb_size": 0.4,
            "delay_mix": 0.05,
            "delay_ms": 100,
            "distortion": 0.3,
            "eq_low": 4,
            "eq_mid": 1,
            "eq_high": -3,
            "stereo_width": 0.45,
        },
    },
    {
        "id": "FY3_SFX_048",
        "name": "GloRilla Crunk Riser",
        "category": "FX",
        "era": "Modern (2016+)",
        "inspiration": "GloRilla 'F.N.F.' (2022)",
        "instrument_breakdown": (
            "Energetic pink noise riser with 3-second sweep from 300Hz to 13kHz. "
            "Bright, clean, punchy climb with wide stereo. High-energy buildup "
            "for crunk-revival beat transitions."
        ),
        "note": 68,
        "duration": 6.5,
        "params": {
            "fx_type": "riser",
            "brightness": 0.75,
            "sweep_time": 3.0,
            "sweep_range": [300, 13000],
            "noise_color": "pink",
            "layer_count": 3,
            "decay_time": 0.4,
            "attack_time": 0.05,
            "reverb_wet": 0.4,
            "reverb_size": 0.55,
            "delay_mix": 0.15,
            "delay_ms": 200,
            "distortion": 0.05,
            "eq_low": -1,
            "eq_mid": 1,
            "eq_high": 3,
            "stereo_width": 0.7,
        },
    },
    {
        "id": "FY3_SFX_049",
        "name": "GloRilla Party Impact",
        "category": "FX",
        "era": "Modern (2016+)",
        "inspiration": "GloRilla 'Tomorrow 2' (2022)",
        "instrument_breakdown": (
            "Bright impact hit with party energy. Pink noise burst, fast attack, "
            "tight decay, clean and punchy. Energetic accent for drops in "
            "modern female trap production."
        ),
        "note": 70,
        "duration": 6.0,
        "params": {
            "fx_type": "impact",
            "brightness": 0.7,
            "sweep_time": 0.0,
            "sweep_range": [200, 9000],
            "noise_color": "pink",
            "layer_count": 2,
            "decay_time": 0.3,
            "attack_time": 0.01,
            "reverb_wet": 0.3,
            "reverb_size": 0.45,
            "delay_mix": 0.12,
            "delay_ms": 150,
            "distortion": 0.05,
            "eq_low": 0,
            "eq_mid": 2,
            "eq_high": 2,
            "stereo_width": 0.6,
        },
    },
    {
        "id": "FY3_SFX_050",
        "name": "Jeezy Anthem Riser",
        "category": "FX",
        "era": "Early (2005-2010)",
        "inspiration": "Young Jeezy 'Soul Survivor' (2005)",
        "instrument_breakdown": (
            "Massive white noise riser with 5-second sweep from 200Hz to 11kHz. "
            "Anthemic buildup with wide stereo, deep reverb. Grand-scale tension "
            "builder for classic Atlanta trap chorus entries."
        ),
        "note": 57,
        "duration": 7.5,
        "params": {
            "fx_type": "riser",
            "brightness": 0.6,
            "sweep_time": 5.0,
            "sweep_range": [200, 11000],
            "noise_color": "white",
            "layer_count": 3,
            "decay_time": 0.6,
            "attack_time": 0.1,
            "reverb_wet": 0.5,
            "reverb_size": 0.7,
            "delay_mix": 0.15,
            "delay_ms": 300,
            "distortion": 0.05,
            "eq_low": 1,
            "eq_mid": 2,
            "eq_high": 2,
            "stereo_width": 0.75,
        },
    },
    {
        "id": "FY3_SFX_051",
        "name": "Jeezy Trap Star Texture",
        "category": "FX",
        "era": "Early (2005-2010)",
        "inspiration": "Young Jeezy 'Trap or Die' (2005)",
        "instrument_breakdown": (
            "Gritty ambient texture with street atmosphere. Brown noise bed, "
            "3-layer wash, warm analog character, moderate reverb. Creates the "
            "classic Atlanta trap environmental backdrop."
        ),
        "note": 53,
        "duration": 8.0,
        "params": {
            "fx_type": "texture",
            "brightness": 0.4,
            "sweep_time": 0.0,
            "sweep_range": [100, 5000],
            "noise_color": "brown",
            "layer_count": 3,
            "decay_time": 0.0,
            "attack_time": 2.0,
            "reverb_wet": 0.5,
            "reverb_size": 0.65,
            "delay_mix": 0.1,
            "delay_ms": 350,
            "distortion": 0.1,
            "eq_low": 2,
            "eq_mid": 1,
            "eq_high": -1,
            "stereo_width": 0.65,
        },
    },
    {
        "id": "FY3_SFX_052",
        "name": "Usher Confessions Impact",
        "category": "FX",
        "era": "Peak (2010-2016)",
        "inspiration": "Usher 'Yeah!' (2004)",
        "instrument_breakdown": (
            "Smooth impact hit with R&B polish. Pink noise burst, moderate decay, "
            "clean tone, wide reverb tail. Elegant accent for transitions in "
            "polished R&B-trap crossover production."
        ),
        "note": 63,
        "duration": 6.0,
        "params": {
            "fx_type": "impact",
            "brightness": 0.55,
            "sweep_time": 0.0,
            "sweep_range": [150, 7000],
            "noise_color": "pink",
            "layer_count": 3,
            "decay_time": 0.5,
            "attack_time": 0.01,
            "reverb_wet": 0.45,
            "reverb_size": 0.6,
            "delay_mix": 0.15,
            "delay_ms": 250,
            "distortion": 0.0,
            "eq_low": 0,
            "eq_mid": 1,
            "eq_high": 1,
            "stereo_width": 0.7,
        },
    },
]
