"""FY3 Zaytoven Collection — Keys Presets (50)."""

KEYS_PRESETS = [
    # =========================================================================
    #  EARLY ERA (2005-2010) — FY3_KEY_001 to FY3_KEY_017
    # =========================================================================
    {
        "id": "FY3_KEY_001",
        "name": "Zone 6 Clav",
        "category": "Keys",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane - Trap House (2005)",
        "instrument_breakdown": "Funky clavinet D6 with bright pulse tone, light tube saturation, percussive attack. Stevie Wonder-inspired clav sound Zaytoven uses for funky trap grooves.",
        "note": 60,
        "duration": 7.0,
        "params": {
            "key_type": "clavinet",
            "brightness": 0.72,
            "mod_index": 0.0,
            "decay_time": 0.45,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.25,
            "filter_cutoff": 4500.0,
            "reverb_wet": 0.12,
            "reverb_size": 0.30,
            "chorus_mix": 0.0,
            "delay_mix": 0.0,
            "delay_ms": 0,
            "eq_low": -2,
            "eq_mid": 3,
            "eq_high": 4,
            "stereo_width": 0.40,
        },
    },
    {
        "id": "FY3_KEY_002",
        "name": "Icy Vibes",
        "category": "Keys",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane - Icy (2005)",
        "instrument_breakdown": "Warm jazz vibraphone with slow motor vibrato and a gentle shimmer. Classic Zaytoven melodic touch layered over 808 sub bass in early Gucci records.",
        "note": 67,
        "duration": 7.0,
        "params": {
            "key_type": "vibraphone",
            "brightness": 0.55,
            "mod_index": 1.8,
            "decay_time": 1.2,
            "vibrato_rate": 3.5,
            "vibrato_depth": 0.30,
            "distortion": 0.0,
            "filter_cutoff": 6000.0,
            "reverb_wet": 0.35,
            "reverb_size": 0.50,
            "chorus_mix": 0.10,
            "delay_mix": 0.0,
            "delay_ms": 0,
            "eq_low": 0,
            "eq_mid": 2,
            "eq_high": 1,
            "stereo_width": 0.55,
        },
    },
    {
        "id": "FY3_KEY_003",
        "name": "Bricks Marimba",
        "category": "Keys",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane - Bricks (2006)",
        "instrument_breakdown": "Dry wooden marimba hit with tight decay and low-pass roll-off. Simple two-note accent pattern that cuts through distorted 808 kick patterns.",
        "note": 72,
        "duration": 6.0,
        "params": {
            "key_type": "marimba",
            "brightness": 0.40,
            "mod_index": 1.2,
            "decay_time": 0.35,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.0,
            "filter_cutoff": 3200.0,
            "reverb_wet": 0.08,
            "reverb_size": 0.20,
            "chorus_mix": 0.0,
            "delay_mix": 0.05,
            "delay_ms": 180,
            "eq_low": -1,
            "eq_mid": 1,
            "eq_high": -2,
            "stereo_width": 0.30,
        },
    },
    {
        "id": "FY3_KEY_004",
        "name": "Freaky Gurl Funk",
        "category": "Keys",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane - Freaky Gurl (2007)",
        "instrument_breakdown": "Mid-range clavinet with moderate saturation and a wah-like brightness sweep. Gives that bouncy, Parliament-Funkadelic-meets-trap groove Zaytoven loved in radio singles.",
        "note": 64,
        "duration": 7.0,
        "params": {
            "key_type": "clavinet",
            "brightness": 0.80,
            "mod_index": 0.0,
            "decay_time": 0.50,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.35,
            "filter_cutoff": 5500.0,
            "reverb_wet": 0.15,
            "reverb_size": 0.35,
            "chorus_mix": 0.08,
            "delay_mix": 0.0,
            "delay_ms": 0,
            "eq_low": -1,
            "eq_mid": 4,
            "eq_high": 3,
            "stereo_width": 0.45,
        },
    },
    {
        "id": "FY3_KEY_005",
        "name": "Juiceman Lo-Fi Clav",
        "category": "Keys",
        "era": "Early (2005-2010)",
        "inspiration": "OJ Da Juiceman - Make Tha Trap Say Aye (2008)",
        "instrument_breakdown": "Gritty lo-fi clavinet with heavy distortion and rolled-off highs. Raw street sound with intentional aliasing that defined OJ Da Juiceman era Zaytoven beats.",
        "note": 60,
        "duration": 7.0,
        "params": {
            "key_type": "clavinet",
            "brightness": 0.50,
            "mod_index": 0.0,
            "decay_time": 0.38,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.60,
            "filter_cutoff": 3800.0,
            "reverb_wet": 0.05,
            "reverb_size": 0.15,
            "chorus_mix": 0.0,
            "delay_mix": 0.0,
            "delay_ms": 0,
            "eq_low": 2,
            "eq_mid": -1,
            "eq_high": -4,
            "stereo_width": 0.25,
        },
    },
    {
        "id": "FY3_KEY_006",
        "name": "Trap Jazz Vibe",
        "category": "Keys",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane - Lemonade (2009)",
        "instrument_breakdown": "Bright vibraphone with quick motor vibrato and medium hall reverb. The quintessential Zaytoven jazz-over-trap melodic voice from the Lemonade era.",
        "note": 65,
        "duration": 8.0,
        "params": {
            "key_type": "vibraphone",
            "brightness": 0.68,
            "mod_index": 2.0,
            "decay_time": 1.5,
            "vibrato_rate": 5.0,
            "vibrato_depth": 0.40,
            "distortion": 0.0,
            "filter_cutoff": 7000.0,
            "reverb_wet": 0.40,
            "reverb_size": 0.60,
            "chorus_mix": 0.12,
            "delay_mix": 0.08,
            "delay_ms": 250,
            "eq_low": -1,
            "eq_mid": 1,
            "eq_high": 3,
            "stereo_width": 0.60,
        },
    },
    {
        "id": "FY3_KEY_007",
        "name": "Chicken Talk Mallet",
        "category": "Keys",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane - Chicken Talk (2006)",
        "instrument_breakdown": "Wooden marimba with slightly boosted mids and short decay. Percussive staccato accent that adds rhythmic texture over hi-hat rolls in early Gucci mixtapes.",
        "note": 69,
        "duration": 6.0,
        "params": {
            "key_type": "marimba",
            "brightness": 0.48,
            "mod_index": 1.0,
            "decay_time": 0.28,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.0,
            "filter_cutoff": 3600.0,
            "reverb_wet": 0.10,
            "reverb_size": 0.25,
            "chorus_mix": 0.0,
            "delay_mix": 0.10,
            "delay_ms": 200,
            "eq_low": -2,
            "eq_mid": 3,
            "eq_high": 0,
            "stereo_width": 0.35,
        },
    },
    {
        "id": "FY3_KEY_008",
        "name": "So Icey Harpsichord",
        "category": "Keys",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane - So Icey (2005)",
        "instrument_breakdown": "Baroque harpsichord with tinny metallic pluck and fast decay. Early Zaytoven classical influence before he refined the piano-centric style, raw and unprocessed.",
        "note": 62,
        "duration": 7.0,
        "params": {
            "key_type": "harpsichord",
            "brightness": 0.65,
            "mod_index": 0.0,
            "decay_time": 0.40,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.10,
            "filter_cutoff": 5000.0,
            "reverb_wet": 0.18,
            "reverb_size": 0.40,
            "chorus_mix": 0.0,
            "delay_mix": 0.05,
            "delay_ms": 150,
            "eq_low": -3,
            "eq_mid": 2,
            "eq_high": 5,
            "stereo_width": 0.50,
        },
    },
    {
        "id": "FY3_KEY_009",
        "name": "Pillz Celesta",
        "category": "Keys",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane - Pillz (2007)",
        "instrument_breakdown": "Glassy celesta with bell-like sustain and subtle FM shimmer. Eerie music-box quality that adds a dark fairy-tale texture to gritty trap instrumentals.",
        "note": 72,
        "duration": 7.0,
        "params": {
            "key_type": "celesta",
            "brightness": 0.58,
            "mod_index": 2.5,
            "decay_time": 1.0,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.0,
            "filter_cutoff": 8000.0,
            "reverb_wet": 0.45,
            "reverb_size": 0.55,
            "chorus_mix": 0.15,
            "delay_mix": 0.12,
            "delay_ms": 300,
            "eq_low": -3,
            "eq_mid": 0,
            "eq_high": 2,
            "stereo_width": 0.65,
        },
    },
    {
        "id": "FY3_KEY_010",
        "name": "Murder Was The Case Clav",
        "category": "Keys",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane - Murder Was the Case (2006)",
        "instrument_breakdown": "Dark clavinet with heavy low-mid saturation and dampened highs. Menacing funk stab that sits underneath aggressive vocal deliveries in early street albums.",
        "note": 55,
        "duration": 7.0,
        "params": {
            "key_type": "clavinet",
            "brightness": 0.35,
            "mod_index": 0.0,
            "decay_time": 0.42,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.50,
            "filter_cutoff": 3000.0,
            "reverb_wet": 0.08,
            "reverb_size": 0.20,
            "chorus_mix": 0.0,
            "delay_mix": 0.0,
            "delay_ms": 0,
            "eq_low": 4,
            "eq_mid": 1,
            "eq_high": -5,
            "stereo_width": 0.30,
        },
    },
    {
        "id": "FY3_KEY_011",
        "name": "745 Vibe Bell",
        "category": "Keys",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane - 745 (2006)",
        "instrument_breakdown": "Bright vibraphone with long sustain and wide stereo spread. Melodic bell tone that floats above the mix, giving early Gucci tracks their signature sparkle.",
        "note": 69,
        "duration": 8.0,
        "params": {
            "key_type": "vibraphone",
            "brightness": 0.75,
            "mod_index": 2.2,
            "decay_time": 1.8,
            "vibrato_rate": 4.0,
            "vibrato_depth": 0.25,
            "distortion": 0.0,
            "filter_cutoff": 7500.0,
            "reverb_wet": 0.50,
            "reverb_size": 0.65,
            "chorus_mix": 0.18,
            "delay_mix": 0.10,
            "delay_ms": 280,
            "eq_low": -2,
            "eq_mid": 0,
            "eq_high": 4,
            "stereo_width": 0.75,
        },
    },
    {
        "id": "FY3_KEY_012",
        "name": "Wasted Harpsichord",
        "category": "Keys",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane - Wasted (2009)",
        "instrument_breakdown": "Processed harpsichord with chorus thickening and slight reverb wash. Party-track brightness that gives the pluck a wider, more modern feel compared to raw baroque patches.",
        "note": 64,
        "duration": 7.0,
        "params": {
            "key_type": "harpsichord",
            "brightness": 0.70,
            "mod_index": 0.0,
            "decay_time": 0.48,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.08,
            "filter_cutoff": 5800.0,
            "reverb_wet": 0.25,
            "reverb_size": 0.45,
            "chorus_mix": 0.20,
            "delay_mix": 0.08,
            "delay_ms": 200,
            "eq_low": -2,
            "eq_mid": 1,
            "eq_high": 4,
            "stereo_width": 0.55,
        },
    },
    {
        "id": "FY3_KEY_013",
        "name": "Photoshoot Marimba",
        "category": "Keys",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane - Photoshoot (2007)",
        "instrument_breakdown": "Bright marimba with open filter and a touch of room reverb. Clean percussive mallet tone used for melodic counter-lines above the main piano riff.",
        "note": 72,
        "duration": 6.0,
        "params": {
            "key_type": "marimba",
            "brightness": 0.60,
            "mod_index": 1.5,
            "decay_time": 0.42,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.0,
            "filter_cutoff": 4800.0,
            "reverb_wet": 0.15,
            "reverb_size": 0.30,
            "chorus_mix": 0.05,
            "delay_mix": 0.0,
            "delay_ms": 0,
            "eq_low": -1,
            "eq_mid": 2,
            "eq_high": 2,
            "stereo_width": 0.40,
        },
    },
    {
        "id": "FY3_KEY_014",
        "name": "Street Cred Clav",
        "category": "Keys",
        "era": "Early (2005-2010)",
        "inspiration": "OJ Da Juiceman - I'm Gettin Money (2009)",
        "instrument_breakdown": "Bright percussive clavinet with crisp attack and minimal effects. Stripped-back rhythmic stab pattern that lets the 808 and hi-hats drive the track.",
        "note": 67,
        "duration": 7.0,
        "params": {
            "key_type": "clavinet",
            "brightness": 0.78,
            "mod_index": 0.0,
            "decay_time": 0.32,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.18,
            "filter_cutoff": 5200.0,
            "reverb_wet": 0.06,
            "reverb_size": 0.15,
            "chorus_mix": 0.0,
            "delay_mix": 0.0,
            "delay_ms": 0,
            "eq_low": -1,
            "eq_mid": 2,
            "eq_high": 5,
            "stereo_width": 0.35,
        },
    },
    {
        "id": "FY3_KEY_015",
        "name": "Trap Back Celesta",
        "category": "Keys",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane - Trap Back (2008)",
        "instrument_breakdown": "Dark celesta with reduced brightness and heavy reverb tail. Music-box-in-a-dungeon feel that adds haunted melodic texture to hard-hitting trap beats.",
        "note": 65,
        "duration": 7.0,
        "params": {
            "key_type": "celesta",
            "brightness": 0.38,
            "mod_index": 2.0,
            "decay_time": 1.3,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.0,
            "filter_cutoff": 5500.0,
            "reverb_wet": 0.55,
            "reverb_size": 0.70,
            "chorus_mix": 0.10,
            "delay_mix": 0.15,
            "delay_ms": 350,
            "eq_low": -1,
            "eq_mid": -2,
            "eq_high": 1,
            "stereo_width": 0.60,
        },
    },
    {
        "id": "FY3_KEY_016",
        "name": "Stupid Wild Vibe",
        "category": "Keys",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane - Stupid Wild (2009)",
        "instrument_breakdown": "Fast vibraphone runs with moderate motor speed and tight decay. Playful jazz-inflected mallet tone for uptempo bounce tracks with rapid sixteenth-note patterns.",
        "note": 60,
        "duration": 6.0,
        "params": {
            "key_type": "vibraphone",
            "brightness": 0.62,
            "mod_index": 1.6,
            "decay_time": 0.8,
            "vibrato_rate": 6.0,
            "vibrato_depth": 0.35,
            "distortion": 0.0,
            "filter_cutoff": 6500.0,
            "reverb_wet": 0.28,
            "reverb_size": 0.40,
            "chorus_mix": 0.08,
            "delay_mix": 0.06,
            "delay_ms": 160,
            "eq_low": 0,
            "eq_mid": 2,
            "eq_high": 2,
            "stereo_width": 0.50,
        },
    },
    {
        "id": "FY3_KEY_017",
        "name": "Coca Coca Clav",
        "category": "Keys",
        "era": "Early (2005-2010)",
        "inspiration": "OJ Da Juiceman - Coca Coca (2009)",
        "instrument_breakdown": "Warm saturated clavinet with boosted low end and scooped mids. Heavy thump-and-click texture that gives OJ's ad-lib-heavy tracks a grimy rhythmic backbone.",
        "note": 55,
        "duration": 7.0,
        "params": {
            "key_type": "clavinet",
            "brightness": 0.45,
            "mod_index": 0.0,
            "decay_time": 0.48,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.45,
            "filter_cutoff": 3500.0,
            "reverb_wet": 0.10,
            "reverb_size": 0.22,
            "chorus_mix": 0.0,
            "delay_mix": 0.04,
            "delay_ms": 120,
            "eq_low": 5,
            "eq_mid": -3,
            "eq_high": -2,
            "stereo_width": 0.28,
        },
    },
    # =========================================================================
    #  PEAK ERA (2010-2016) — FY3_KEY_018 to FY3_KEY_034
    # =========================================================================
    {
        "id": "FY3_KEY_018",
        "name": "Versace Clav",
        "category": "Keys",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos - Versace (2013)",
        "instrument_breakdown": "Crisp electric clavinet with sharp transient and light chorus widening. Punchy rhythmic stab that locks in with hi-hat triplets on Migos' breakout single.",
        "note": 62,
        "duration": 7.0,
        "params": {
            "key_type": "clavinet",
            "brightness": 0.82,
            "mod_index": 0.0,
            "decay_time": 0.35,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.20,
            "filter_cutoff": 5800.0,
            "reverb_wet": 0.10,
            "reverb_size": 0.25,
            "chorus_mix": 0.15,
            "delay_mix": 0.0,
            "delay_ms": 0,
            "eq_low": -2,
            "eq_mid": 3,
            "eq_high": 5,
            "stereo_width": 0.50,
        },
    },
    {
        "id": "FY3_KEY_019",
        "name": "Fight Night Vibe",
        "category": "Keys",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos - Fight Night (2014)",
        "instrument_breakdown": "Bright vibraphone with fast motor vibrato and tight room reverb. Aggressive melodic bell that punches through dense trap mixes with athletic energy.",
        "note": 67,
        "duration": 7.0,
        "params": {
            "key_type": "vibraphone",
            "brightness": 0.78,
            "mod_index": 2.4,
            "decay_time": 1.0,
            "vibrato_rate": 6.5,
            "vibrato_depth": 0.45,
            "distortion": 0.0,
            "filter_cutoff": 7200.0,
            "reverb_wet": 0.22,
            "reverb_size": 0.35,
            "chorus_mix": 0.10,
            "delay_mix": 0.05,
            "delay_ms": 180,
            "eq_low": -1,
            "eq_mid": 2,
            "eq_high": 4,
            "stereo_width": 0.55,
        },
    },
    {
        "id": "FY3_KEY_020",
        "name": "Trap God Harpsichord",
        "category": "Keys",
        "era": "Peak (2010-2016)",
        "inspiration": "Gucci Mane - Trap God (2012)",
        "instrument_breakdown": "Processed harpsichord with tube saturation and stereo delay. Baroque pluck pushed through analog warmth, giving classical melody a hard street edge.",
        "note": 64,
        "duration": 7.0,
        "params": {
            "key_type": "harpsichord",
            "brightness": 0.60,
            "mod_index": 0.0,
            "decay_time": 0.52,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.30,
            "filter_cutoff": 4800.0,
            "reverb_wet": 0.20,
            "reverb_size": 0.45,
            "chorus_mix": 0.05,
            "delay_mix": 0.15,
            "delay_ms": 240,
            "eq_low": -1,
            "eq_mid": 3,
            "eq_high": 3,
            "stereo_width": 0.60,
        },
    },
    {
        "id": "FY3_KEY_021",
        "name": "Blow My Mind Celesta",
        "category": "Keys",
        "era": "Peak (2010-2016)",
        "inspiration": "Future - Blow a Bag (2015)",
        "instrument_breakdown": "Processed celesta with heavy reverb wash and subtle chorus shimmer. Dreamy, almost otherworldly bell tone that gives Future's auto-tuned vocals a celestial backdrop.",
        "note": 72,
        "duration": 8.0,
        "params": {
            "key_type": "celesta",
            "brightness": 0.62,
            "mod_index": 2.8,
            "decay_time": 1.5,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.0,
            "filter_cutoff": 7800.0,
            "reverb_wet": 0.55,
            "reverb_size": 0.72,
            "chorus_mix": 0.22,
            "delay_mix": 0.12,
            "delay_ms": 320,
            "eq_low": -3,
            "eq_mid": -1,
            "eq_high": 3,
            "stereo_width": 0.70,
        },
    },
    {
        "id": "FY3_KEY_022",
        "name": "Hannah Montana Clav",
        "category": "Keys",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos - Hannah Montana (2013)",
        "instrument_breakdown": "Mid-bright clavinet with moderate bite and quick release. Signature Zaytoven clav bounce that drives the repetitive melodic hook in early Migos bangers.",
        "note": 60,
        "duration": 7.0,
        "params": {
            "key_type": "clavinet",
            "brightness": 0.68,
            "mod_index": 0.0,
            "decay_time": 0.30,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.28,
            "filter_cutoff": 4800.0,
            "reverb_wet": 0.08,
            "reverb_size": 0.18,
            "chorus_mix": 0.0,
            "delay_mix": 0.0,
            "delay_ms": 0,
            "eq_low": 0,
            "eq_mid": 4,
            "eq_high": 3,
            "stereo_width": 0.38,
        },
    },
    {
        "id": "FY3_KEY_023",
        "name": "Migos Triplet Marimba",
        "category": "Keys",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos - Bando (2013)",
        "instrument_breakdown": "Bright marimba with snappy attack for triplet flow patterns. Open filter lets the woody overtones sing, matching the rapid-fire delivery of Bando-era Migos.",
        "note": 69,
        "duration": 6.0,
        "params": {
            "key_type": "marimba",
            "brightness": 0.65,
            "mod_index": 1.8,
            "decay_time": 0.32,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.0,
            "filter_cutoff": 5200.0,
            "reverb_wet": 0.12,
            "reverb_size": 0.28,
            "chorus_mix": 0.0,
            "delay_mix": 0.08,
            "delay_ms": 165,
            "eq_low": -2,
            "eq_mid": 3,
            "eq_high": 3,
            "stereo_width": 0.42,
        },
    },
    {
        "id": "FY3_KEY_024",
        "name": "Bird Money Vibe",
        "category": "Keys",
        "era": "Peak (2010-2016)",
        "inspiration": "Gucci Mane - Bird Money ft. Rick Ross (2012)",
        "instrument_breakdown": "Lush vibraphone with wide stereo field and long sustain tail. Rich jazz tone with slow motor tremolo that fills the sonic space between vocal bars.",
        "note": 65,
        "duration": 8.0,
        "params": {
            "key_type": "vibraphone",
            "brightness": 0.60,
            "mod_index": 2.0,
            "decay_time": 2.0,
            "vibrato_rate": 3.0,
            "vibrato_depth": 0.28,
            "distortion": 0.0,
            "filter_cutoff": 6800.0,
            "reverb_wet": 0.48,
            "reverb_size": 0.62,
            "chorus_mix": 0.15,
            "delay_mix": 0.10,
            "delay_ms": 300,
            "eq_low": 0,
            "eq_mid": 1,
            "eq_high": 2,
            "stereo_width": 0.72,
        },
    },
    {
        "id": "FY3_KEY_025",
        "name": "Trap Queen Celesta",
        "category": "Keys",
        "era": "Peak (2010-2016)",
        "inspiration": "Gucci Mane - Trap Queen (2014)",
        "instrument_breakdown": "Warm celesta with moderate FM depth and gentle delay. Sweet bell tone with enough body to carry a melodic hook without competing with the vocal frequency range.",
        "note": 67,
        "duration": 7.0,
        "params": {
            "key_type": "celesta",
            "brightness": 0.52,
            "mod_index": 2.2,
            "decay_time": 1.1,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.0,
            "filter_cutoff": 6500.0,
            "reverb_wet": 0.38,
            "reverb_size": 0.50,
            "chorus_mix": 0.12,
            "delay_mix": 0.10,
            "delay_ms": 260,
            "eq_low": -1,
            "eq_mid": 1,
            "eq_high": 1,
            "stereo_width": 0.55,
        },
    },
    {
        "id": "FY3_KEY_026",
        "name": "Cross The Country Clav",
        "category": "Keys",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos - Cross The Country (2014)",
        "instrument_breakdown": "Aggressive clavinet with high distortion and boosted presence. Biting funk stab that cuts through layers of ad-libs and stacked vocal tracks.",
        "note": 64,
        "duration": 7.0,
        "params": {
            "key_type": "clavinet",
            "brightness": 0.85,
            "mod_index": 0.0,
            "decay_time": 0.28,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.55,
            "filter_cutoff": 6000.0,
            "reverb_wet": 0.05,
            "reverb_size": 0.12,
            "chorus_mix": 0.0,
            "delay_mix": 0.0,
            "delay_ms": 0,
            "eq_low": -3,
            "eq_mid": 5,
            "eq_high": 6,
            "stereo_width": 0.32,
        },
    },
    {
        "id": "FY3_KEY_027",
        "name": "YRN Harpsichord",
        "category": "Keys",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos - Young Rich Niggas (2013)",
        "instrument_breakdown": "Bright harpsichord with doubled octave and stereo chorus spread. Regal plucked texture that gives YRN-era Migos beats a baroque grandeur above hard 808s.",
        "note": 60,
        "duration": 7.0,
        "params": {
            "key_type": "harpsichord",
            "brightness": 0.75,
            "mod_index": 0.0,
            "decay_time": 0.45,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.12,
            "filter_cutoff": 6200.0,
            "reverb_wet": 0.22,
            "reverb_size": 0.42,
            "chorus_mix": 0.25,
            "delay_mix": 0.08,
            "delay_ms": 210,
            "eq_low": -2,
            "eq_mid": 2,
            "eq_high": 5,
            "stereo_width": 0.65,
        },
    },
    {
        "id": "FY3_KEY_028",
        "name": "Everybody Lookin Vibe",
        "category": "Keys",
        "era": "Peak (2010-2016)",
        "inspiration": "Gucci Mane - Everybody Looking (2016)",
        "instrument_breakdown": "Polished vibraphone with balanced EQ and medium motor vibrato. Post-prison Gucci era refinement with cleaner production and more deliberate melodic phrasing.",
        "note": 62,
        "duration": 7.0,
        "params": {
            "key_type": "vibraphone",
            "brightness": 0.65,
            "mod_index": 2.0,
            "decay_time": 1.3,
            "vibrato_rate": 4.5,
            "vibrato_depth": 0.32,
            "distortion": 0.0,
            "filter_cutoff": 7000.0,
            "reverb_wet": 0.32,
            "reverb_size": 0.48,
            "chorus_mix": 0.10,
            "delay_mix": 0.06,
            "delay_ms": 220,
            "eq_low": 0,
            "eq_mid": 1,
            "eq_high": 2,
            "stereo_width": 0.58,
        },
    },
    {
        "id": "FY3_KEY_029",
        "name": "Deadz Clav Crunch",
        "category": "Keys",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos - Deadz ft. 2 Chainz (2016)",
        "instrument_breakdown": "Crunchy clavinet with mid-heavy distortion and tight gate. Punchy saturated funk tone that drives the groove under triplet flows and 2 Chainz punchlines.",
        "note": 65,
        "duration": 7.0,
        "params": {
            "key_type": "clavinet",
            "brightness": 0.70,
            "mod_index": 0.0,
            "decay_time": 0.25,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.48,
            "filter_cutoff": 4200.0,
            "reverb_wet": 0.04,
            "reverb_size": 0.10,
            "chorus_mix": 0.0,
            "delay_mix": 0.0,
            "delay_ms": 0,
            "eq_low": 1,
            "eq_mid": 5,
            "eq_high": 2,
            "stereo_width": 0.30,
        },
    },
    {
        "id": "FY3_KEY_030",
        "name": "Future DS2 Celesta",
        "category": "Keys",
        "era": "Peak (2010-2016)",
        "inspiration": "Future - DS2 (2015)",
        "instrument_breakdown": "Spacious celesta with long reverb tail and delayed repeats. Ethereal bell texture floating in a cavernous space, perfect under Future's melancholic auto-tune.",
        "note": 69,
        "duration": 8.0,
        "params": {
            "key_type": "celesta",
            "brightness": 0.55,
            "mod_index": 3.0,
            "decay_time": 1.8,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.0,
            "filter_cutoff": 7500.0,
            "reverb_wet": 0.60,
            "reverb_size": 0.78,
            "chorus_mix": 0.18,
            "delay_mix": 0.18,
            "delay_ms": 375,
            "eq_low": -4,
            "eq_mid": -1,
            "eq_high": 2,
            "stereo_width": 0.80,
        },
    },
    {
        "id": "FY3_KEY_031",
        "name": "Spray Marimba",
        "category": "Keys",
        "era": "Peak (2010-2016)",
        "inspiration": "Gucci Mane - Spray (2011)",
        "instrument_breakdown": "Filtered marimba with boosted mids and short staccato hits. Woody mallet accent that punches through during sparse breakdowns between vocal sections.",
        "note": 72,
        "duration": 6.0,
        "params": {
            "key_type": "marimba",
            "brightness": 0.52,
            "mod_index": 1.4,
            "decay_time": 0.25,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.0,
            "filter_cutoff": 3800.0,
            "reverb_wet": 0.10,
            "reverb_size": 0.22,
            "chorus_mix": 0.0,
            "delay_mix": 0.12,
            "delay_ms": 190,
            "eq_low": -3,
            "eq_mid": 4,
            "eq_high": 1,
            "stereo_width": 0.35,
        },
    },
    {
        "id": "FY3_KEY_032",
        "name": "Freak No More Harp",
        "category": "Keys",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos - Freak No More (2015)",
        "instrument_breakdown": "Dark harpsichord with heavy low-pass filtering and reverb depth. Moody plucked tone stripped of high-end bite, creating an ominous melodic undercurrent.",
        "note": 55,
        "duration": 7.0,
        "params": {
            "key_type": "harpsichord",
            "brightness": 0.40,
            "mod_index": 0.0,
            "decay_time": 0.55,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.15,
            "filter_cutoff": 3200.0,
            "reverb_wet": 0.35,
            "reverb_size": 0.55,
            "chorus_mix": 0.08,
            "delay_mix": 0.10,
            "delay_ms": 280,
            "eq_low": 2,
            "eq_mid": 0,
            "eq_high": -4,
            "stereo_width": 0.48,
        },
    },
    {
        "id": "FY3_KEY_033",
        "name": "Saran Pack Vibe",
        "category": "Keys",
        "era": "Peak (2010-2016)",
        "inspiration": "Gucci Mane - Saran Pack (2014)",
        "instrument_breakdown": "Metallic vibraphone with fast motor and minimal reverb. Dry, in-your-face bell tone with aggressive motor warble that matches the intensity of street rap delivery.",
        "note": 60,
        "duration": 6.0,
        "params": {
            "key_type": "vibraphone",
            "brightness": 0.72,
            "mod_index": 2.6,
            "decay_time": 0.7,
            "vibrato_rate": 7.0,
            "vibrato_depth": 0.50,
            "distortion": 0.0,
            "filter_cutoff": 6200.0,
            "reverb_wet": 0.10,
            "reverb_size": 0.20,
            "chorus_mix": 0.0,
            "delay_mix": 0.04,
            "delay_ms": 140,
            "eq_low": -1,
            "eq_mid": 3,
            "eq_high": 3,
            "stereo_width": 0.40,
        },
    },
    {
        "id": "FY3_KEY_034",
        "name": "First Day Out Celesta",
        "category": "Keys",
        "era": "Peak (2010-2016)",
        "inspiration": "Gucci Mane - First Day Out Tha Feds (2016)",
        "instrument_breakdown": "Celebratory celesta with bright FM harmonics and medium room. Triumphant music-box sparkle marking Gucci's return, clean and confident with radio-ready polish.",
        "note": 72,
        "duration": 7.0,
        "params": {
            "key_type": "celesta",
            "brightness": 0.70,
            "mod_index": 2.5,
            "decay_time": 1.2,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.0,
            "filter_cutoff": 8500.0,
            "reverb_wet": 0.30,
            "reverb_size": 0.45,
            "chorus_mix": 0.14,
            "delay_mix": 0.08,
            "delay_ms": 240,
            "eq_low": -2,
            "eq_mid": 1,
            "eq_high": 4,
            "stereo_width": 0.62,
        },
    },
    # =========================================================================
    #  MODERN ERA (2016+) — FY3_KEY_035 to FY3_KEY_050
    # =========================================================================
    {
        "id": "FY3_KEY_035",
        "name": "Trap Holizay Synth Clav",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "Zaytoven - Trap Holizay (2018)",
        "instrument_breakdown": "Synthetic clavinet with heavy chorus and delay. Modern hybrid texture blending acoustic clav character with digital processing, Zaytoven's evolved 2018 sound.",
        "note": 62,
        "duration": 7.0,
        "params": {
            "key_type": "clavinet",
            "brightness": 0.75,
            "mod_index": 0.0,
            "decay_time": 0.40,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.22,
            "filter_cutoff": 5200.0,
            "reverb_wet": 0.18,
            "reverb_size": 0.35,
            "chorus_mix": 0.28,
            "delay_mix": 0.15,
            "delay_ms": 250,
            "eq_low": -1,
            "eq_mid": 2,
            "eq_high": 4,
            "stereo_width": 0.65,
        },
    },
    {
        "id": "FY3_KEY_036",
        "name": "Lil Uzi Hybrid Mallet",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "Lil Uzi Vert - Sanguine Paradise (2019)",
        "instrument_breakdown": "Bright marimba with heavy chorus widening and delay tail. Hybrid mallet tone blending organic wood with digital spread for the melodic trap-rock crossover sound.",
        "note": 69,
        "duration": 7.0,
        "params": {
            "key_type": "marimba",
            "brightness": 0.72,
            "mod_index": 2.0,
            "decay_time": 0.50,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.0,
            "filter_cutoff": 5500.0,
            "reverb_wet": 0.30,
            "reverb_size": 0.45,
            "chorus_mix": 0.30,
            "delay_mix": 0.18,
            "delay_ms": 280,
            "eq_low": -1,
            "eq_mid": 1,
            "eq_high": 3,
            "stereo_width": 0.70,
        },
    },
    {
        "id": "FY3_KEY_037",
        "name": "21 Savage Digital Celesta",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "21 Savage - a lot ft. J. Cole (2018)",
        "instrument_breakdown": "Cold digital celesta with minimal reverb and flat EQ. Sparse, clinical bell tone that mirrors 21 Savage's deadpan delivery and minimalist production style.",
        "note": 67,
        "duration": 7.0,
        "params": {
            "key_type": "celesta",
            "brightness": 0.50,
            "mod_index": 2.0,
            "decay_time": 0.9,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.0,
            "filter_cutoff": 6000.0,
            "reverb_wet": 0.15,
            "reverb_size": 0.25,
            "chorus_mix": 0.0,
            "delay_mix": 0.05,
            "delay_ms": 200,
            "eq_low": 0,
            "eq_mid": 0,
            "eq_high": 0,
            "stereo_width": 0.40,
        },
    },
    {
        "id": "FY3_KEY_038",
        "name": "GlokkNine Processed Vibe",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "GlokkNine - 10 Percent (2018)",
        "instrument_breakdown": "Processed vibraphone with aggressive motor vibrato and tight gating. Warped metallic bell with exaggerated wobble for Florida-influenced aggressive trap energy.",
        "note": 64,
        "duration": 6.0,
        "params": {
            "key_type": "vibraphone",
            "brightness": 0.80,
            "mod_index": 2.8,
            "decay_time": 0.6,
            "vibrato_rate": 8.0,
            "vibrato_depth": 0.55,
            "distortion": 0.0,
            "filter_cutoff": 7000.0,
            "reverb_wet": 0.12,
            "reverb_size": 0.18,
            "chorus_mix": 0.0,
            "delay_mix": 0.08,
            "delay_ms": 150,
            "eq_low": -2,
            "eq_mid": 4,
            "eq_high": 5,
            "stereo_width": 0.45,
        },
    },
    {
        "id": "FY3_KEY_039",
        "name": "Drip Too Hard Harp",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "Lil Baby & Gunna - Drip Too Hard (2018)",
        "instrument_breakdown": "Modern harpsichord with bright chorus and stereo delay. Updated baroque pluck with digital sheen that fits the polished Atlanta drip sound of 2018.",
        "note": 65,
        "duration": 7.0,
        "params": {
            "key_type": "harpsichord",
            "brightness": 0.72,
            "mod_index": 0.0,
            "decay_time": 0.42,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.08,
            "filter_cutoff": 6000.0,
            "reverb_wet": 0.20,
            "reverb_size": 0.38,
            "chorus_mix": 0.22,
            "delay_mix": 0.12,
            "delay_ms": 230,
            "eq_low": -2,
            "eq_mid": 1,
            "eq_high": 5,
            "stereo_width": 0.68,
        },
    },
    {
        "id": "FY3_KEY_040",
        "name": "Wicked Clav",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "Future - Wicked (2020)",
        "instrument_breakdown": "Dark processed clavinet with low-pass sweep and heavy saturation. Murky, ominous funk stab with reduced high end that matches Future's darker sonic palette.",
        "note": 55,
        "duration": 7.0,
        "params": {
            "key_type": "clavinet",
            "brightness": 0.38,
            "mod_index": 0.0,
            "decay_time": 0.50,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.58,
            "filter_cutoff": 2800.0,
            "reverb_wet": 0.15,
            "reverb_size": 0.30,
            "chorus_mix": 0.05,
            "delay_mix": 0.0,
            "delay_ms": 0,
            "eq_low": 4,
            "eq_mid": 0,
            "eq_high": -6,
            "stereo_width": 0.30,
        },
    },
    {
        "id": "FY3_KEY_041",
        "name": "East Atlanta Day Vibe",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "Gucci Mane - East Atlanta Day (2017)",
        "instrument_breakdown": "Balanced vibraphone with moderate motor and wide reverb. Mature jazz-trap tone reflecting post-prison Gucci's cleaner aesthetic and more measured production style.",
        "note": 62,
        "duration": 8.0,
        "params": {
            "key_type": "vibraphone",
            "brightness": 0.58,
            "mod_index": 1.8,
            "decay_time": 1.6,
            "vibrato_rate": 4.0,
            "vibrato_depth": 0.30,
            "distortion": 0.0,
            "filter_cutoff": 6500.0,
            "reverb_wet": 0.42,
            "reverb_size": 0.58,
            "chorus_mix": 0.12,
            "delay_mix": 0.08,
            "delay_ms": 260,
            "eq_low": 0,
            "eq_mid": 1,
            "eq_high": 1,
            "stereo_width": 0.62,
        },
    },
    {
        "id": "FY3_KEY_042",
        "name": "Culture III Marimba",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "Migos - Culture III (2021)",
        "instrument_breakdown": "Polished marimba with chorus shimmer and subtle delay. Refined mallet tone for Migos' later work, more produced and layered than the raw early mixtape sound.",
        "note": 67,
        "duration": 7.0,
        "params": {
            "key_type": "marimba",
            "brightness": 0.62,
            "mod_index": 1.6,
            "decay_time": 0.45,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.0,
            "filter_cutoff": 5000.0,
            "reverb_wet": 0.25,
            "reverb_size": 0.40,
            "chorus_mix": 0.18,
            "delay_mix": 0.10,
            "delay_ms": 220,
            "eq_low": -1,
            "eq_mid": 2,
            "eq_high": 2,
            "stereo_width": 0.55,
        },
    },
    {
        "id": "FY3_KEY_043",
        "name": "Ice Cream Man Celesta",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "Gucci Mane - Ice Cream Man (2017)",
        "instrument_breakdown": "Playful bright celesta with quick decay and stereo ping-pong delay. Whimsical ice cream truck melody tone that brings nostalgic childhood texture to modern trap.",
        "note": 72,
        "duration": 6.0,
        "params": {
            "key_type": "celesta",
            "brightness": 0.75,
            "mod_index": 2.4,
            "decay_time": 0.7,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.0,
            "filter_cutoff": 8000.0,
            "reverb_wet": 0.20,
            "reverb_size": 0.32,
            "chorus_mix": 0.08,
            "delay_mix": 0.22,
            "delay_ms": 190,
            "eq_low": -3,
            "eq_mid": 0,
            "eq_high": 5,
            "stereo_width": 0.75,
        },
    },
    {
        "id": "FY3_KEY_044",
        "name": "Woptober Harp",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "Gucci Mane - Woptober (2016)",
        "instrument_breakdown": "Warm harpsichord with analog-style saturation and reverb wash. Thick baroque pluck with softened attack, bridging the Peak-to-Modern era transition in Gucci's catalog.",
        "note": 60,
        "duration": 7.0,
        "params": {
            "key_type": "harpsichord",
            "brightness": 0.55,
            "mod_index": 0.0,
            "decay_time": 0.58,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.25,
            "filter_cutoff": 4500.0,
            "reverb_wet": 0.30,
            "reverb_size": 0.50,
            "chorus_mix": 0.10,
            "delay_mix": 0.06,
            "delay_ms": 200,
            "eq_low": 1,
            "eq_mid": 2,
            "eq_high": 1,
            "stereo_width": 0.52,
        },
    },
    {
        "id": "FY3_KEY_045",
        "name": "Wake Up Clav Bounce",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "Zaytoven & Gucci Mane - Wake Up (2017)",
        "instrument_breakdown": "Bouncy clavinet with moderate brightness and rhythmic delay. Uptempo funk character with synced delay taps that reinforce the groove's rhythmic momentum.",
        "note": 64,
        "duration": 7.0,
        "params": {
            "key_type": "clavinet",
            "brightness": 0.65,
            "mod_index": 0.0,
            "decay_time": 0.35,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.30,
            "filter_cutoff": 4800.0,
            "reverb_wet": 0.10,
            "reverb_size": 0.22,
            "chorus_mix": 0.05,
            "delay_mix": 0.18,
            "delay_ms": 200,
            "eq_low": 0,
            "eq_mid": 3,
            "eq_high": 3,
            "stereo_width": 0.45,
        },
    },
    {
        "id": "FY3_KEY_046",
        "name": "Waybach Vibraphone",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "Gucci Mane - Waybach (2019)",
        "instrument_breakdown": "Luxurious vibraphone with slow motor and spacious hall reverb. Rich, sustained bell tone with premium feel, matching the opulent lifestyle aesthetic of late-era Gucci.",
        "note": 65,
        "duration": 8.0,
        "params": {
            "key_type": "vibraphone",
            "brightness": 0.60,
            "mod_index": 2.2,
            "decay_time": 2.2,
            "vibrato_rate": 2.5,
            "vibrato_depth": 0.22,
            "distortion": 0.0,
            "filter_cutoff": 7200.0,
            "reverb_wet": 0.52,
            "reverb_size": 0.70,
            "chorus_mix": 0.15,
            "delay_mix": 0.10,
            "delay_ms": 300,
            "eq_low": 0,
            "eq_mid": 0,
            "eq_high": 2,
            "stereo_width": 0.78,
        },
    },
    {
        "id": "FY3_KEY_047",
        "name": "Racks 2 Skinny Marimba",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "Migos - Racks 2 Skinny (2018)",
        "instrument_breakdown": "Sharp marimba with bright attack and tight gating. Percussive accent that pops through compressed mixes, adding rhythmic punctuation to hard-panning vocal arrangements.",
        "note": 72,
        "duration": 6.0,
        "params": {
            "key_type": "marimba",
            "brightness": 0.75,
            "mod_index": 1.8,
            "decay_time": 0.22,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.0,
            "filter_cutoff": 5800.0,
            "reverb_wet": 0.08,
            "reverb_size": 0.15,
            "chorus_mix": 0.0,
            "delay_mix": 0.06,
            "delay_ms": 140,
            "eq_low": -3,
            "eq_mid": 2,
            "eq_high": 5,
            "stereo_width": 0.38,
        },
    },
    {
        "id": "FY3_KEY_048",
        "name": "Packs On Packs Harp",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "Zaytoven - Packs on Packs (2019)",
        "instrument_breakdown": "Digital harpsichord with bright attack and heavy stereo chorus. Modernized pluck with synthetic sheen that represents Zaytoven's evolution into fully digital production.",
        "note": 67,
        "duration": 7.0,
        "params": {
            "key_type": "harpsichord",
            "brightness": 0.78,
            "mod_index": 0.0,
            "decay_time": 0.38,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.05,
            "filter_cutoff": 6500.0,
            "reverb_wet": 0.18,
            "reverb_size": 0.32,
            "chorus_mix": 0.32,
            "delay_mix": 0.10,
            "delay_ms": 180,
            "eq_low": -2,
            "eq_mid": 1,
            "eq_high": 6,
            "stereo_width": 0.72,
        },
    },
    {
        "id": "FY3_KEY_049",
        "name": "Trap Funeral Celesta",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "21 Savage & Metro Boomin - Savage Mode II (2020)",
        "instrument_breakdown": "Haunting celesta with deep reverb and dark filtering. Ghostly bell tone with cavernous space that evokes the cinematic horror-trap aesthetic of modern Atlanta production.",
        "note": 60,
        "duration": 8.0,
        "params": {
            "key_type": "celesta",
            "brightness": 0.35,
            "mod_index": 2.8,
            "decay_time": 2.0,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.0,
            "filter_cutoff": 5000.0,
            "reverb_wet": 0.65,
            "reverb_size": 0.82,
            "chorus_mix": 0.10,
            "delay_mix": 0.20,
            "delay_ms": 400,
            "eq_low": -1,
            "eq_mid": -3,
            "eq_high": -1,
            "stereo_width": 0.85,
        },
    },
    {
        "id": "FY3_KEY_050",
        "name": "Zaytoven Legacy Clav",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "Zaytoven - Where Would the Game Be Without Me 3 (2022)",
        "instrument_breakdown": "Signature clavinet combining warm saturation with modern stereo processing. The fully evolved Zaytoven clav tone, balancing vintage funk soul with contemporary trap polish.",
        "note": 60,
        "duration": 7.0,
        "params": {
            "key_type": "clavinet",
            "brightness": 0.70,
            "mod_index": 0.0,
            "decay_time": 0.42,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.35,
            "filter_cutoff": 4800.0,
            "reverb_wet": 0.15,
            "reverb_size": 0.30,
            "chorus_mix": 0.12,
            "delay_mix": 0.08,
            "delay_ms": 200,
            "eq_low": 1,
            "eq_mid": 3,
            "eq_high": 2,
            "stereo_width": 0.55,
        },
    },
    # ══════════════════════════════════════════════════════════════════════
    # UNDERREPRESENTED ARTIST EXPANSION — Presets 051-074
    # ══════════════════════════════════════════════════════════════════════
    {
        "id": "FY3_KEY_051",
        "name": "Usher Smooth Vibes",
        "category": "Keys",
        "era": "Peak (2010-2016)",
        "inspiration": "Usher - Raymond vs. Raymond (2010)",
        "instrument_breakdown": "Warm vibraphone with slow motor vibrato and lush reverb. Smooth jazzy keys for romantic R&B productions.",
        "note": 67,
        "duration": 8.0,
        "params": {
            "key_type": "vibraphone",
            "brightness": 0.45,
            "mod_index": 1.5,
            "decay_time": 1.5,
            "vibrato_rate": 3.0,
            "vibrato_depth": 0.3,
            "distortion": 0.0,
            "filter_cutoff": 5500.0,
            "reverb_wet": 0.42,
            "reverb_size": 0.58,
            "chorus_mix": 0.12,
            "delay_mix": 0.08,
            "delay_ms": 300,
            "eq_low": 0,
            "eq_mid": 2,
            "eq_high": 1,
            "stereo_width": 0.55,
        },
    },
    {
        "id": "FY3_KEY_052",
        "name": "Usher Celesta Dream",
        "category": "Keys",
        "era": "Peak (2010-2016)",
        "inspiration": "Usher - Climax (2012)",
        "instrument_breakdown": "Dreamy celesta with ethereal shimmer and long reverb tail. Delicate celestial keys for atmospheric R&B moments.",
        "note": 72,
        "duration": 8.0,
        "params": {
            "key_type": "celesta",
            "brightness": 0.5,
            "mod_index": 2.0,
            "decay_time": 1.8,
            "vibrato_rate": 3.5,
            "vibrato_depth": 0.15,
            "distortion": 0.0,
            "filter_cutoff": 6000.0,
            "reverb_wet": 0.5,
            "reverb_size": 0.7,
            "chorus_mix": 0.15,
            "delay_mix": 0.12,
            "delay_ms": 350,
            "eq_low": -1,
            "eq_mid": 0,
            "eq_high": 2,
            "stereo_width": 0.6,
        },
    },
    {
        "id": "FY3_KEY_053",
        "name": "Waka Hard Clav",
        "category": "Keys",
        "era": "Early (2005-2010)",
        "inspiration": "Waka Flocka Flame - Flockaveli (2010)",
        "instrument_breakdown": "Aggressive clavinet with heavy saturation and biting attack. Hard funky keys for Flockaveli-era trap bangers.",
        "note": 60,
        "duration": 6.0,
        "params": {
            "key_type": "clavinet",
            "brightness": 0.75,
            "mod_index": 0.0,
            "decay_time": 0.35,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.45,
            "filter_cutoff": 5000.0,
            "reverb_wet": 0.08,
            "reverb_size": 0.15,
            "chorus_mix": 0.0,
            "delay_mix": 0.0,
            "delay_ms": 0,
            "eq_low": -2,
            "eq_mid": 4,
            "eq_high": 3,
            "stereo_width": 0.3,
        },
    },
    {
        "id": "FY3_KEY_054",
        "name": "Waka Marimba Punch",
        "category": "Keys",
        "era": "Early (2005-2010)",
        "inspiration": "Waka Flocka Flame - Hard in da Paint (2010)",
        "instrument_breakdown": "Punchy marimba with hard attack and tight decay. Percussive wooden keys for aggressive trap patterns.",
        "note": 67,
        "duration": 6.0,
        "params": {
            "key_type": "marimba",
            "brightness": 0.55,
            "mod_index": 1.5,
            "decay_time": 0.3,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.0,
            "filter_cutoff": 4000.0,
            "reverb_wet": 0.08,
            "reverb_size": 0.18,
            "chorus_mix": 0.0,
            "delay_mix": 0.05,
            "delay_ms": 160,
            "eq_low": -1,
            "eq_mid": 2,
            "eq_high": 1,
            "stereo_width": 0.3,
        },
    },
    {
        "id": "FY3_KEY_055",
        "name": "Quavo Melodic Vibes",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "Quavo - Quavo Huncho (2018)",
        "instrument_breakdown": "Bright vibraphone with melodic shimmer and catchy sustain. Sparkling jazzy keys for Quavo-style melodic hooks.",
        "note": 72,
        "duration": 7.0,
        "params": {
            "key_type": "vibraphone",
            "brightness": 0.6,
            "mod_index": 2.0,
            "decay_time": 1.3,
            "vibrato_rate": 4.0,
            "vibrato_depth": 0.25,
            "distortion": 0.0,
            "filter_cutoff": 6500.0,
            "reverb_wet": 0.35,
            "reverb_size": 0.5,
            "chorus_mix": 0.1,
            "delay_mix": 0.1,
            "delay_ms": 260,
            "eq_low": -1,
            "eq_mid": 1,
            "eq_high": 2,
            "stereo_width": 0.55,
        },
    },
    {
        "id": "FY3_KEY_056",
        "name": "Quavo Celesta Sparkle",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "Quavo - Rocket Power (2024)",
        "instrument_breakdown": "Sparkling celesta with futuristic shimmer. Bright crystalline keys for spacey melodic trap production.",
        "note": 76,
        "duration": 7.0,
        "params": {
            "key_type": "celesta",
            "brightness": 0.65,
            "mod_index": 2.5,
            "decay_time": 1.5,
            "vibrato_rate": 3.5,
            "vibrato_depth": 0.12,
            "distortion": 0.0,
            "filter_cutoff": 7000.0,
            "reverb_wet": 0.38,
            "reverb_size": 0.55,
            "chorus_mix": 0.12,
            "delay_mix": 0.12,
            "delay_ms": 280,
            "eq_low": -2,
            "eq_mid": 0,
            "eq_high": 3,
            "stereo_width": 0.6,
        },
    },
    {
        "id": "FY3_KEY_057",
        "name": "Offset Dark Harpsichord",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "Offset - Father of 4 (2019)",
        "instrument_breakdown": "Dark harpsichord with menacing pluck and controlled sustain. Ominous baroque keys for hard modern trap.",
        "note": 60,
        "duration": 7.0,
        "params": {
            "key_type": "harpsichord",
            "brightness": 0.35,
            "mod_index": 0.5,
            "decay_time": 0.4,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.05,
            "filter_cutoff": 3500.0,
            "reverb_wet": 0.2,
            "reverb_size": 0.35,
            "chorus_mix": 0.05,
            "delay_mix": 0.06,
            "delay_ms": 200,
            "eq_low": 0,
            "eq_mid": 2,
            "eq_high": -1,
            "stereo_width": 0.4,
        },
    },
    {
        "id": "FY3_KEY_058",
        "name": "Offset Clout Clav",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "Offset - Clout (2019)",
        "instrument_breakdown": "Punchy clavinet with aggressive bite and modern sheen. Hard funky keys for flex-anthem trap production.",
        "note": 64,
        "duration": 6.0,
        "params": {
            "key_type": "clavinet",
            "brightness": 0.7,
            "mod_index": 0.0,
            "decay_time": 0.38,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.35,
            "filter_cutoff": 4800.0,
            "reverb_wet": 0.1,
            "reverb_size": 0.2,
            "chorus_mix": 0.0,
            "delay_mix": 0.05,
            "delay_ms": 160,
            "eq_low": -1,
            "eq_mid": 3,
            "eq_high": 3,
            "stereo_width": 0.35,
        },
    },
    {
        "id": "FY3_KEY_059",
        "name": "Takeoff Quick Marimba",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "Takeoff - The Last Rocket (2018)",
        "instrument_breakdown": "Fast-decay marimba for rapid melodic patterns. Technical wooden keys for Takeoff-style precision production.",
        "note": 72,
        "duration": 6.0,
        "params": {
            "key_type": "marimba",
            "brightness": 0.5,
            "mod_index": 1.5,
            "decay_time": 0.25,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.0,
            "filter_cutoff": 4500.0,
            "reverb_wet": 0.08,
            "reverb_size": 0.15,
            "chorus_mix": 0.0,
            "delay_mix": 0.06,
            "delay_ms": 140,
            "eq_low": -1,
            "eq_mid": 1,
            "eq_high": 1,
            "stereo_width": 0.3,
        },
    },
    {
        "id": "FY3_KEY_060",
        "name": "Takeoff Celesta Precision",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "Takeoff - Last Memory (2018)",
        "instrument_breakdown": "Precise celesta with clean attack and defined sustain. Technical celestial keys for intricate melodic layering.",
        "note": 76,
        "duration": 7.0,
        "params": {
            "key_type": "celesta",
            "brightness": 0.55,
            "mod_index": 2.0,
            "decay_time": 1.0,
            "vibrato_rate": 3.0,
            "vibrato_depth": 0.1,
            "distortion": 0.0,
            "filter_cutoff": 6000.0,
            "reverb_wet": 0.2,
            "reverb_size": 0.32,
            "chorus_mix": 0.06,
            "delay_mix": 0.08,
            "delay_ms": 180,
            "eq_low": -1,
            "eq_mid": 0,
            "eq_high": 2,
            "stereo_width": 0.42,
        },
    },
    {
        "id": "FY3_KEY_061",
        "name": "YB Emotional Vibes",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "NBA YoungBoy - AI YoungBoy 2 (2019)",
        "instrument_breakdown": "Melancholic vibraphone with heavy motor vibrato and emotional sustain. Haunting jazzy keys for pain-driven melodic trap.",
        "note": 64,
        "duration": 8.0,
        "params": {
            "key_type": "vibraphone",
            "brightness": 0.4,
            "mod_index": 1.8,
            "decay_time": 1.5,
            "vibrato_rate": 3.5,
            "vibrato_depth": 0.35,
            "distortion": 0.0,
            "filter_cutoff": 5000.0,
            "reverb_wet": 0.45,
            "reverb_size": 0.6,
            "chorus_mix": 0.12,
            "delay_mix": 0.1,
            "delay_ms": 320,
            "eq_low": 0,
            "eq_mid": 1,
            "eq_high": 0,
            "stereo_width": 0.55,
        },
    },
    {
        "id": "FY3_KEY_062",
        "name": "YB Dark Harpsichord",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "NBA YoungBoy - Sincerely Kentrell (2021)",
        "instrument_breakdown": "Dark harpsichord with ominous pluck and heavy reverb. Gothic baroque keys for aggressive emotional trap.",
        "note": 58,
        "duration": 7.0,
        "params": {
            "key_type": "harpsichord",
            "brightness": 0.3,
            "mod_index": 0.5,
            "decay_time": 0.45,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.08,
            "filter_cutoff": 3000.0,
            "reverb_wet": 0.35,
            "reverb_size": 0.5,
            "chorus_mix": 0.08,
            "delay_mix": 0.08,
            "delay_ms": 280,
            "eq_low": 1,
            "eq_mid": 1,
            "eq_high": -2,
            "stereo_width": 0.45,
        },
    },
    {
        "id": "FY3_KEY_063",
        "name": "OJ Classic Vibes",
        "category": "Keys",
        "era": "Early (2005-2010)",
        "inspiration": "OJ Da Juiceman - The Otha Side of the Trap (2009)",
        "instrument_breakdown": "Classic vibraphone with vintage warmth and old-school charm. Traditional jazz keys from early Zone 6 trap.",
        "note": 67,
        "duration": 7.0,
        "params": {
            "key_type": "vibraphone",
            "brightness": 0.5,
            "mod_index": 1.8,
            "decay_time": 1.2,
            "vibrato_rate": 3.5,
            "vibrato_depth": 0.28,
            "distortion": 0.0,
            "filter_cutoff": 5500.0,
            "reverb_wet": 0.3,
            "reverb_size": 0.45,
            "chorus_mix": 0.08,
            "delay_mix": 0.0,
            "delay_ms": 0,
            "eq_low": 0,
            "eq_mid": 2,
            "eq_high": 1,
            "stereo_width": 0.45,
        },
    },
    {
        "id": "FY3_KEY_064",
        "name": "OJ Marimba Trap",
        "category": "Keys",
        "era": "Early (2005-2010)",
        "inspiration": "OJ Da Juiceman - Make tha Trap Say Aye (2008)",
        "instrument_breakdown": "Warm trap marimba with vintage character. Classic wooden accent from the golden Juiceman era.",
        "note": 72,
        "duration": 7.0,
        "params": {
            "key_type": "marimba",
            "brightness": 0.42,
            "mod_index": 1.2,
            "decay_time": 0.38,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.0,
            "filter_cutoff": 3500.0,
            "reverb_wet": 0.12,
            "reverb_size": 0.25,
            "chorus_mix": 0.0,
            "delay_mix": 0.05,
            "delay_ms": 200,
            "eq_low": 0,
            "eq_mid": 1,
            "eq_high": 0,
            "stereo_width": 0.35,
        },
    },
    {
        "id": "FY3_KEY_065",
        "name": "Dolph Memphis Clav",
        "category": "Keys",
        "era": "Peak (2010-2016)",
        "inspiration": "Young Dolph - King of Memphis (2016)",
        "instrument_breakdown": "Gritty Memphis clavinet with heavy saturation. Street-hardened funky keys for kingpin anthem production.",
        "note": 60,
        "duration": 7.0,
        "params": {
            "key_type": "clavinet",
            "brightness": 0.68,
            "mod_index": 0.0,
            "decay_time": 0.4,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.4,
            "filter_cutoff": 4500.0,
            "reverb_wet": 0.1,
            "reverb_size": 0.2,
            "chorus_mix": 0.0,
            "delay_mix": 0.0,
            "delay_ms": 0,
            "eq_low": -1,
            "eq_mid": 4,
            "eq_high": 2,
            "stereo_width": 0.35,
        },
    },
    {
        "id": "FY3_KEY_066",
        "name": "Dolph Harpsichord Dark",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "Young Dolph - Rich Slave (2020)",
        "instrument_breakdown": "Dark harpsichord with Memphis grit and street edge. Ominous baroque pluck for aggressive narrative trap.",
        "note": 58,
        "duration": 7.0,
        "params": {
            "key_type": "harpsichord",
            "brightness": 0.35,
            "mod_index": 0.5,
            "decay_time": 0.4,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.1,
            "filter_cutoff": 3200.0,
            "reverb_wet": 0.18,
            "reverb_size": 0.3,
            "chorus_mix": 0.05,
            "delay_mix": 0.06,
            "delay_ms": 200,
            "eq_low": 0,
            "eq_mid": 2,
            "eq_high": -1,
            "stereo_width": 0.38,
        },
    },
    {
        "id": "FY3_KEY_067",
        "name": "GloRilla Bright Celesta",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "GloRilla - Tomorrow 2 (2022)",
        "instrument_breakdown": "Bright energetic celesta with sparkling attack. High-energy celestial keys for modern female trap anthems.",
        "note": 76,
        "duration": 6.0,
        "params": {
            "key_type": "celesta",
            "brightness": 0.65,
            "mod_index": 2.5,
            "decay_time": 1.0,
            "vibrato_rate": 3.0,
            "vibrato_depth": 0.1,
            "distortion": 0.0,
            "filter_cutoff": 7000.0,
            "reverb_wet": 0.18,
            "reverb_size": 0.28,
            "chorus_mix": 0.06,
            "delay_mix": 0.06,
            "delay_ms": 150,
            "eq_low": -2,
            "eq_mid": 0,
            "eq_high": 3,
            "stereo_width": 0.42,
        },
    },
    {
        "id": "FY3_KEY_068",
        "name": "GloRilla Party Vibes",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "GloRilla - FNF (2022)",
        "instrument_breakdown": "Bouncy vibraphone with party energy and bright shimmer. Fun jazzy keys for high-tempo crunk-trap crossover.",
        "note": 69,
        "duration": 6.0,
        "params": {
            "key_type": "vibraphone",
            "brightness": 0.6,
            "mod_index": 2.0,
            "decay_time": 1.0,
            "vibrato_rate": 4.0,
            "vibrato_depth": 0.2,
            "distortion": 0.0,
            "filter_cutoff": 6500.0,
            "reverb_wet": 0.15,
            "reverb_size": 0.25,
            "chorus_mix": 0.06,
            "delay_mix": 0.05,
            "delay_ms": 140,
            "eq_low": -1,
            "eq_mid": 1,
            "eq_high": 2,
            "stereo_width": 0.4,
        },
    },
    {
        "id": "FY3_KEY_069",
        "name": "Jeezy Soul Marimba",
        "category": "Keys",
        "era": "Early (2005-2010)",
        "inspiration": "Young Jeezy - Soul Survivor (2005)",
        "instrument_breakdown": "Warm soulful marimba with gospel-infused character. Wooden accent for motivational Snowman-era trap.",
        "note": 67,
        "duration": 7.0,
        "params": {
            "key_type": "marimba",
            "brightness": 0.45,
            "mod_index": 1.2,
            "decay_time": 0.42,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.0,
            "filter_cutoff": 3800.0,
            "reverb_wet": 0.22,
            "reverb_size": 0.35,
            "chorus_mix": 0.05,
            "delay_mix": 0.05,
            "delay_ms": 230,
            "eq_low": 0,
            "eq_mid": 1,
            "eq_high": 0,
            "stereo_width": 0.4,
        },
    },
    {
        "id": "FY3_KEY_070",
        "name": "Jeezy Clav Anthem",
        "category": "Keys",
        "era": "Early (2005-2010)",
        "inspiration": "Young Jeezy - Go Crazy (2005)",
        "instrument_breakdown": "Funky clavinet with celebratory energy. Anthemic funky keys for victory-lap trap hooks.",
        "note": 62,
        "duration": 7.0,
        "params": {
            "key_type": "clavinet",
            "brightness": 0.68,
            "mod_index": 0.0,
            "decay_time": 0.42,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.22,
            "filter_cutoff": 4500.0,
            "reverb_wet": 0.15,
            "reverb_size": 0.28,
            "chorus_mix": 0.05,
            "delay_mix": 0.05,
            "delay_ms": 200,
            "eq_low": -1,
            "eq_mid": 3,
            "eq_high": 2,
            "stereo_width": 0.42,
        },
    },
    {
        "id": "FY3_KEY_071",
        "name": "Usher Harpsichord Elegant",
        "category": "Keys",
        "era": "Peak (2010-2016)",
        "inspiration": "Usher - Papers (2010)",
        "instrument_breakdown": "Elegant harpsichord with warm tone and refined sustain. Classical pluck keys for sophisticated R&B productions.",
        "note": 64,
        "duration": 7.0,
        "params": {
            "key_type": "harpsichord",
            "brightness": 0.45,
            "mod_index": 0.5,
            "decay_time": 0.5,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.0,
            "filter_cutoff": 4500.0,
            "reverb_wet": 0.35,
            "reverb_size": 0.5,
            "chorus_mix": 0.08,
            "delay_mix": 0.08,
            "delay_ms": 280,
            "eq_low": 0,
            "eq_mid": 1,
            "eq_high": 1,
            "stereo_width": 0.5,
        },
    },
    {
        "id": "FY3_KEY_072",
        "name": "Waka Hard Harpsichord",
        "category": "Keys",
        "era": "Early (2005-2010)",
        "inspiration": "Waka Flocka Flame - No Hands (2010)",
        "instrument_breakdown": "Aggressive harpsichord with distorted edge and sharp pluck. Hard baroque keys for club-trap crossover.",
        "note": 60,
        "duration": 6.0,
        "params": {
            "key_type": "harpsichord",
            "brightness": 0.6,
            "mod_index": 0.5,
            "decay_time": 0.35,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.2,
            "filter_cutoff": 4200.0,
            "reverb_wet": 0.08,
            "reverb_size": 0.18,
            "chorus_mix": 0.0,
            "delay_mix": 0.0,
            "delay_ms": 0,
            "eq_low": -1,
            "eq_mid": 3,
            "eq_high": 2,
            "stereo_width": 0.3,
        },
    },
    {
        "id": "FY3_KEY_073",
        "name": "YB Moody Celesta",
        "category": "Keys",
        "era": "Modern (2016+)",
        "inspiration": "NBA YoungBoy - Colors (2020)",
        "instrument_breakdown": "Moody celesta with dark undertones and emotional resonance. Brooding celestial keys for confessional trap.",
        "note": 69,
        "duration": 8.0,
        "params": {
            "key_type": "celesta",
            "brightness": 0.4,
            "mod_index": 1.8,
            "decay_time": 1.5,
            "vibrato_rate": 3.0,
            "vibrato_depth": 0.15,
            "distortion": 0.0,
            "filter_cutoff": 5000.0,
            "reverb_wet": 0.42,
            "reverb_size": 0.58,
            "chorus_mix": 0.1,
            "delay_mix": 0.1,
            "delay_ms": 320,
            "eq_low": 0,
            "eq_mid": 1,
            "eq_high": 0,
            "stereo_width": 0.52,
        },
    },
    {
        "id": "FY3_KEY_074",
        "name": "Dolph Marimba Grit",
        "category": "Keys",
        "era": "Peak (2010-2016)",
        "inspiration": "Young Dolph - 100 Shots (2017)",
        "instrument_breakdown": "Gritty marimba with Memphis character and boosted mids. Hard wooden keys for confrontational street trap.",
        "note": 67,
        "duration": 6.0,
        "params": {
            "key_type": "marimba",
            "brightness": 0.5,
            "mod_index": 1.5,
            "decay_time": 0.32,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "distortion": 0.05,
            "filter_cutoff": 3800.0,
            "reverb_wet": 0.1,
            "reverb_size": 0.2,
            "chorus_mix": 0.0,
            "delay_mix": 0.05,
            "delay_ms": 160,
            "eq_low": 0,
            "eq_mid": 3,
            "eq_high": 1,
            "stereo_width": 0.32,
        },
    },
]
