"""FY3 Zaytoven Collection — Vocal Presets (50)."""

VOCAL_PRESETS = [
    # ──────────────────────────────────────────────
    # EARLY ERA (2005-2010) — Presets 001-016
    # ──────────────────────────────────────────────
    {
        "id": "FY3_VOX_001",
        "name": "Trap House Choir",
        "category": "Vocals",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'Trap House' (2005) — gospel choir stacks behind trap drums",
        "instrument_breakdown": "4-voice choir on 'ah' vowel, heavy reverb, slight vibrato",
        "note": 60,
        "duration": 8.0,
        "params": {
            "vocal_type": "choir",
            "vowel": "ah",
            "formant_shift": 0,
            "breathiness": 0.2,
            "vibrato_rate": 5.0,
            "vibrato_depth": 0.03,
            "n_voices": 4,
            "detune_cents": 12,
            "reverb_wet": 0.5,
            "reverb_size": 0.7,
            "delay_mix": 0.0,
            "delay_ms": 300,
            "distortion": 0.0,
            "eq_low": 0,
            "eq_mid": 1,
            "eq_high": 0,
            "stereo_width": 0.5,
        },
    },
    {
        "id": "FY3_VOX_002",
        "name": "So Icy Vocal Chop",
        "category": "Vocals",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'So Icy' (2005) — stuttered vocal hits riding over 808s",
        "instrument_breakdown": "Quick 'eh' chop with tight decay, slight formant pitch-up, dry mix",
        "note": 64,
        "duration": 6.0,
        "params": {
            "vocal_type": "vocal_chop",
            "vowel": "eh",
            "formant_shift": 2,
            "breathiness": 0.15,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 1,
            "detune_cents": 5,
            "reverb_wet": 0.15,
            "reverb_size": 0.3,
            "delay_mix": 0.1,
            "delay_ms": 125,
            "distortion": 0.05,
            "eq_low": -2,
            "eq_mid": 2,
            "eq_high": 1,
            "stereo_width": 0.3,
        },
    },
    {
        "id": "FY3_VOX_003",
        "name": "Chicken Talk Pad",
        "category": "Vocals",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'Chicken Talk' (2006) — warm vocal texture under organ leads",
        "instrument_breakdown": "Sustained 'ooh' vocal pad with gentle vibrato and wide reverb wash",
        "note": 60,
        "duration": 8.0,
        "params": {
            "vocal_type": "vocal_pad",
            "vowel": "ooh",
            "formant_shift": 0,
            "breathiness": 0.35,
            "vibrato_rate": 4.5,
            "vibrato_depth": 0.02,
            "n_voices": 2,
            "detune_cents": 10,
            "reverb_wet": 0.55,
            "reverb_size": 0.7,
            "delay_mix": 0.05,
            "delay_ms": 350,
            "distortion": 0.0,
            "eq_low": 1,
            "eq_mid": 0,
            "eq_high": -1,
            "stereo_width": 0.6,
        },
    },
    {
        "id": "FY3_VOX_004",
        "name": "Zone 6 Adlib Hey",
        "category": "Vocals",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'Trap House' (2005) — raw 'hey' adlib stabs punctuating bars",
        "instrument_breakdown": "Short percussive 'eh' stab with hard attack, mid-forward EQ, minimal reverb",
        "note": 67,
        "duration": 6.0,
        "params": {
            "vocal_type": "adlib",
            "vowel": "eh",
            "formant_shift": 3,
            "breathiness": 0.1,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 1,
            "detune_cents": 5,
            "reverb_wet": 0.1,
            "reverb_size": 0.2,
            "delay_mix": 0.05,
            "delay_ms": 100,
            "distortion": 0.1,
            "eq_low": -3,
            "eq_mid": 3,
            "eq_high": 2,
            "stereo_width": 0.2,
        },
    },
    {
        "id": "FY3_VOX_005",
        "name": "Burrprint Gospel Stack",
        "category": "Vocals",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'Burrprint 3D' (2009) — layered gospel choir behind hood anthems",
        "instrument_breakdown": "6-voice choir on 'oh' vowel, church reverb, wide stereo, warm low-mids",
        "note": 55,
        "duration": 8.0,
        "params": {
            "vocal_type": "choir",
            "vowel": "oh",
            "formant_shift": -2,
            "breathiness": 0.25,
            "vibrato_rate": 5.5,
            "vibrato_depth": 0.04,
            "n_voices": 6,
            "detune_cents": 15,
            "reverb_wet": 0.6,
            "reverb_size": 0.8,
            "delay_mix": 0.0,
            "delay_ms": 400,
            "distortion": 0.0,
            "eq_low": 2,
            "eq_mid": 1,
            "eq_high": -1,
            "stereo_width": 0.7,
        },
    },
    {
        "id": "FY3_VOX_006",
        "name": "Jeezy Vocal Rise",
        "category": "Vocals",
        "era": "Early (2005-2010)",
        "inspiration": "Young Jeezy 'The Inspiration' (2006) — vocal swell building into chorus drops",
        "instrument_breakdown": "Slow 'ah' riser with increasing breathiness, deep reverb, formant sweep upward",
        "note": 60,
        "duration": 7.0,
        "params": {
            "vocal_type": "vocal_rise",
            "vowel": "ah",
            "formant_shift": 4,
            "breathiness": 0.5,
            "vibrato_rate": 6.0,
            "vibrato_depth": 0.04,
            "n_voices": 2,
            "detune_cents": 20,
            "reverb_wet": 0.6,
            "reverb_size": 0.75,
            "delay_mix": 0.15,
            "delay_ms": 300,
            "distortion": 0.0,
            "eq_low": -1,
            "eq_mid": 0,
            "eq_high": 2,
            "stereo_width": 0.6,
        },
    },
    {
        "id": "FY3_VOX_007",
        "name": "Hard to Kill Drone",
        "category": "Vocals",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'Hard to Kill' (2006) — ominous vocal bed underneath dark piano loops",
        "instrument_breakdown": "Low 'ooh' drone with slow vibrato, dark EQ, heavy reverb tail",
        "note": 48,
        "duration": 8.0,
        "params": {
            "vocal_type": "vocal_drone",
            "vowel": "ooh",
            "formant_shift": -4,
            "breathiness": 0.4,
            "vibrato_rate": 4.0,
            "vibrato_depth": 0.02,
            "n_voices": 2,
            "detune_cents": 18,
            "reverb_wet": 0.65,
            "reverb_size": 0.85,
            "delay_mix": 0.05,
            "delay_ms": 500,
            "distortion": 0.05,
            "eq_low": 3,
            "eq_mid": 0,
            "eq_high": -3,
            "stereo_width": 0.5,
        },
    },
    {
        "id": "FY3_VOX_008",
        "name": "Waka Flocka Chop Stack",
        "category": "Vocals",
        "era": "Early (2005-2010)",
        "inspiration": "Waka Flocka 'Flockaveli' (2010) — aggressive vocal chops hitting with 808 kicks",
        "instrument_breakdown": "Pitched-down 'ah' chop with distortion grit, punchy mid-range, fast gate",
        "note": 55,
        "duration": 6.0,
        "params": {
            "vocal_type": "vocal_chop",
            "vowel": "ah",
            "formant_shift": -3,
            "breathiness": 0.1,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 1,
            "detune_cents": 8,
            "reverb_wet": 0.1,
            "reverb_size": 0.25,
            "delay_mix": 0.0,
            "delay_ms": 100,
            "distortion": 0.2,
            "eq_low": 1,
            "eq_mid": 3,
            "eq_high": -1,
            "stereo_width": 0.2,
        },
    },
    {
        "id": "FY3_VOX_009",
        "name": "State vs Radric Ethereal Pad",
        "category": "Vocals",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'The State vs Radric Davis' (2009) — airy vocal texture on polished tracks",
        "instrument_breakdown": "Breathy 'ee' pad with high formant shift, shimmery reverb, wide stereo spread",
        "note": 67,
        "duration": 8.0,
        "params": {
            "vocal_type": "vocal_pad",
            "vowel": "ee",
            "formant_shift": 5,
            "breathiness": 0.5,
            "vibrato_rate": 5.0,
            "vibrato_depth": 0.02,
            "n_voices": 3,
            "detune_cents": 15,
            "reverb_wet": 0.6,
            "reverb_size": 0.8,
            "delay_mix": 0.1,
            "delay_ms": 400,
            "distortion": 0.0,
            "eq_low": -2,
            "eq_mid": 0,
            "eq_high": 3,
            "stereo_width": 0.8,
        },
    },
    {
        "id": "FY3_VOX_010",
        "name": "Trap-A-Thon Dark Choir",
        "category": "Vocals",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'Trap-A-Thon' (2007) — menacing choir hit accenting bass drops",
        "instrument_breakdown": "3-voice dark choir on 'oh', low register, tight reverb, slight distortion edge",
        "note": 48,
        "duration": 7.0,
        "params": {
            "vocal_type": "choir",
            "vowel": "oh",
            "formant_shift": -3,
            "breathiness": 0.15,
            "vibrato_rate": 4.5,
            "vibrato_depth": 0.03,
            "n_voices": 3,
            "detune_cents": 10,
            "reverb_wet": 0.35,
            "reverb_size": 0.5,
            "delay_mix": 0.0,
            "delay_ms": 250,
            "distortion": 0.08,
            "eq_low": 2,
            "eq_mid": 1,
            "eq_high": -2,
            "stereo_width": 0.4,
        },
    },
    {
        "id": "FY3_VOX_011",
        "name": "Writing on the Wall Stutter",
        "category": "Vocals",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'Writing on the Wall' (2009) — rhythmic vocal glitch layered with bells",
        "instrument_breakdown": "Stuttered 'ee' chop with tight delay creating rhythmic pattern, bright EQ",
        "note": 72,
        "duration": 6.0,
        "params": {
            "vocal_type": "vocal_chop",
            "vowel": "ee",
            "formant_shift": 4,
            "breathiness": 0.1,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 1,
            "detune_cents": 5,
            "reverb_wet": 0.2,
            "reverb_size": 0.3,
            "delay_mix": 0.25,
            "delay_ms": 150,
            "distortion": 0.0,
            "eq_low": -3,
            "eq_mid": 1,
            "eq_high": 3,
            "stereo_width": 0.4,
        },
    },
    {
        "id": "FY3_VOX_012",
        "name": "OJ Juiceman Skrrt Stab",
        "category": "Vocals",
        "era": "Early (2005-2010)",
        "inspiration": "OJ Da Juiceman 'Make Tha Trap Say Aye' (2008) — percussive vocal stab on the one",
        "instrument_breakdown": "Sharp 'eh' adlib with high formant, maximum attack, lo-fi grit",
        "note": 69,
        "duration": 6.0,
        "params": {
            "vocal_type": "adlib",
            "vowel": "eh",
            "formant_shift": 5,
            "breathiness": 0.05,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 1,
            "detune_cents": 5,
            "reverb_wet": 0.08,
            "reverb_size": 0.15,
            "delay_mix": 0.0,
            "delay_ms": 80,
            "distortion": 0.15,
            "eq_low": -4,
            "eq_mid": 4,
            "eq_high": 2,
            "stereo_width": 0.1,
        },
    },
    {
        "id": "FY3_VOX_013",
        "name": "So Icy Whisper Choir",
        "category": "Vocals",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'So Icy' (2005) — hushed choir texture beneath icy synth melodies",
        "instrument_breakdown": "4-voice soft choir on 'ah' with high breathiness, wide reverb, ghostly presence",
        "note": 55,
        "duration": 8.0,
        "params": {
            "vocal_type": "choir",
            "vowel": "ah",
            "formant_shift": -2,
            "breathiness": 0.55,
            "vibrato_rate": 4.0,
            "vibrato_depth": 0.015,
            "n_voices": 4,
            "detune_cents": 22,
            "reverb_wet": 0.7,
            "reverb_size": 0.9,
            "delay_mix": 0.08,
            "delay_ms": 450,
            "distortion": 0.0,
            "eq_low": 1,
            "eq_mid": -1,
            "eq_high": -2,
            "stereo_width": 0.7,
        },
    },
    {
        "id": "FY3_VOX_014",
        "name": "Jeezy Put On Rise",
        "category": "Vocals",
        "era": "Early (2005-2010)",
        "inspiration": "Young Jeezy 'Put On' (2008) — dramatic vocal swell into hook section",
        "instrument_breakdown": "Building 'ooh' riser with increasing intensity, wide detune, heavy verb tail",
        "note": 60,
        "duration": 7.0,
        "params": {
            "vocal_type": "vocal_rise",
            "vowel": "ooh",
            "formant_shift": 6,
            "breathiness": 0.45,
            "vibrato_rate": 6.5,
            "vibrato_depth": 0.05,
            "n_voices": 3,
            "detune_cents": 25,
            "reverb_wet": 0.55,
            "reverb_size": 0.7,
            "delay_mix": 0.2,
            "delay_ms": 250,
            "distortion": 0.0,
            "eq_low": 0,
            "eq_mid": 1,
            "eq_high": 3,
            "stereo_width": 0.7,
        },
    },
    {
        "id": "FY3_VOX_015",
        "name": "Chicken Talk Warm Pad",
        "category": "Vocals",
        "era": "Early (2005-2010)",
        "inspiration": "Gucci Mane 'Chicken Talk' (2006) — warm vocal blanket under raw piano loops",
        "instrument_breakdown": "Soft 'ah' pad with low breathiness, warm EQ, medium reverb, gentle vibrato",
        "note": 60,
        "duration": 8.0,
        "params": {
            "vocal_type": "vocal_pad",
            "vowel": "ah",
            "formant_shift": -1,
            "breathiness": 0.3,
            "vibrato_rate": 4.5,
            "vibrato_depth": 0.02,
            "n_voices": 2,
            "detune_cents": 12,
            "reverb_wet": 0.45,
            "reverb_size": 0.6,
            "delay_mix": 0.05,
            "delay_ms": 300,
            "distortion": 0.0,
            "eq_low": 2,
            "eq_mid": 1,
            "eq_high": -2,
            "stereo_width": 0.5,
        },
    },
    {
        "id": "FY3_VOX_016",
        "name": "Flocka Bow Bow Adlib",
        "category": "Vocals",
        "era": "Early (2005-2010)",
        "inspiration": "Waka Flocka 'Hard in da Paint' (2010) — aggressive adlib stabs on every downbeat",
        "instrument_breakdown": "Distorted 'oh' stab with maximum attack, crushed mids, zero reverb for raw impact",
        "note": 60,
        "duration": 6.0,
        "params": {
            "vocal_type": "adlib",
            "vowel": "oh",
            "formant_shift": -2,
            "breathiness": 0.05,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 1,
            "detune_cents": 5,
            "reverb_wet": 0.05,
            "reverb_size": 0.1,
            "delay_mix": 0.0,
            "delay_ms": 80,
            "distortion": 0.3,
            "eq_low": 1,
            "eq_mid": 4,
            "eq_high": -1,
            "stereo_width": 0.1,
        },
    },
    # ──────────────────────────────────────────────
    # PEAK ERA (2010-2016) — Presets 017-033
    # ──────────────────────────────────────────────
    {
        "id": "FY3_VOX_017",
        "name": "Versace Choir Anthem",
        "category": "Vocals",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos 'Versace' (2013) — massive choir stab hitting with the hook",
        "instrument_breakdown": "8-voice choir on 'ah', maximum width, bright reverb, wide detune for anthem feel",
        "note": 60,
        "duration": 8.0,
        "params": {
            "vocal_type": "choir",
            "vowel": "ah",
            "formant_shift": 0,
            "breathiness": 0.2,
            "vibrato_rate": 5.5,
            "vibrato_depth": 0.03,
            "n_voices": 8,
            "detune_cents": 18,
            "reverb_wet": 0.5,
            "reverb_size": 0.7,
            "delay_mix": 0.05,
            "delay_ms": 280,
            "distortion": 0.0,
            "eq_low": 0,
            "eq_mid": 1,
            "eq_high": 2,
            "stereo_width": 0.9,
        },
    },
    {
        "id": "FY3_VOX_018",
        "name": "YRN Pitched Chop",
        "category": "Vocals",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos 'YRN' (2014) — pitched vocal chop riding triplet hi-hats",
        "instrument_breakdown": "High-pitched 'ee' chop with fast gate, rhythmic delay, clean formant shift up",
        "note": 72,
        "duration": 6.0,
        "params": {
            "vocal_type": "vocal_chop",
            "vowel": "ee",
            "formant_shift": 6,
            "breathiness": 0.1,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 1,
            "detune_cents": 5,
            "reverb_wet": 0.2,
            "reverb_size": 0.35,
            "delay_mix": 0.2,
            "delay_ms": 166,
            "distortion": 0.0,
            "eq_low": -3,
            "eq_mid": 0,
            "eq_high": 4,
            "stereo_width": 0.4,
        },
    },
    {
        "id": "FY3_VOX_019",
        "name": "DS2 Codeine Pad",
        "category": "Vocals",
        "era": "Peak (2010-2016)",
        "inspiration": "Future 'DS2' (2015) — murky vocal pad drenched in reverb and lean",
        "instrument_breakdown": "Dark 'ooh' pad with heavy breathiness, slow vibrato, massive reverb, low formant",
        "note": 55,
        "duration": 8.0,
        "params": {
            "vocal_type": "vocal_pad",
            "vowel": "ooh",
            "formant_shift": -4,
            "breathiness": 0.6,
            "vibrato_rate": 4.0,
            "vibrato_depth": 0.025,
            "n_voices": 3,
            "detune_cents": 20,
            "reverb_wet": 0.7,
            "reverb_size": 0.85,
            "delay_mix": 0.1,
            "delay_ms": 400,
            "distortion": 0.05,
            "eq_low": 2,
            "eq_mid": 0,
            "eq_high": -3,
            "stereo_width": 0.6,
        },
    },
    {
        "id": "FY3_VOX_020",
        "name": "Culture What Adlib",
        "category": "Vocals",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos 'Culture' (2017) — signature 'what' stab cutting through the beat",
        "instrument_breakdown": "Sharp 'ah' adlib with high formant, short decay, slight room verb for presence",
        "note": 65,
        "duration": 6.0,
        "params": {
            "vocal_type": "adlib",
            "vowel": "ah",
            "formant_shift": 4,
            "breathiness": 0.08,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 1,
            "detune_cents": 5,
            "reverb_wet": 0.12,
            "reverb_size": 0.25,
            "delay_mix": 0.08,
            "delay_ms": 120,
            "distortion": 0.08,
            "eq_low": -3,
            "eq_mid": 3,
            "eq_high": 3,
            "stereo_width": 0.2,
        },
    },
    {
        "id": "FY3_VOX_021",
        "name": "Monster Vocal Drone",
        "category": "Vocals",
        "era": "Peak (2010-2016)",
        "inspiration": "Future 'Monster' (2014) — dark sustained vocal texture beneath trap bass",
        "instrument_breakdown": "Low 'oh' drone with slight distortion, heavy reverb, minimal vibrato, sub-forward EQ",
        "note": 48,
        "duration": 8.0,
        "params": {
            "vocal_type": "vocal_drone",
            "vowel": "oh",
            "formant_shift": -6,
            "breathiness": 0.45,
            "vibrato_rate": 3.5,
            "vibrato_depth": 0.015,
            "n_voices": 2,
            "detune_cents": 20,
            "reverb_wet": 0.6,
            "reverb_size": 0.8,
            "delay_mix": 0.05,
            "delay_ms": 500,
            "distortion": 0.1,
            "eq_low": 4,
            "eq_mid": -1,
            "eq_high": -3,
            "stereo_width": 0.5,
        },
    },
    {
        "id": "FY3_VOX_022",
        "name": "Trap Back Choir Hit",
        "category": "Vocals",
        "era": "Peak (2010-2016)",
        "inspiration": "Gucci Mane 'Trap Back' (2012) — punchy choir stab on the snare accent",
        "instrument_breakdown": "5-voice choir on 'eh' with tight decay, aggressive mid-push, controlled reverb",
        "note": 60,
        "duration": 7.0,
        "params": {
            "vocal_type": "choir",
            "vowel": "eh",
            "formant_shift": 1,
            "breathiness": 0.15,
            "vibrato_rate": 5.0,
            "vibrato_depth": 0.02,
            "n_voices": 5,
            "detune_cents": 10,
            "reverb_wet": 0.3,
            "reverb_size": 0.45,
            "delay_mix": 0.0,
            "delay_ms": 200,
            "distortion": 0.05,
            "eq_low": 0,
            "eq_mid": 2,
            "eq_high": 1,
            "stereo_width": 0.5,
        },
    },
    {
        "id": "FY3_VOX_023",
        "name": "Papers R&B Vocal Pad",
        "category": "Vocals",
        "era": "Peak (2010-2016)",
        "inspiration": "Usher 'Papers' (2010) — silky vocal texture on Zaytoven's R&B crossover",
        "instrument_breakdown": "Smooth 'ooh' pad with lush vibrato, warm EQ, polished reverb, wide stereo",
        "note": 64,
        "duration": 8.0,
        "params": {
            "vocal_type": "vocal_pad",
            "vowel": "ooh",
            "formant_shift": 2,
            "breathiness": 0.4,
            "vibrato_rate": 5.5,
            "vibrato_depth": 0.035,
            "n_voices": 3,
            "detune_cents": 12,
            "reverb_wet": 0.5,
            "reverb_size": 0.65,
            "delay_mix": 0.08,
            "delay_ms": 300,
            "distortion": 0.0,
            "eq_low": 0,
            "eq_mid": 1,
            "eq_high": 2,
            "stereo_width": 0.7,
        },
    },
    {
        "id": "FY3_VOX_024",
        "name": "Everybody Looking Rise",
        "category": "Vocals",
        "era": "Peak (2010-2016)",
        "inspiration": "Gucci Mane 'Everybody Looking' (2016) — triumphant vocal swell on comeback anthem",
        "instrument_breakdown": "Building 'ah' riser with bright formant sweep, increasing detune, heavy delay wash",
        "note": 60,
        "duration": 7.0,
        "params": {
            "vocal_type": "vocal_rise",
            "vowel": "ah",
            "formant_shift": 8,
            "breathiness": 0.4,
            "vibrato_rate": 6.0,
            "vibrato_depth": 0.04,
            "n_voices": 4,
            "detune_cents": 28,
            "reverb_wet": 0.55,
            "reverb_size": 0.7,
            "delay_mix": 0.2,
            "delay_ms": 280,
            "distortion": 0.0,
            "eq_low": -1,
            "eq_mid": 0,
            "eq_high": 4,
            "stereo_width": 0.8,
        },
    },
    {
        "id": "FY3_VOX_025",
        "name": "No Label Chop Rhythm",
        "category": "Vocals",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos 'No Label 2' (2014) — rhythmic vocal chop synced to triplet flow",
        "instrument_breakdown": "Quick 'ah' chop with triplet delay, formant pitch-up, clean attack",
        "note": 67,
        "duration": 6.0,
        "params": {
            "vocal_type": "vocal_chop",
            "vowel": "ah",
            "formant_shift": 3,
            "breathiness": 0.12,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 1,
            "detune_cents": 5,
            "reverb_wet": 0.18,
            "reverb_size": 0.3,
            "delay_mix": 0.22,
            "delay_ms": 143,
            "distortion": 0.0,
            "eq_low": -2,
            "eq_mid": 1,
            "eq_high": 2,
            "stereo_width": 0.35,
        },
    },
    {
        "id": "FY3_VOX_026",
        "name": "HNDRXX Breathy Pad",
        "category": "Vocals",
        "era": "Peak (2010-2016)",
        "inspiration": "Future 'HNDRXX' (2017) — ethereal breathy vocal washing over melodic trap",
        "instrument_breakdown": "Airy 'ee' pad with high breathiness, bright formant, maximum reverb, gentle vibrato",
        "note": 67,
        "duration": 8.0,
        "params": {
            "vocal_type": "vocal_pad",
            "vowel": "ee",
            "formant_shift": 5,
            "breathiness": 0.65,
            "vibrato_rate": 5.0,
            "vibrato_depth": 0.02,
            "n_voices": 3,
            "detune_cents": 18,
            "reverb_wet": 0.7,
            "reverb_size": 0.85,
            "delay_mix": 0.12,
            "delay_ms": 380,
            "distortion": 0.0,
            "eq_low": -2,
            "eq_mid": 0,
            "eq_high": 4,
            "stereo_width": 0.8,
        },
    },
    {
        "id": "FY3_VOX_027",
        "name": "Versace Mama Adlib",
        "category": "Vocals",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos 'Versace' (2013) — 'mama' adlib punctuating between verse lines",
        "instrument_breakdown": "Bright 'ah' stab with slight delay tail, clean formant, present mids",
        "note": 64,
        "duration": 6.0,
        "params": {
            "vocal_type": "adlib",
            "vowel": "ah",
            "formant_shift": 2,
            "breathiness": 0.1,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 1,
            "detune_cents": 5,
            "reverb_wet": 0.15,
            "reverb_size": 0.3,
            "delay_mix": 0.1,
            "delay_ms": 140,
            "distortion": 0.05,
            "eq_low": -2,
            "eq_mid": 2,
            "eq_high": 2,
            "stereo_width": 0.25,
        },
    },
    {
        "id": "FY3_VOX_028",
        "name": "DS2 Dirty Chop",
        "category": "Vocals",
        "era": "Peak (2010-2016)",
        "inspiration": "Future 'DS2' (2015) — gritty pitched vocal stab through distorted chain",
        "instrument_breakdown": "Distorted 'oh' chop with low formant, crushed mid-range, gated reverb tail",
        "note": 55,
        "duration": 6.0,
        "params": {
            "vocal_type": "vocal_chop",
            "vowel": "oh",
            "formant_shift": -5,
            "breathiness": 0.15,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 1,
            "detune_cents": 8,
            "reverb_wet": 0.15,
            "reverb_size": 0.25,
            "delay_mix": 0.05,
            "delay_ms": 100,
            "distortion": 0.25,
            "eq_low": 1,
            "eq_mid": 3,
            "eq_high": -2,
            "stereo_width": 0.2,
        },
    },
    {
        "id": "FY3_VOX_029",
        "name": "Culture Gospel Choir",
        "category": "Vocals",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos 'Culture' (2017) — triumphant gospel choir layered on celebratory hooks",
        "instrument_breakdown": "7-voice choir on 'ah', bright reverb, wide stereo, uplifting formant, full vibrato",
        "note": 60,
        "duration": 8.0,
        "params": {
            "vocal_type": "choir",
            "vowel": "ah",
            "formant_shift": 2,
            "breathiness": 0.2,
            "vibrato_rate": 5.5,
            "vibrato_depth": 0.04,
            "n_voices": 7,
            "detune_cents": 15,
            "reverb_wet": 0.55,
            "reverb_size": 0.75,
            "delay_mix": 0.05,
            "delay_ms": 320,
            "distortion": 0.0,
            "eq_low": 0,
            "eq_mid": 1,
            "eq_high": 2,
            "stereo_width": 0.85,
        },
    },
    {
        "id": "FY3_VOX_030",
        "name": "Trap Back Haze Drone",
        "category": "Vocals",
        "era": "Peak (2010-2016)",
        "inspiration": "Gucci Mane 'Trap Back' (2012) — smoky vocal drone underneath heavy 808 patterns",
        "instrument_breakdown": "Evolving 'ah' drone with moderate distortion, dark EQ, wide reverb wash",
        "note": 50,
        "duration": 8.0,
        "params": {
            "vocal_type": "vocal_drone",
            "vowel": "ah",
            "formant_shift": -3,
            "breathiness": 0.5,
            "vibrato_rate": 3.5,
            "vibrato_depth": 0.02,
            "n_voices": 2,
            "detune_cents": 25,
            "reverb_wet": 0.65,
            "reverb_size": 0.85,
            "delay_mix": 0.08,
            "delay_ms": 450,
            "distortion": 0.12,
            "eq_low": 2,
            "eq_mid": 0,
            "eq_high": -3,
            "stereo_width": 0.6,
        },
    },
    {
        "id": "FY3_VOX_031",
        "name": "Everybody Looking Chop",
        "category": "Vocals",
        "era": "Peak (2010-2016)",
        "inspiration": "Gucci Mane 'Everybody Looking' (2016) — polished vocal chop on comeback intro",
        "instrument_breakdown": "Clean 'ooh' chop with pristine reverb, slight pitch-up, balanced EQ",
        "note": 67,
        "duration": 3.5,
        "params": {
            "vocal_type": "vocal_chop",
            "vowel": "ooh",
            "formant_shift": 3,
            "breathiness": 0.15,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 1,
            "detune_cents": 5,
            "reverb_wet": 0.3,
            "reverb_size": 0.45,
            "delay_mix": 0.12,
            "delay_ms": 200,
            "distortion": 0.0,
            "eq_low": -1,
            "eq_mid": 1,
            "eq_high": 2,
            "stereo_width": 0.4,
        },
    },
    {
        "id": "FY3_VOX_032",
        "name": "Monster Ominous Choir",
        "category": "Vocals",
        "era": "Peak (2010-2016)",
        "inspiration": "Future 'Monster' (2014) — ominous choir stab looming beneath dark bass drops",
        "instrument_breakdown": "4-voice dark choir on 'oh', low formant, distortion edge, heavy reverb, menacing",
        "note": 52,
        "duration": 4.5,
        "params": {
            "vocal_type": "choir",
            "vowel": "oh",
            "formant_shift": -6,
            "breathiness": 0.3,
            "vibrato_rate": 4.5,
            "vibrato_depth": 0.03,
            "n_voices": 4,
            "detune_cents": 15,
            "reverb_wet": 0.6,
            "reverb_size": 0.8,
            "delay_mix": 0.05,
            "delay_ms": 350,
            "distortion": 0.08,
            "eq_low": 2,
            "eq_mid": 0,
            "eq_high": -2,
            "stereo_width": 0.55,
        },
    },
    {
        "id": "FY3_VOX_033",
        "name": "YRN Skrrt Adlib",
        "category": "Vocals",
        "era": "Peak (2010-2016)",
        "inspiration": "Migos 'YRN' (2014) — sharp adlib stab between triplet flows",
        "instrument_breakdown": "Piercing 'ee' adlib with maximum formant shift, tight gate, no reverb for immediacy",
        "note": 72,
        "duration": 6.0,
        "params": {
            "vocal_type": "adlib",
            "vowel": "ee",
            "formant_shift": 7,
            "breathiness": 0.05,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 1,
            "detune_cents": 5,
            "reverb_wet": 0.05,
            "reverb_size": 0.1,
            "delay_mix": 0.05,
            "delay_ms": 100,
            "distortion": 0.1,
            "eq_low": -4,
            "eq_mid": 2,
            "eq_high": 5,
            "stereo_width": 0.15,
        },
    },
    # ──────────────────────────────────────────────
    # MODERN ERA (2016+) — Presets 034-050
    # ──────────────────────────────────────────────
    {
        "id": "FY3_VOX_034",
        "name": "21 Savage Dark Choir",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "21 Savage 'a lot' (2018) — somber choir stacks on introspective trap",
        "instrument_breakdown": "4-voice dark choir on 'oh', low register, brooding reverb, minimal vibrato",
        "note": 52,
        "duration": 8.0,
        "params": {
            "vocal_type": "choir",
            "vowel": "oh",
            "formant_shift": -4,
            "breathiness": 0.3,
            "vibrato_rate": 4.0,
            "vibrato_depth": 0.02,
            "n_voices": 4,
            "detune_cents": 14,
            "reverb_wet": 0.55,
            "reverb_size": 0.75,
            "delay_mix": 0.05,
            "delay_ms": 380,
            "distortion": 0.0,
            "eq_low": 2,
            "eq_mid": 1,
            "eq_high": -2,
            "stereo_width": 0.55,
        },
    },
    {
        "id": "FY3_VOX_035",
        "name": "GloRilla Anthem Choir",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "GloRilla 'Tomorrow 2' (2022) — massive female choir energy on trap anthem",
        "instrument_breakdown": "8-voice bright choir on 'ee', high energy, wide stereo, vibrant reverb",
        "note": 64,
        "duration": 8.0,
        "params": {
            "vocal_type": "choir",
            "vowel": "ee",
            "formant_shift": 3,
            "breathiness": 0.15,
            "vibrato_rate": 6.0,
            "vibrato_depth": 0.04,
            "n_voices": 8,
            "detune_cents": 20,
            "reverb_wet": 0.45,
            "reverb_size": 0.65,
            "delay_mix": 0.08,
            "delay_ms": 250,
            "distortion": 0.0,
            "eq_low": -1,
            "eq_mid": 2,
            "eq_high": 3,
            "stereo_width": 0.9,
        },
    },
    {
        "id": "FY3_VOX_036",
        "name": "Uzi Pitched Chop High",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "Lil Uzi Vert 'XO Tour Llif3' (2017) — pitched-up vocal chop on melodic trap",
        "instrument_breakdown": "High-pitched 'ooh' chop with max formant shift, sparkly delay, airy character",
        "note": 72,
        "duration": 6.0,
        "params": {
            "vocal_type": "vocal_chop",
            "vowel": "ooh",
            "formant_shift": 8,
            "breathiness": 0.2,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 1,
            "detune_cents": 8,
            "reverb_wet": 0.3,
            "reverb_size": 0.45,
            "delay_mix": 0.18,
            "delay_ms": 180,
            "distortion": 0.0,
            "eq_low": -4,
            "eq_mid": -1,
            "eq_high": 5,
            "stereo_width": 0.5,
        },
    },
    {
        "id": "FY3_VOX_037",
        "name": "Young Dolph Memphis Pad",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "Young Dolph 'Preach' (2017) — warm vocal pad beneath Memphis street anthems",
        "instrument_breakdown": "Smooth 'ah' pad with moderate breathiness, warm low-mids, steady vibrato, wide verb",
        "note": 60,
        "duration": 8.0,
        "params": {
            "vocal_type": "vocal_pad",
            "vowel": "ah",
            "formant_shift": 0,
            "breathiness": 0.35,
            "vibrato_rate": 5.0,
            "vibrato_depth": 0.025,
            "n_voices": 2,
            "detune_cents": 14,
            "reverb_wet": 0.5,
            "reverb_size": 0.65,
            "delay_mix": 0.08,
            "delay_ms": 320,
            "distortion": 0.0,
            "eq_low": 1,
            "eq_mid": 1,
            "eq_high": 0,
            "stereo_width": 0.6,
        },
    },
    {
        "id": "FY3_VOX_038",
        "name": "NBA Youngboy Raw Adlib",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "NBA Youngboy 'No Smoke' (2017) — raw percussive vocal stab with street energy",
        "instrument_breakdown": "Aggressive 'eh' adlib with distortion, hard mid-push, zero reverb for in-your-face impact",
        "note": 65,
        "duration": 6.0,
        "params": {
            "vocal_type": "adlib",
            "vowel": "eh",
            "formant_shift": 1,
            "breathiness": 0.05,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 1,
            "detune_cents": 5,
            "reverb_wet": 0.05,
            "reverb_size": 0.1,
            "delay_mix": 0.0,
            "delay_ms": 80,
            "distortion": 0.25,
            "eq_low": -2,
            "eq_mid": 4,
            "eq_high": 1,
            "stereo_width": 0.1,
        },
    },
    {
        "id": "FY3_VOX_039",
        "name": "Takeoff Celestial Pad",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "Takeoff 'The Last Rocket' (2018) — celestial vocal wash on spacey trap production",
        "instrument_breakdown": "Ethereal 'ee' pad with high breathiness, max reverb, bright formant, wide spread",
        "note": 67,
        "duration": 8.0,
        "params": {
            "vocal_type": "vocal_pad",
            "vowel": "ee",
            "formant_shift": 6,
            "breathiness": 0.6,
            "vibrato_rate": 4.5,
            "vibrato_depth": 0.02,
            "n_voices": 3,
            "detune_cents": 20,
            "reverb_wet": 0.7,
            "reverb_size": 0.9,
            "delay_mix": 0.12,
            "delay_ms": 400,
            "distortion": 0.0,
            "eq_low": -2,
            "eq_mid": 0,
            "eq_high": 4,
            "stereo_width": 0.85,
        },
    },
    {
        "id": "FY3_VOX_040",
        "name": "21 Savage Sub Drone",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "21 Savage 'Issa Album' (2017) — deep vocal drone underneath deadpan delivery",
        "instrument_breakdown": "Low 'ooh' drone at bottom register, heavy sub, slow evolving texture, max reverb",
        "note": 48,
        "duration": 8.0,
        "params": {
            "vocal_type": "vocal_drone",
            "vowel": "ooh",
            "formant_shift": -8,
            "breathiness": 0.4,
            "vibrato_rate": 3.0,
            "vibrato_depth": 0.015,
            "n_voices": 2,
            "detune_cents": 18,
            "reverb_wet": 0.7,
            "reverb_size": 0.9,
            "delay_mix": 0.05,
            "delay_ms": 500,
            "distortion": 0.05,
            "eq_low": 4,
            "eq_mid": -2,
            "eq_high": -4,
            "stereo_width": 0.5,
        },
    },
    {
        "id": "FY3_VOX_041",
        "name": "GloRilla Hype Rise",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "GloRilla 'F.N.F.' (2022) — energy-building vocal swell into anthemic drop",
        "instrument_breakdown": "Bright 'ah' riser with fast formant sweep, increasing voices, explosive reverb tail",
        "note": 64,
        "duration": 7.0,
        "params": {
            "vocal_type": "vocal_rise",
            "vowel": "ah",
            "formant_shift": 10,
            "breathiness": 0.35,
            "vibrato_rate": 7.0,
            "vibrato_depth": 0.05,
            "n_voices": 4,
            "detune_cents": 30,
            "reverb_wet": 0.5,
            "reverb_size": 0.7,
            "delay_mix": 0.2,
            "delay_ms": 200,
            "distortion": 0.0,
            "eq_low": -1,
            "eq_mid": 1,
            "eq_high": 4,
            "stereo_width": 0.8,
        },
    },
    {
        "id": "FY3_VOX_042",
        "name": "Uzi Vert Glitch Chop",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "Lil Uzi Vert 'Eternal Atake' (2020) — glitchy stuttered vocal cutting through synths",
        "instrument_breakdown": "Stuttered 'ee' chop with rapid delay, formant glitch, tight gate, clean mix",
        "note": 69,
        "duration": 6.0,
        "params": {
            "vocal_type": "vocal_chop",
            "vowel": "ee",
            "formant_shift": 7,
            "breathiness": 0.08,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 1,
            "detune_cents": 5,
            "reverb_wet": 0.15,
            "reverb_size": 0.25,
            "delay_mix": 0.3,
            "delay_ms": 100,
            "distortion": 0.05,
            "eq_low": -3,
            "eq_mid": 1,
            "eq_high": 4,
            "stereo_width": 0.45,
        },
    },
    {
        "id": "FY3_VOX_043",
        "name": "Dolph Key Glock Choir",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "Young Dolph & Key Glock 'Dum and Dummer' (2019) — hard choir stab on Memphis trap",
        "instrument_breakdown": "5-voice tight choir on 'eh', aggressive attack, mid-forward, controlled stereo",
        "note": 57,
        "duration": 7.0,
        "params": {
            "vocal_type": "choir",
            "vowel": "eh",
            "formant_shift": -1,
            "breathiness": 0.12,
            "vibrato_rate": 4.5,
            "vibrato_depth": 0.025,
            "n_voices": 5,
            "detune_cents": 10,
            "reverb_wet": 0.35,
            "reverb_size": 0.5,
            "delay_mix": 0.0,
            "delay_ms": 220,
            "distortion": 0.08,
            "eq_low": 1,
            "eq_mid": 2,
            "eq_high": 0,
            "stereo_width": 0.5,
        },
    },
    {
        "id": "FY3_VOX_044",
        "name": "Youngboy Melodic Pad",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "NBA Youngboy 'AI YoungBoy 2' (2019) — melodic vocal texture on emotional trap",
        "instrument_breakdown": "Warm 'ooh' pad with expressive vibrato, moderate breathiness, lush reverb wash",
        "note": 62,
        "duration": 8.0,
        "params": {
            "vocal_type": "vocal_pad",
            "vowel": "ooh",
            "formant_shift": 1,
            "breathiness": 0.4,
            "vibrato_rate": 5.5,
            "vibrato_depth": 0.035,
            "n_voices": 2,
            "detune_cents": 15,
            "reverb_wet": 0.55,
            "reverb_size": 0.7,
            "delay_mix": 0.1,
            "delay_ms": 340,
            "distortion": 0.0,
            "eq_low": 0,
            "eq_mid": 1,
            "eq_high": 1,
            "stereo_width": 0.6,
        },
    },
    {
        "id": "FY3_VOX_045",
        "name": "Savage Mode Drone",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "21 Savage 'Savage Mode II' (2020) — menacing vocal drone under Metro-style 808s",
        "instrument_breakdown": "Dissonant 'eh' drone with formant tension, slight distortion, evolving texture",
        "note": 50,
        "duration": 8.0,
        "params": {
            "vocal_type": "vocal_drone",
            "vowel": "eh",
            "formant_shift": -5,
            "breathiness": 0.5,
            "vibrato_rate": 3.5,
            "vibrato_depth": 0.02,
            "n_voices": 2,
            "detune_cents": 25,
            "reverb_wet": 0.6,
            "reverb_size": 0.8,
            "delay_mix": 0.08,
            "delay_ms": 480,
            "distortion": 0.1,
            "eq_low": 3,
            "eq_mid": 0,
            "eq_high": -2,
            "stereo_width": 0.55,
        },
    },
    {
        "id": "FY3_VOX_046",
        "name": "Takeoff Cosmos Chop",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "Takeoff 'Casper' (2018) — spacey pitched vocal chop floating over cosmic trap",
        "instrument_breakdown": "Airy 'ah' chop with high pitch, sparkly reverb, wide delay, clean formant",
        "note": 72,
        "duration": 3.5,
        "params": {
            "vocal_type": "vocal_chop",
            "vowel": "ah",
            "formant_shift": 9,
            "breathiness": 0.25,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 1,
            "detune_cents": 10,
            "reverb_wet": 0.4,
            "reverb_size": 0.6,
            "delay_mix": 0.2,
            "delay_ms": 220,
            "distortion": 0.0,
            "eq_low": -3,
            "eq_mid": 0,
            "eq_high": 4,
            "stereo_width": 0.6,
        },
    },
    {
        "id": "FY3_VOX_047",
        "name": "GloRilla Gang Adlib",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "GloRilla 'Blessed' (2023) — sharp hype adlib cutting through bass-heavy mix",
        "instrument_breakdown": "Bright 'oh' stab with high formant energy, cutting mids, zero delay for punch",
        "note": 67,
        "duration": 6.0,
        "params": {
            "vocal_type": "adlib",
            "vowel": "oh",
            "formant_shift": 5,
            "breathiness": 0.08,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 1,
            "detune_cents": 5,
            "reverb_wet": 0.1,
            "reverb_size": 0.2,
            "delay_mix": 0.0,
            "delay_ms": 80,
            "distortion": 0.12,
            "eq_low": -3,
            "eq_mid": 3,
            "eq_high": 3,
            "stereo_width": 0.2,
        },
    },
    {
        "id": "FY3_VOX_048",
        "name": "Modern Trap Gospel Rise",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "21 Savage 'a lot' (2018) — gospel-tinged vocal swell on introspective trap moments",
        "instrument_breakdown": "Choir-like 'ah' riser with multiple voices, formant ascension, spiritual reverb",
        "note": 60,
        "duration": 4.5,
        "params": {
            "vocal_type": "vocal_rise",
            "vowel": "ah",
            "formant_shift": 6,
            "breathiness": 0.35,
            "vibrato_rate": 5.5,
            "vibrato_depth": 0.04,
            "n_voices": 4,
            "detune_cents": 22,
            "reverb_wet": 0.6,
            "reverb_size": 0.8,
            "delay_mix": 0.15,
            "delay_ms": 300,
            "distortion": 0.0,
            "eq_low": 0,
            "eq_mid": 1,
            "eq_high": 2,
            "stereo_width": 0.75,
        },
    },
    {
        "id": "FY3_VOX_049",
        "name": "Dolph Smoke Pad",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "Young Dolph 'Rich Slave' (2020) — smoky vocal pad drifting under Memphis trap",
        "instrument_breakdown": "Warm 'ah' pad with moderate breathiness, evolving formant, deep reverb wash, gentle vibrato",
        "note": 57,
        "duration": 8.0,
        "params": {
            "vocal_type": "vocal_pad",
            "vowel": "ah",
            "formant_shift": -3,
            "breathiness": 0.5,
            "vibrato_rate": 4.5,
            "vibrato_depth": 0.025,
            "n_voices": 2,
            "detune_cents": 16,
            "reverb_wet": 0.6,
            "reverb_size": 0.75,
            "delay_mix": 0.08,
            "delay_ms": 360,
            "distortion": 0.0,
            "eq_low": 1,
            "eq_mid": 1,
            "eq_high": -1,
            "stereo_width": 0.6,
        },
    },
    {
        "id": "FY3_VOX_050",
        "name": "Youngboy Pain Choir",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "NBA Youngboy 'Top' (2020) — emotional choir wash behind vulnerable verses",
        "instrument_breakdown": "6-voice choir on 'ooh', expressive vibrato, wide reverb, bittersweet formant coloring",
        "note": 60,
        "duration": 8.0,
        "params": {
            "vocal_type": "choir",
            "vowel": "ooh",
            "formant_shift": -1,
            "breathiness": 0.25,
            "vibrato_rate": 5.5,
            "vibrato_depth": 0.04,
            "n_voices": 6,
            "detune_cents": 16,
            "reverb_wet": 0.55,
            "reverb_size": 0.75,
            "delay_mix": 0.05,
            "delay_ms": 350,
            "distortion": 0.0,
            "eq_low": 1,
            "eq_mid": 1,
            "eq_high": 0,
            "stereo_width": 0.7,
        },
    },
    # ──────────────────────────────────────────────
    # UNDERREPRESENTED ARTISTS — Presets 051-074
    # ──────────────────────────────────────────────
    {
        "id": "FY3_VOX_051",
        "name": "Usher Confessions Choir",
        "category": "Vocals",
        "era": "Peak (2010-2016)",
        "inspiration": "Usher 'Confessions Part II' (2004) — lush gospel choir bed under R&B vocals",
        "instrument_breakdown": "6-voice choir on 'ah', warm formant, slow vibrato, wide reverb wash, smooth R&B texture",
        "note": 60,
        "duration": 8.0,
        "params": {
            "vocal_type": "choir",
            "vowel": "ah",
            "formant_shift": 0,
            "breathiness": 0.2,
            "vibrato_rate": 4.5,
            "vibrato_depth": 0.035,
            "n_voices": 6,
            "detune_cents": 14,
            "reverb_wet": 0.6,
            "reverb_size": 0.8,
            "delay_mix": 0.1,
            "delay_ms": 300,
            "distortion": 0.0,
            "eq_low": 1,
            "eq_mid": 2,
            "eq_high": 0,
            "stereo_width": 0.75,
        },
    },
    {
        "id": "FY3_VOX_052",
        "name": "Usher Climax Vocal Pad",
        "category": "Vocals",
        "era": "Peak (2010-2016)",
        "inspiration": "Usher 'Climax' (2012) — ethereal vocal pad floating beneath falsetto",
        "instrument_breakdown": "4-voice vocal pad on 'ooh', breathy texture, high formant shift, long reverb tail, intimate feel",
        "note": 67,
        "duration": 7.5,
        "params": {
            "vocal_type": "vocal_pad",
            "vowel": "ooh",
            "formant_shift": 3,
            "breathiness": 0.45,
            "vibrato_rate": 3.5,
            "vibrato_depth": 0.025,
            "n_voices": 4,
            "detune_cents": 18,
            "reverb_wet": 0.7,
            "reverb_size": 0.85,
            "delay_mix": 0.15,
            "delay_ms": 400,
            "distortion": 0.0,
            "eq_low": -1,
            "eq_mid": 1,
            "eq_high": 2,
            "stereo_width": 0.85,
        },
    },
    {
        "id": "FY3_VOX_053",
        "name": "Usher Love Vocal Rise",
        "category": "Vocals",
        "era": "Peak (2010-2016)",
        "inspiration": "Usher 'Love In This Club' (2008) — sweeping vocal rise building into chorus drop",
        "instrument_breakdown": "Vocal rise on 'ee', smooth upward sweep, moderate reverb, building energy for transitions",
        "note": 64,
        "duration": 6.5,
        "params": {
            "vocal_type": "vocal_rise",
            "vowel": "ee",
            "formant_shift": 2,
            "breathiness": 0.3,
            "vibrato_rate": 6.0,
            "vibrato_depth": 0.04,
            "n_voices": 3,
            "detune_cents": 10,
            "reverb_wet": 0.5,
            "reverb_size": 0.7,
            "delay_mix": 0.2,
            "delay_ms": 250,
            "distortion": 0.0,
            "eq_low": 0,
            "eq_mid": 2,
            "eq_high": 1,
            "stereo_width": 0.65,
        },
    },
    {
        "id": "FY3_VOX_054",
        "name": "Flocka Hard Adlib Stack",
        "category": "Vocals",
        "era": "Early (2005-2010)",
        "inspiration": "Waka Flocka 'Hard In Da Paint' (2010) — aggressive layered adlib hits, raw energy",
        "instrument_breakdown": "Punchy 'eh' adlib, tight decay, slight distortion, dry mix, aggressive stacking",
        "note": 55,
        "duration": 6.0,
        "params": {
            "vocal_type": "adlib",
            "vowel": "eh",
            "formant_shift": -2,
            "breathiness": 0.1,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 2,
            "detune_cents": 5,
            "reverb_wet": 0.15,
            "reverb_size": 0.25,
            "delay_mix": 0.05,
            "delay_ms": 100,
            "distortion": 0.2,
            "eq_low": 2,
            "eq_mid": 3,
            "eq_high": -1,
            "stereo_width": 0.4,
        },
    },
    {
        "id": "FY3_VOX_055",
        "name": "Flocka Grove Street Chop",
        "category": "Vocals",
        "era": "Early (2005-2010)",
        "inspiration": "Waka Flocka 'Grove St. Party' (2010) — chopped vocal stabs driving the hook",
        "instrument_breakdown": "Quick vocal chop on 'ah', rhythmic gating, low formant, gritty distortion edge",
        "note": 52,
        "duration": 6.0,
        "params": {
            "vocal_type": "vocal_chop",
            "vowel": "ah",
            "formant_shift": -3,
            "breathiness": 0.05,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 1,
            "detune_cents": 3,
            "reverb_wet": 0.1,
            "reverb_size": 0.2,
            "delay_mix": 0.1,
            "delay_ms": 150,
            "distortion": 0.25,
            "eq_low": 3,
            "eq_mid": 2,
            "eq_high": -2,
            "stereo_width": 0.35,
        },
    },
    {
        "id": "FY3_VOX_056",
        "name": "Quavo Stir Fry Vocal Chop",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "Migos 'Stir Fry' (2018) — melodic vocal chop accents, bright and bouncy",
        "instrument_breakdown": "Bright 'ee' chop, high formant, clean tone, tight delay for rhythmic bounce",
        "note": 69,
        "duration": 6.0,
        "params": {
            "vocal_type": "vocal_chop",
            "vowel": "ee",
            "formant_shift": 4,
            "breathiness": 0.15,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 1,
            "detune_cents": 6,
            "reverb_wet": 0.3,
            "reverb_size": 0.45,
            "delay_mix": 0.2,
            "delay_ms": 175,
            "distortion": 0.0,
            "eq_low": -1,
            "eq_mid": 1,
            "eq_high": 3,
            "stereo_width": 0.6,
        },
    },
    {
        "id": "FY3_VOX_057",
        "name": "Quavo Motorsport Choir",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "Migos 'Motorsport' (2017) — atmospheric choir bed behind Quavo's melodic hook",
        "instrument_breakdown": "5-voice choir on 'ooh', bright formant, medium reverb, sparkling high-end",
        "note": 65,
        "duration": 7.5,
        "params": {
            "vocal_type": "choir",
            "vowel": "ooh",
            "formant_shift": 2,
            "breathiness": 0.25,
            "vibrato_rate": 5.0,
            "vibrato_depth": 0.03,
            "n_voices": 5,
            "detune_cents": 15,
            "reverb_wet": 0.5,
            "reverb_size": 0.7,
            "delay_mix": 0.1,
            "delay_ms": 300,
            "distortion": 0.0,
            "eq_low": 0,
            "eq_mid": 1,
            "eq_high": 2,
            "stereo_width": 0.7,
        },
    },
    {
        "id": "FY3_VOX_058",
        "name": "Offset Clout Vocal Drone",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "Offset 'Clout' (2019) — dark sustained vocal drone anchoring the beat",
        "instrument_breakdown": "Deep vocal drone on 'oh', low formant, heavy reverb, dark coloring, menacing undertone",
        "note": 48,
        "duration": 8.0,
        "params": {
            "vocal_type": "vocal_drone",
            "vowel": "oh",
            "formant_shift": -3,
            "breathiness": 0.1,
            "vibrato_rate": 2.0,
            "vibrato_depth": 0.02,
            "n_voices": 3,
            "detune_cents": 20,
            "reverb_wet": 0.65,
            "reverb_size": 0.9,
            "delay_mix": 0.05,
            "delay_ms": 500,
            "distortion": 0.05,
            "eq_low": 3,
            "eq_mid": 0,
            "eq_high": -2,
            "stereo_width": 0.8,
        },
    },
    {
        "id": "FY3_VOX_059",
        "name": "Offset Ric Flair Adlib",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "Offset 'Ric Flair Drip' (2017) — punchy adlib stabs cutting through the mix",
        "instrument_breakdown": "Sharp 'ah' adlib hit, tight attack, moderate distortion, dry and aggressive",
        "note": 57,
        "duration": 6.0,
        "params": {
            "vocal_type": "adlib",
            "vowel": "ah",
            "formant_shift": -1,
            "breathiness": 0.08,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 1,
            "detune_cents": 4,
            "reverb_wet": 0.2,
            "reverb_size": 0.3,
            "delay_mix": 0.08,
            "delay_ms": 125,
            "distortion": 0.15,
            "eq_low": 1,
            "eq_mid": 3,
            "eq_high": 0,
            "stereo_width": 0.45,
        },
    },
    {
        "id": "FY3_VOX_060",
        "name": "Takeoff Takeoff Vocal Rise",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "Takeoff 'Last Memory' (2018) — sweeping vocal build powering verse transitions",
        "instrument_breakdown": "Vocal rise on 'ah', fast sweep, bright formant, clean with slight delay tail",
        "note": 62,
        "duration": 6.5,
        "params": {
            "vocal_type": "vocal_rise",
            "vowel": "ah",
            "formant_shift": 1,
            "breathiness": 0.2,
            "vibrato_rate": 5.5,
            "vibrato_depth": 0.035,
            "n_voices": 2,
            "detune_cents": 8,
            "reverb_wet": 0.4,
            "reverb_size": 0.6,
            "delay_mix": 0.15,
            "delay_ms": 200,
            "distortion": 0.0,
            "eq_low": 0,
            "eq_mid": 2,
            "eq_high": 1,
            "stereo_width": 0.55,
        },
    },
    {
        "id": "FY3_VOX_061",
        "name": "Takeoff Intruder Chop",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "Takeoff 'Intruder' (2018) — rapid-fire vocal chop accents matching triplet flow",
        "instrument_breakdown": "Fast 'eh' chop, tight gating, clean tone, minimal reverb, precision rhythmic hits",
        "note": 66,
        "duration": 6.0,
        "params": {
            "vocal_type": "vocal_chop",
            "vowel": "eh",
            "formant_shift": 2,
            "breathiness": 0.1,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 1,
            "detune_cents": 5,
            "reverb_wet": 0.2,
            "reverb_size": 0.35,
            "delay_mix": 0.12,
            "delay_ms": 150,
            "distortion": 0.0,
            "eq_low": -1,
            "eq_mid": 2,
            "eq_high": 2,
            "stereo_width": 0.5,
        },
    },
    {
        "id": "FY3_VOX_062",
        "name": "Youngboy Lonely Choir",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "NBA Youngboy 'Lonely Child' (2019) — haunting choir behind raw emotional delivery",
        "instrument_breakdown": "5-voice choir on 'ooh', dark formant, deep reverb, melancholic vibrato, emotional wash",
        "note": 58,
        "duration": 8.0,
        "params": {
            "vocal_type": "choir",
            "vowel": "ooh",
            "formant_shift": -2,
            "breathiness": 0.3,
            "vibrato_rate": 5.0,
            "vibrato_depth": 0.04,
            "n_voices": 5,
            "detune_cents": 18,
            "reverb_wet": 0.6,
            "reverb_size": 0.85,
            "delay_mix": 0.1,
            "delay_ms": 350,
            "distortion": 0.0,
            "eq_low": 2,
            "eq_mid": 1,
            "eq_high": -1,
            "stereo_width": 0.75,
        },
    },
    {
        "id": "FY3_VOX_063",
        "name": "Youngboy Slime Adlib",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "NBA Youngboy 'Slime Belief' (2020) — aggressive adlib punches behind verses",
        "instrument_breakdown": "Hard 'ah' adlib, low formant, distorted edge, tight and confrontational",
        "note": 50,
        "duration": 6.0,
        "params": {
            "vocal_type": "adlib",
            "vowel": "ah",
            "formant_shift": -4,
            "breathiness": 0.05,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 1,
            "detune_cents": 3,
            "reverb_wet": 0.15,
            "reverb_size": 0.2,
            "delay_mix": 0.05,
            "delay_ms": 100,
            "distortion": 0.3,
            "eq_low": 2,
            "eq_mid": 3,
            "eq_high": -2,
            "stereo_width": 0.3,
        },
    },
    {
        "id": "FY3_VOX_064",
        "name": "Youngboy Pain Vocal Pad",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "NBA Youngboy 'No Smoke' (2017) — sustained vocal pad bed, emotional undertow",
        "instrument_breakdown": "Warm vocal pad on 'ah', breathy texture, wide detune, deep reverb, vulnerable character",
        "note": 55,
        "duration": 7.5,
        "params": {
            "vocal_type": "vocal_pad",
            "vowel": "ah",
            "formant_shift": -1,
            "breathiness": 0.4,
            "vibrato_rate": 4.0,
            "vibrato_depth": 0.03,
            "n_voices": 4,
            "detune_cents": 22,
            "reverb_wet": 0.65,
            "reverb_size": 0.8,
            "delay_mix": 0.1,
            "delay_ms": 400,
            "distortion": 0.0,
            "eq_low": 1,
            "eq_mid": 0,
            "eq_high": -1,
            "stereo_width": 0.8,
        },
    },
    {
        "id": "FY3_VOX_065",
        "name": "OJ Juice Vocal Chop",
        "category": "Vocals",
        "era": "Early (2005-2010)",
        "inspiration": "OJ Da Juiceman 'Make Da Trap Say Aye' (2009) — stuttered vocal chop riding the beat",
        "instrument_breakdown": "Quick 'aye' chop, vintage formant, slight saturation, classic trap vocal texture",
        "note": 63,
        "duration": 6.0,
        "params": {
            "vocal_type": "vocal_chop",
            "vowel": "ah",
            "formant_shift": 1,
            "breathiness": 0.15,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 1,
            "detune_cents": 7,
            "reverb_wet": 0.25,
            "reverb_size": 0.4,
            "delay_mix": 0.15,
            "delay_ms": 175,
            "distortion": 0.1,
            "eq_low": 0,
            "eq_mid": 2,
            "eq_high": 1,
            "stereo_width": 0.5,
        },
    },
    {
        "id": "FY3_VOX_066",
        "name": "OJ Juiceman Adlib Stack",
        "category": "Vocals",
        "era": "Early (2005-2010)",
        "inspiration": "OJ Da Juiceman 'I'm Getting Money' (2008) — trademark stacked adlib energy",
        "instrument_breakdown": "Layered 'eh' adlib, gritty formant, raw texture, punchy with analog warmth",
        "note": 59,
        "duration": 6.0,
        "params": {
            "vocal_type": "adlib",
            "vowel": "eh",
            "formant_shift": 0,
            "breathiness": 0.1,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 2,
            "detune_cents": 8,
            "reverb_wet": 0.2,
            "reverb_size": 0.35,
            "delay_mix": 0.1,
            "delay_ms": 150,
            "distortion": 0.15,
            "eq_low": 1,
            "eq_mid": 2,
            "eq_high": 0,
            "stereo_width": 0.45,
        },
    },
    {
        "id": "FY3_VOX_067",
        "name": "Dolph Memphis Vocal Drone",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "Young Dolph 'Preach' (2016) — heavy droning vocal bed, Memphis darkness",
        "instrument_breakdown": "Deep vocal drone on 'oh', dark formant, heavy bass, sustained Memphis atmosphere",
        "note": 49,
        "duration": 8.0,
        "params": {
            "vocal_type": "vocal_drone",
            "vowel": "oh",
            "formant_shift": -4,
            "breathiness": 0.08,
            "vibrato_rate": 1.5,
            "vibrato_depth": 0.02,
            "n_voices": 3,
            "detune_cents": 22,
            "reverb_wet": 0.55,
            "reverb_size": 0.8,
            "delay_mix": 0.05,
            "delay_ms": 450,
            "distortion": 0.1,
            "eq_low": 3,
            "eq_mid": 0,
            "eq_high": -3,
            "stereo_width": 0.7,
        },
    },
    {
        "id": "FY3_VOX_068",
        "name": "Dolph 100 Shots Choir",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "Young Dolph '100 Shots' (2017) — defiant choir wash behind street anthem",
        "instrument_breakdown": "4-voice choir on 'ah', gritty Memphis tone, moderate reverb, raw power",
        "note": 53,
        "duration": 7.5,
        "params": {
            "vocal_type": "choir",
            "vowel": "ah",
            "formant_shift": -2,
            "breathiness": 0.15,
            "vibrato_rate": 4.5,
            "vibrato_depth": 0.03,
            "n_voices": 4,
            "detune_cents": 14,
            "reverb_wet": 0.45,
            "reverb_size": 0.65,
            "delay_mix": 0.08,
            "delay_ms": 300,
            "distortion": 0.08,
            "eq_low": 2,
            "eq_mid": 1,
            "eq_high": -1,
            "stereo_width": 0.6,
        },
    },
    {
        "id": "FY3_VOX_069",
        "name": "GloRilla FNF Adlib",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "GloRilla 'F.N.F.' (2022) — energetic female adlib hits, crunk energy",
        "instrument_breakdown": "Bright 'ee' adlib, high formant, punchy attack, clean and energetic",
        "note": 70,
        "duration": 6.0,
        "params": {
            "vocal_type": "adlib",
            "vowel": "ee",
            "formant_shift": 4,
            "breathiness": 0.12,
            "vibrato_rate": 0.0,
            "vibrato_depth": 0.0,
            "n_voices": 1,
            "detune_cents": 5,
            "reverb_wet": 0.25,
            "reverb_size": 0.4,
            "delay_mix": 0.12,
            "delay_ms": 125,
            "distortion": 0.05,
            "eq_low": -1,
            "eq_mid": 2,
            "eq_high": 3,
            "stereo_width": 0.55,
        },
    },
    {
        "id": "FY3_VOX_070",
        "name": "GloRilla Tomorrow Vocal Rise",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "GloRilla 'Tomorrow 2' (2022) — building vocal sweep into explosive hook",
        "instrument_breakdown": "Vocal rise on 'ooh', bright sweep, energetic climb, clean and powerful",
        "note": 68,
        "duration": 6.5,
        "params": {
            "vocal_type": "vocal_rise",
            "vowel": "ooh",
            "formant_shift": 3,
            "breathiness": 0.2,
            "vibrato_rate": 6.5,
            "vibrato_depth": 0.04,
            "n_voices": 2,
            "detune_cents": 10,
            "reverb_wet": 0.4,
            "reverb_size": 0.55,
            "delay_mix": 0.18,
            "delay_ms": 200,
            "distortion": 0.0,
            "eq_low": -1,
            "eq_mid": 1,
            "eq_high": 2,
            "stereo_width": 0.6,
        },
    },
    {
        "id": "FY3_VOX_071",
        "name": "Jeezy Snowman Choir",
        "category": "Vocals",
        "era": "Early (2005-2010)",
        "inspiration": "Young Jeezy 'Soul Survivor' (2005) — massive gospel choir anchoring the anthemic hook",
        "instrument_breakdown": "6-voice choir on 'ah', powerful gospel tone, deep reverb, wide stereo, anthemic",
        "note": 56,
        "duration": 8.0,
        "params": {
            "vocal_type": "choir",
            "vowel": "ah",
            "formant_shift": 0,
            "breathiness": 0.18,
            "vibrato_rate": 5.5,
            "vibrato_depth": 0.04,
            "n_voices": 6,
            "detune_cents": 16,
            "reverb_wet": 0.6,
            "reverb_size": 0.85,
            "delay_mix": 0.08,
            "delay_ms": 350,
            "distortion": 0.0,
            "eq_low": 2,
            "eq_mid": 2,
            "eq_high": 0,
            "stereo_width": 0.8,
        },
    },
    {
        "id": "FY3_VOX_072",
        "name": "Jeezy Trap Or Die Vocal Drone",
        "category": "Vocals",
        "era": "Early (2005-2010)",
        "inspiration": "Young Jeezy 'Trap or Die' (2005) — sustained vocal drone bed, street gravity",
        "instrument_breakdown": "Low vocal drone on 'oh', deep formant, heavy reverb, commanding presence",
        "note": 50,
        "duration": 8.0,
        "params": {
            "vocal_type": "vocal_drone",
            "vowel": "oh",
            "formant_shift": -3,
            "breathiness": 0.1,
            "vibrato_rate": 2.0,
            "vibrato_depth": 0.02,
            "n_voices": 3,
            "detune_cents": 20,
            "reverb_wet": 0.55,
            "reverb_size": 0.8,
            "delay_mix": 0.05,
            "delay_ms": 400,
            "distortion": 0.05,
            "eq_low": 3,
            "eq_mid": 1,
            "eq_high": -2,
            "stereo_width": 0.7,
        },
    },
    {
        "id": "FY3_VOX_073",
        "name": "Quavo Huncho Vocal Pad",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "Quavo 'Workin Me' (2018) — shimmering vocal pad layered under melodic hooks",
        "instrument_breakdown": "Airy vocal pad on 'ee', bright formant, wide detune, glassy reverb, atmospheric",
        "note": 71,
        "duration": 7.5,
        "params": {
            "vocal_type": "vocal_pad",
            "vowel": "ee",
            "formant_shift": 3,
            "breathiness": 0.35,
            "vibrato_rate": 4.0,
            "vibrato_depth": 0.025,
            "n_voices": 4,
            "detune_cents": 20,
            "reverb_wet": 0.65,
            "reverb_size": 0.8,
            "delay_mix": 0.15,
            "delay_ms": 350,
            "distortion": 0.0,
            "eq_low": -2,
            "eq_mid": 1,
            "eq_high": 3,
            "stereo_width": 0.85,
        },
    },
    {
        "id": "FY3_VOX_074",
        "name": "Offset Father Of 4 Choir",
        "category": "Vocals",
        "era": "Modern (2016+)",
        "inspiration": "Offset 'Father of 4' (2019) — emotional choir wash beneath introspective verses",
        "instrument_breakdown": "5-voice choir on 'ooh', warm formant, medium-dark tone, wide reverb, soulful depth",
        "note": 60,
        "duration": 8.0,
        "params": {
            "vocal_type": "choir",
            "vowel": "ooh",
            "formant_shift": -1,
            "breathiness": 0.25,
            "vibrato_rate": 5.0,
            "vibrato_depth": 0.035,
            "n_voices": 5,
            "detune_cents": 16,
            "reverb_wet": 0.55,
            "reverb_size": 0.75,
            "delay_mix": 0.1,
            "delay_ms": 300,
            "distortion": 0.0,
            "eq_low": 1,
            "eq_mid": 1,
            "eq_high": 0,
            "stereo_width": 0.7,
        },
    },
]
